package tracekinds

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
)

func WriteTraceKinds(outPath string, kinds []string, breadcrumbLabels []string) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: Trace/Trace.go Kind* constants + BreadcrumbLabels. Regenerate with: npm run gen:node-defs`)
	fmt.Fprintln(w)
	fmt.Fprintf(w, "export const TRACE_EVENT_KINDS = [")
	for i, k := range kinds {
		if i > 0 {
			fmt.Fprint(w, ", ")
		}
		fmt.Fprintf(w, "%q", k)
	}
	fmt.Fprintln(w, "] as const;")
	fmt.Fprintln(w)
	fmt.Fprintln(w, `export type TraceEventKind = (typeof TRACE_EVENT_KINDS)[number];`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// BREADCRUMB_LABELS is indexed by the buffer EVENT block's Label column`)
	fmt.Fprintln(w, `// (Kind==KindBreadcrumb rows only) — see Trace.go's BreadcrumbLabel* consts.`)
	fmt.Fprintf(w, "export const BREADCRUMB_LABELS = [")
	for i, l := range breadcrumbLabels {
		if i > 0 {
			fmt.Fprint(w, ", ")
		}
		fmt.Fprintf(w, "%q", l)
	}
	fmt.Fprintln(w, "] as const;")

	w.Flush()
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}
