// GENERATED by src/Chrome/Panels/Panel/gen — do not edit.
// Source: the PANEL_FLAGS block in src/Input/messages.ts.
// Regenerate with: go generate ./...
//
// The same paths src/Chrome/Panels/Panel/paths/ hands the renderer. Neither
// side builds this string itself.

package Panel

// FlagPath maps a flag to its file, relative to the SCENE ROOT.
var FlagPath = map[string]string{
	"overlays":     "view/panels/overlays.bin",
	"node":         "view/panels/node.bin",
	"nodeShape":    "view/panels/nodeShape.bin",
	"nodeState":    "view/panels/nodeState.bin",
	"nodePoles":    "view/panels/nodePoles.bin",
	"nodeRules":    "view/panels/nodeRules.bin",
	"scene":        "view/panels/scene.bin",
	"sceneGuides":  "view/panels/sceneGuides.bin",
	"scenePoles":   "view/panels/scenePoles.bin",
	"sceneVectors": "view/panels/sceneVectors.bin",
	"sceneLabels":  "view/panels/sceneLabels.bin",
}
