// GENERATED by Start/extension/runner/gen — do not edit.
// Source: Drag's kinds.go — the runner names one input slot file per event kind.
// Regenerate with: go generate ./...

export const IN_EVENT_KINDS = ["pointerdown", "pointermove", "pointerup", "wheel", "home", "delete", "key"] as const;

