// GENERATED by src/Node/Wiring/nodegeom/gen — do not edit.
// Source: src/NodeKinds/<Kind>/SPEC.md ## Ports table.
// Regenerate with: go generate ./...

package portwiring

// KindPorts maps each runtime kind to the inputs and outputs its SPEC.md
// declares, in the same order the table lists them. RegisterBuilder reads
// this instead of taking a hand-written list, so a kind declares its ports
// in one place and the runtime and the editor cannot disagree about them.
var KindPorts = map[string][]PortSpec{
	"HoldFlip": {
		{Name: "In", Dir: PortIn},
		{Name: "Out", Dir: PortOut},
	},
	"Input": {
		{Name: "OutCadence", Dir: PortOut},
		{Name: "ToExcitatory", Dir: PortOut},
		{Name: "FeedbackIn", Dir: PortIn},
	},
	"NormalSum": {
		{Name: "NormalA", Dir: PortIn},
		{Name: "NormalB", Dir: PortIn},
		{Name: "Out", Dir: PortOut},
	},
	"Pacer": {
		{Name: "In", Dir: PortIn},
		{Name: "FeedbackOut", Dir: PortOut},
	},
	"PairNode": {
		{Name: "In", Dir: PortIn},
		{Name: "Out", Dir: PortOut},
	},
	"Pulse": {
		{Name: "In", Dir: PortIn},
		{Name: "Out", Dir: PortOut},
		{Name: "OutFanout", Dir: PortOut},
	},
	"PulseLeft": {
		{Name: "In", Dir: PortIn},
		{Name: "Out", Dir: PortOut},
	},
	"PulseRight": {
		{Name: "In", Dir: PortIn},
		{Name: "Out", Dir: PortOut},
	},
	"SelectLeft": {
		{Name: "FromLeft", Dir: PortIn},
		{Name: "FromRight", Dir: PortIn},
		{Name: "ToPassed", Dir: PortOut},
	},
	"SelectRight": {
		{Name: "FromLeft", Dir: PortIn},
		{Name: "FromRight", Dir: PortIn},
		{Name: "ToPassed", Dir: PortOut},
	},
	"Time": {
		{Name: "In", Dir: PortIn},
		{Name: "ToNext", Dir: PortBroadcast},
	},
	"TimeEnd": {
		{Name: "In", Dir: PortIn},
	},
	"TimeStart": {
		{Name: "In", Dir: PortIn},
		{Name: "ToNext", Dir: PortBroadcast},
	},
}
