// GENERATED by tools/gen-node-defs. Do not edit.
// Source: the Edge block(s) in this directory.

import {
  COL_STREAM_BASE_EDGE,
} from "../Buffer/column-streams-gen";

export const COL_STREAM_EDGE_SX = COL_STREAM_BASE_EDGE + 0;
export const COL_STREAM_EDGE_SY = COL_STREAM_BASE_EDGE + 1;
export const COL_STREAM_EDGE_SZ = COL_STREAM_BASE_EDGE + 2;
export const COL_STREAM_EDGE_EX = COL_STREAM_BASE_EDGE + 3;
export const COL_STREAM_EDGE_EY = COL_STREAM_BASE_EDGE + 4;
export const COL_STREAM_EDGE_EZ = COL_STREAM_BASE_EDGE + 5;
export const COL_STREAM_EDGE_SRC_NODE_ROW = COL_STREAM_BASE_EDGE + 6;
export const COL_STREAM_EDGE_DST_NODE_ROW = COL_STREAM_BASE_EDGE + 7;
export const COL_STREAM_EDGE_DELTA_R = COL_STREAM_BASE_EDGE + 8;
export const COL_STREAM_EDGE_DRAG_ACTIVE = COL_STREAM_BASE_EDGE + 9;
export const COL_STREAM_EDGE_LABEL = COL_STREAM_BASE_EDGE + 10;
