// GENERATED by Categories/Node/ChannelVectors/values from VectorValueNames in
// vector_values.go — do not edit.
//
// One block file per node, holding the channel vectors leaving it. The row
// sits in the path, not in the file.

export const VECTOR_VALUE_NAMES = [
  "channelShaftM0",
  "channelShaftM1",
  "channelShaftM2",
  "channelShaftM3",
  "channelShaftM4",
  "channelShaftM5",
  "channelShaftM6",
  "channelShaftM7",
  "channelShaftM8",
  "channelShaftM9",
  "channelShaftM10",
  "channelShaftM11",
  "channelShaftM12",
  "channelShaftM13",
  "channelShaftM14",
  "channelShaftM15",
  "channelHeadM0",
  "channelHeadM1",
  "channelHeadM2",
  "channelHeadM3",
  "channelHeadM4",
  "channelHeadM5",
  "channelHeadM6",
  "channelHeadM7",
  "channelHeadM8",
  "channelHeadM9",
  "channelHeadM10",
  "channelHeadM11",
  "channelHeadM12",
  "channelHeadM13",
  "channelHeadM14",
  "channelHeadM15",
] as const;

export type VectorValueName = (typeof VECTOR_VALUE_NAMES)[number];
