// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/bufschema/layout.go  Regenerate: cd tools/topology-vscode && npm run gen:node-defs
// BUF_LAYOUT_FINGERPRINT: version:43|interiorSlotsPerNode:4|block:Node[NodeId:i32:0,CX:f32:4,CY:f32:8,CZ:f32:12,Radius:f32:16,SphereR:f32:20,VRX:f32:24,VRY:f32:28,VRZ:f32:32,FRX:f32:36,FRY:f32:40,FRZ:f32:44,PolePhi:f32:48,PoleTheta:f32:52,RingAxisPhi:f32:56,RingAxisTheta:f32:60,TopTiltVectorLen:f32:64,TopTiltVectorIdx:i32:68,TopTiltVectorPhi:f32:72,BottomTiltVectorPhi:f32:76,CoplanarNormalPhi:f32:80,ReceivedVectorLen:f32:84,ReceivedVectorPhi:f32:88,Selected:u8:92,KindId:u8:93,LabelOff:u32:94,LabelLen:u32:98,Hovered:u8:102,LatchedSel:u8:103,LatticePoints:u8:104,RoundsToParallel:i32:105,MsgsToParallel:i32:109]:stride:113|block:Interior[Present:u8:0,Value:i32:1,OX:f32:5,OY:f32:9,OZ:f32:13]:stride:17|block:Edge[SX:f32:0,SY:f32:4,SZ:f32:8,EX:f32:12,EY:f32:16,EZ:f32:20,SrcNodeRow:i32:24,EdgeLabelOff:u32:28,EdgeLabelLen:u32:32]:stride:36|block:EdgeBead[X:f32:0,Y:f32:4,Z:f32:8,Value:i32:12]:stride:16|block:Camera[PX:f32:0,PY:f32:4,PZ:f32:8,R:f32:12,PosPhi:f32:16,PosTheta:f32:20,UpPhi:f32:24,UpTheta:f32:28]:stride:32|block:Overlay[SceneTori:u8:0,ScenePoles:u8:1,NodePoles:u8:2,Handholds:u8:3,LabelsGlobal:u8:4,OverlaysVis:u8:5,NodeBody:u8:6,NodeRing:u8:7,RingPick:u8:8,SelectionRing:u8:9,HoverRing:u8:10,ReachSphere:u8:11,SceneVectors:u8:12,CommEdges:u8:13,DragNodeRow:i32:14,EditRefused:u32:18,SceneEditable:u8:22,SceneKinds:u32:23,GroupLenTime:f32:27,GroupLenInput:f32:31,GroupLenGate:f32:35,Speed:f32:39]:stride:43|block:Panel[Overlays:u8:0,Node:u8:1,NodeShape:u8:2,NodeState:u8:3,NodeReach:u8:4,NodePoles:u8:5,Scene:u8:6,SceneGuides:u8:7,ScenePoles:u8:8,SceneVectors:u8:9,SceneLabels:u8:10]:stride:11|block:Scene[CX:f32:0,CY:f32:4,CZ:f32:8,Radius:f32:12]:stride:16|block:Event[Kind:u8:0,NodeRow:i32:1,PortRow:i32:5,TargetRow:i32:9,TargetPortRow:i32:13,EdgeRow:i32:17,Slot:i32:21,Value:i32:25,Bead:u32:29,BeadSteps:f32:33,SimLatencyMs:f32:37,X:f32:41,Y:f32:45,Z:f32:49,F:f32:53,Label:u8:57,Debug:u8:58,TextOff:u32:59,TextLen:u32:63]:stride:67

package Buffer

import (
	"encoding/binary"
	"math"
)

// ── Edge block ───────────────────────────────────────────────
const (
	BufEdgeColSX           = 0  // f32
	BufEdgeColSY           = 4  // f32
	BufEdgeColSZ           = 8  // f32
	BufEdgeColEX           = 12 // f32
	BufEdgeColEY           = 16 // f32
	BufEdgeColEZ           = 20 // f32
	BufEdgeColSrcNodeRow   = 24 // i32
	BufEdgeColEdgeLabelOff = 28 // u32
	BufEdgeColEdgeLabelLen = 32 // u32
	BufEdgeStride          = 36
)

// SetEdgeRow writes one Edge row into buf[row*BufEdgeStride:].
func SetEdgeRow(buf []byte, row int, sX float32, sY float32, sZ float32, eX float32, eY float32, eZ float32, srcNodeRow int32, edgeLabelOff uint32, edgeLabelLen uint32) {
	off := row * BufEdgeStride
	binary.LittleEndian.PutUint32(buf[off+0:], math.Float32bits(sX))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(sY))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(sZ))
	binary.LittleEndian.PutUint32(buf[off+12:], math.Float32bits(eX))
	binary.LittleEndian.PutUint32(buf[off+16:], math.Float32bits(eY))
	binary.LittleEndian.PutUint32(buf[off+20:], math.Float32bits(eZ))
	binary.LittleEndian.PutUint32(buf[off+24:], uint32(srcNodeRow))
	binary.LittleEndian.PutUint32(buf[off+28:], edgeLabelOff)
	binary.LittleEndian.PutUint32(buf[off+32:], edgeLabelLen)
}

// ── EdgeBead block ───────────────────────────────────────────
const (
	BufEdgeBeadColX     = 0  // f32
	BufEdgeBeadColY     = 4  // f32
	BufEdgeBeadColZ     = 8  // f32
	BufEdgeBeadColValue = 12 // i32
	BufEdgeBeadStride   = 16
)

// SetEdgeBeadRow writes one EdgeBead row into buf[row*BufEdgeBeadStride:].
func SetEdgeBeadRow(buf []byte, row int, x float32, y float32, z float32, value int32) {
	off := row * BufEdgeBeadStride
	binary.LittleEndian.PutUint32(buf[off+0:], math.Float32bits(x))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(y))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(z))
	binary.LittleEndian.PutUint32(buf[off+12:], uint32(value))
}

// ── Event block ──────────────────────────────────────────────
const (
	BufEventColKind          = 0  // u8
	BufEventColNodeRow       = 1  // i32
	BufEventColPortRow       = 5  // i32
	BufEventColTargetRow     = 9  // i32
	BufEventColTargetPortRow = 13 // i32
	BufEventColEdgeRow       = 17 // i32
	BufEventColSlot          = 21 // i32
	BufEventColValue         = 25 // i32
	BufEventColBead          = 29 // u32
	BufEventColBeadSteps     = 33 // f32
	BufEventColSimLatencyMs  = 37 // f32
	BufEventColX             = 41 // f32
	BufEventColY             = 45 // f32
	BufEventColZ             = 49 // f32
	BufEventColF             = 53 // f32
	BufEventColLabel         = 57 // u8
	BufEventColDebug         = 58 // u8
	BufEventColTextOff       = 59 // u32
	BufEventColTextLen       = 63 // u32
	BufEventStride           = 67
)

// SetEventRow writes one Event row into buf[row*BufEventStride:].
func SetEventRow(buf []byte, row int, kind uint8, nodeRow int32, portRow int32, targetRow int32, targetPortRow int32, edgeRow int32, slot int32, value int32, bead uint32, beadSteps float32, simLatencyMs float32, x float32, y float32, z float32, f float32, label uint8, debug uint8, textOff uint32, textLen uint32) {
	off := row * BufEventStride
	buf[off+0] = kind
	binary.LittleEndian.PutUint32(buf[off+1:], uint32(nodeRow))
	binary.LittleEndian.PutUint32(buf[off+5:], uint32(portRow))
	binary.LittleEndian.PutUint32(buf[off+9:], uint32(targetRow))
	binary.LittleEndian.PutUint32(buf[off+13:], uint32(targetPortRow))
	binary.LittleEndian.PutUint32(buf[off+17:], uint32(edgeRow))
	binary.LittleEndian.PutUint32(buf[off+21:], uint32(slot))
	binary.LittleEndian.PutUint32(buf[off+25:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+29:], bead)
	binary.LittleEndian.PutUint32(buf[off+33:], math.Float32bits(beadSteps))
	binary.LittleEndian.PutUint32(buf[off+37:], math.Float32bits(simLatencyMs))
	binary.LittleEndian.PutUint32(buf[off+41:], math.Float32bits(x))
	binary.LittleEndian.PutUint32(buf[off+45:], math.Float32bits(y))
	binary.LittleEndian.PutUint32(buf[off+49:], math.Float32bits(z))
	binary.LittleEndian.PutUint32(buf[off+53:], math.Float32bits(f))
	buf[off+57] = label
	buf[off+58] = debug
	binary.LittleEndian.PutUint32(buf[off+59:], textOff)
	binary.LittleEndian.PutUint32(buf[off+63:], textLen)
}
