// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/bufschema/layout.go  Regenerate: cd tools/topology-vscode && npm run gen:node-defs
// BUF_LAYOUT_FINGERPRINT: version:42|interiorSlotsPerNode:4|block:Node[NodeId:i32:0,CX:f32:4,CY:f32:8,CZ:f32:12,Radius:f32:16,SphereR:f32:20,VRX:f32:24,VRY:f32:28,VRZ:f32:32,FRX:f32:36,FRY:f32:40,FRZ:f32:44,PolePhi:f32:48,PoleTheta:f32:52,RingAxisPhi:f32:56,RingAxisTheta:f32:60,TopTiltVectorLen:f32:64,TopTiltVectorTheta:f32:68,BottomTiltVectorTheta:f32:72,CoplanarNormalTheta:f32:76,ReceivedVectorLen:f32:80,ReceivedVectorTheta:f32:84,Selected:u8:88,KindId:u8:89,LabelOff:u32:90,LabelLen:u32:94,Hovered:u8:98,LatchedSel:u8:99,LatticePoints:u8:100,RoundsToParallel:i32:101,MsgsToParallel:i32:105]:stride:109|block:ChainBead[OX:f32:0,OY:f32:4,OZ:f32:8,Lit:u8:12,LitValue:i32:13]:stride:17|block:OutPole[DX:f32:0,DY:f32:4,DZ:f32:8]:stride:12|block:Interior[Present:u8:0,Value:i32:1,OX:f32:5,OY:f32:9,OZ:f32:13]:stride:17|block:Edge[SX:f32:0,SY:f32:4,SZ:f32:8,EX:f32:12,EY:f32:16,EZ:f32:20,EdgeLabelOff:u32:24,EdgeLabelLen:u32:28]:stride:32|block:Camera[PX:f32:0,PY:f32:4,PZ:f32:8,R:f32:12,PosPhi:f32:16,PosTheta:f32:20,UpPhi:f32:24,UpTheta:f32:28]:stride:32|block:Overlay[SceneTori:u8:0,ScenePoles:u8:1,NodePoles:u8:2,SelSpherePoles:u8:3,Handholds:u8:4,LabelsGlobal:u8:5,OverlaysVis:u8:6,NodeBody:u8:7,NodeRing:u8:8,RingPick:u8:9,SelectionRing:u8:10,HoverRing:u8:11,ReachSphere:u8:12,SceneVectors:u8:13,DragNodeRow:i32:14,EditRefused:u32:18,SceneEditable:u8:22,SceneKinds:u32:23,GroupLenTime:f32:27,GroupLenInput:f32:31,GroupLenGate:f32:35,Speed:f32:39]:stride:43|block:Scene[CX:f32:0,CY:f32:4,CZ:f32:8,Radius:f32:12]:stride:16|block:Event[Kind:u8:0,NodeRow:i32:1,PortRow:i32:5,TargetRow:i32:9,TargetPortRow:i32:13,EdgeRow:i32:17,Slot:i32:21,Value:i32:25,Bead:u32:29,BeadSteps:f32:33,SimLatencyMs:f32:37,X:f32:41,Y:f32:45,Z:f32:49,F:f32:53,Label:u8:57,Debug:u8:58,TextOff:u32:59,TextLen:u32:63]:stride:67

package Buffer

import (
	"encoding/binary"
	"math"
)

// ── Camera block ─────────────────────────────────────────────
const (
	BufCameraColPX       = 0  // f32
	BufCameraColPY       = 4  // f32
	BufCameraColPZ       = 8  // f32
	BufCameraColR        = 12 // f32
	BufCameraColPosPhi   = 16 // f32
	BufCameraColPosTheta = 20 // f32
	BufCameraColUpPhi    = 24 // f32
	BufCameraColUpTheta  = 28 // f32
	BufCameraStride      = 32
)

// SetCameraRow writes the Camera row into buf (always 1 row; no row param).
func SetCameraRow(buf []byte, pX float32, pY float32, pZ float32, r float32, posPhi float32, posTheta float32, upPhi float32, upTheta float32) {
	binary.LittleEndian.PutUint32(buf[0:], math.Float32bits(pX))
	binary.LittleEndian.PutUint32(buf[4:], math.Float32bits(pY))
	binary.LittleEndian.PutUint32(buf[8:], math.Float32bits(pZ))
	binary.LittleEndian.PutUint32(buf[12:], math.Float32bits(r))
	binary.LittleEndian.PutUint32(buf[16:], math.Float32bits(posPhi))
	binary.LittleEndian.PutUint32(buf[20:], math.Float32bits(posTheta))
	binary.LittleEndian.PutUint32(buf[24:], math.Float32bits(upPhi))
	binary.LittleEndian.PutUint32(buf[28:], math.Float32bits(upTheta))
}

// ── Overlay block ────────────────────────────────────────────
const (
	BufOverlayColSceneTori      = 0  // u8
	BufOverlayColScenePoles     = 1  // u8
	BufOverlayColNodePoles      = 2  // u8
	BufOverlayColSelSpherePoles = 3  // u8
	BufOverlayColHandholds      = 4  // u8
	BufOverlayColLabelsGlobal   = 5  // u8
	BufOverlayColOverlaysVis    = 6  // u8
	BufOverlayColNodeBody       = 7  // u8
	BufOverlayColNodeRing       = 8  // u8
	BufOverlayColRingPick       = 9  // u8
	BufOverlayColSelectionRing  = 10 // u8
	BufOverlayColHoverRing      = 11 // u8
	BufOverlayColReachSphere    = 12 // u8
	BufOverlayColSceneVectors   = 13 // u8
	BufOverlayColDragNodeRow    = 14 // i32
	BufOverlayColEditRefused    = 18 // u32
	BufOverlayColSceneEditable  = 22 // u8
	BufOverlayColSceneKinds     = 23 // u32
	BufOverlayColGroupLenTime   = 27 // f32
	BufOverlayColGroupLenInput  = 31 // f32
	BufOverlayColGroupLenGate   = 35 // f32
	BufOverlayColSpeed          = 39 // f32
	BufOverlayStride            = 43
)

// OverlayRow is the named-field snapshot of the Overlay block (single row).
// Passed BY VALUE to SetOverlayRow so the write call never enumerates fields
// positionally — closes the swapped-adjacent-uint8-args hazard a positional
// writer call would otherwise compile silently.
type OverlayRow struct {
	SceneTori      uint8
	ScenePoles     uint8
	NodePoles      uint8
	SelSpherePoles uint8
	Handholds      uint8
	LabelsGlobal   uint8
	OverlaysVis    uint8
	NodeBody       uint8
	NodeRing       uint8
	RingPick       uint8
	SelectionRing  uint8
	HoverRing      uint8
	ReachSphere    uint8
	SceneVectors   uint8
	DragNodeRow    int32
	EditRefused    uint32
	SceneEditable  uint8
	SceneKinds     uint32
	GroupLenTime   float32
	GroupLenInput  float32
	GroupLenGate   float32
	Speed          float32
}

// SetOverlayRow writes the Overlay row into buf (always 1 row; no row param).
func SetOverlayRow(buf []byte, row OverlayRow) {
	buf[0] = row.SceneTori
	buf[1] = row.ScenePoles
	buf[2] = row.NodePoles
	buf[3] = row.SelSpherePoles
	buf[4] = row.Handholds
	buf[5] = row.LabelsGlobal
	buf[6] = row.OverlaysVis
	buf[7] = row.NodeBody
	buf[8] = row.NodeRing
	buf[9] = row.RingPick
	buf[10] = row.SelectionRing
	buf[11] = row.HoverRing
	buf[12] = row.ReachSphere
	buf[13] = row.SceneVectors
	binary.LittleEndian.PutUint32(buf[14:], uint32(row.DragNodeRow))
	binary.LittleEndian.PutUint32(buf[18:], row.EditRefused)
	buf[22] = row.SceneEditable
	binary.LittleEndian.PutUint32(buf[23:], row.SceneKinds)
	binary.LittleEndian.PutUint32(buf[27:], math.Float32bits(row.GroupLenTime))
	binary.LittleEndian.PutUint32(buf[31:], math.Float32bits(row.GroupLenInput))
	binary.LittleEndian.PutUint32(buf[35:], math.Float32bits(row.GroupLenGate))
	binary.LittleEndian.PutUint32(buf[39:], math.Float32bits(row.Speed))
}

// ── Scene block ──────────────────────────────────────────────
const (
	BufSceneColCX     = 0  // f32
	BufSceneColCY     = 4  // f32
	BufSceneColCZ     = 8  // f32
	BufSceneColRadius = 12 // f32
	BufSceneStride    = 16
)

// SetSceneRow writes the Scene row into buf (always 1 row; no row param).
func SetSceneRow(buf []byte, cX float32, cY float32, cZ float32, radius float32) {
	binary.LittleEndian.PutUint32(buf[0:], math.Float32bits(cX))
	binary.LittleEndian.PutUint32(buf[4:], math.Float32bits(cY))
	binary.LittleEndian.PutUint32(buf[8:], math.Float32bits(cZ))
	binary.LittleEndian.PutUint32(buf[12:], math.Float32bits(radius))
}
