// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/bufschema/layout.go  Regenerate: cd tools/topology-vscode && npm run gen:node-defs
// BUF_LAYOUT_FINGERPRINT: version:43|interiorSlotsPerNode:4|block:Node[NodeId:i32:0,CX:f32:4,CY:f32:8,CZ:f32:12,Radius:f32:16,SphereR:f32:20,VRX:f32:24,VRY:f32:28,VRZ:f32:32,FRX:f32:36,FRY:f32:40,FRZ:f32:44,RingAxisPhi:f32:48,RingAxisTheta:f32:52,TopTiltVectorLen:f32:56,TopTiltVectorTheta:f32:60,BottomTiltVectorTheta:f32:64,CoplanarNormalTheta:f32:68,ReceivedVectorLen:f32:72,ReceivedVectorTheta:f32:76,Selected:u8:80,KindId:u8:81,LabelOff:u32:82,LabelLen:u32:86,Hovered:u8:90,LatchedSel:u8:91,LatticePoints:u8:92,RoundsToParallel:i32:93,MsgsToParallel:i32:97]:stride:101|block:Interior[Present:u8:0,Value:i32:1,OX:f32:5,OY:f32:9,OZ:f32:13]:stride:17|block:Edge[SX:f32:0,SY:f32:4,SZ:f32:8,EX:f32:12,EY:f32:16,EZ:f32:20,SrcNodeRow:i32:24,EdgeLabelOff:u32:28,EdgeLabelLen:u32:32]:stride:36|block:EdgeBead[X:f32:0,Y:f32:4,Z:f32:8,Value:i32:12]:stride:16|block:Camera[PX:f32:0,PY:f32:4,PZ:f32:8,R:f32:12,PosPhi:f32:16,PosTheta:f32:20,UpPhi:f32:24,UpTheta:f32:28]:stride:32|block:Overlay[SceneTori:u8:0,ScenePoles:u8:1,Handholds:u8:2,LabelsGlobal:u8:3,OverlaysVis:u8:4,NodeBody:u8:5,NodeRing:u8:6,RingPick:u8:7,SelectionRing:u8:8,HoverRing:u8:9,ReachSphere:u8:10,SceneVectors:u8:11,CommEdges:u8:12,DragNodeRow:i32:13,EditRefused:u32:17,SceneEditable:u8:21,SceneKinds:u32:22,GroupLenTime:f32:26,GroupLenInput:f32:30,GroupLenGate:f32:34,Speed:f32:38]:stride:42|block:Panel[Overlays:u8:0,Node:u8:1,NodeShape:u8:2,NodeState:u8:3,NodeReach:u8:4,Scene:u8:5,SceneGuides:u8:6,ScenePoles:u8:7,SceneVectors:u8:8,SceneLabels:u8:9]:stride:10|block:Scene[CX:f32:0,CY:f32:4,CZ:f32:8,Radius:f32:12]:stride:16|block:Event[Kind:u8:0,NodeRow:i32:1,PortRow:i32:5,TargetRow:i32:9,TargetPortRow:i32:13,EdgeRow:i32:17,Slot:i32:21,Value:i32:25,Bead:u32:29,BeadSteps:f32:33,SimLatencyMs:f32:37,X:f32:41,Y:f32:45,Z:f32:49,F:f32:53,Label:u8:57,Debug:u8:58,TextOff:u32:59,TextLen:u32:63]:stride:67

package Buffer

// BufLayoutVersionGenerated must equal BufLayoutVersion in layout.go.
const BufLayoutVersionGenerated = 43

// BufLayoutFingerprintHash is FNV-1a over BUF_LAYOUT_FINGERPRINT above. It rides in
// every VIEW frame header so the decoder can REFUSE a frame whose layout it was not
// built for, instead of reading the bytes into the wrong columns and drawing garbage.
//
// It is DERIVED, never hand-written: any column added, removed, resized or reordered
// changes the fingerprint and therefore this value. BufLayoutVersion is a human intent
// marker and is NOT what the wire check uses — a forgotten bump must not be able to
// make a skewed layout look compatible.
const BufLayoutFingerprintHash uint32 = 3127422406

// BufInteriorSlotsPerNodeGenerated must equal BufInteriorSlotsPerNode in layout.go.
const BufInteriorSlotsPerNodeGenerated = 4

// BufHeaderSize is the byte width of the retired combined-snapshot frame's header.
// The combined SCENE/BEAD/NODE/EDGE frame is gone entirely — each goroutine now streams
// its own per-owner frame (VIEW/EDGE_STREAM/NODE_STREAM/INTERIOR_STREAM — see
// Buffer/frame_tags.go and memory/feedback_no_single_writer_bridge.md); this constant
// is a historical layout marker, not consumed by any live decoder:
// [tick:u32][layoutLinkCount:u32]
const BufHeaderSize = 8
