#!/usr/bin/env bash
set -euo pipefail

# PLACEMENT: none | repo-wide: no directory holds more hand-edited files at its own top level than the ceiling, without an allowlisted mechanism

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

report="$(python3 - <<'PY'
import os, re, subprocess, collections

CEILING = 20

ALLOWED = {
    "scripts/kindscan":
        "one parse-a-kind pipeline; 7 unexported symbols cross file boundaries",
    "src/Buffer/gen/buflayout":
        "one parse-then-emit pipeline; 29 unexported symbols cross file boundaries",
    "src/Node/nodeactor/owners":
        "splitting re-exports the leaf fields the owners package exists to hide",
    "src/Node":
        "12 guards pinned here by their own PLACEMENT: src/Node/** headers, plus the bead "
        "lifecycle dissolved out of wire/; that half shrinks when the animation owns it",
    "src/Node/BeadAnimation":
        "one Go package by the compiler: 9 unexported symbols cross its files, and Sender "
        "and Receiver reach BeadLine's unexported queue; plus its own TS and 3 guards",
    "src/NodeKinds/PairNode":
        "kindscan joins pkgDir with the literal SPEC.md; tiltring took the exported-call seam",
    ".":
        "go.mod, LICENSE and the main package live at the module root",
    "src/Buffer":
        "ParseBufferLayoutDir globs *.go in exactly this dir; a subdir is not parsed at all",
}

BANNED = ("cohesive", "one concern", "no seam", "already small", "hot path",
          "entry point", "impure", "jsx", "too small", "reads better",
          "no benefit", "not worth")

SCANNED_EXT = (".go", ".ts", ".tsx", ".js", ".md", ".html", ".css", ".sh", ".py")
GEN_MARK = re.compile(r"DO NOT EDIT|Code generated|@generated|GENERATED by", re.I)

def generator_sources():
    """Every generator's Go source. The generators live with the thing each one
    generates, so there is no single directory to walk: a generator is a Go file
    under a gen/ directory, or part of the kind scanner they share."""
    for root, dirs, files in os.walk("."):
        dirs[:] = [d for d in dirs if d not in ("node_modules", "out", ".git", ".probe")]
        rel = os.path.relpath(root, ".")
        if "gen" not in rel.split(os.sep) and not rel.startswith("scripts/kindscan"):
            continue
        for f in files:
            if f.endswith(".go"):
                yield os.path.join(root, f)


def generator_written():
    out = set()
    for path in generator_sources():
        try:
            t = open(path, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        for m in re.finditer(r'"([\w\-/.]+\.(?:go|ts))"', t):
            out.add(os.path.basename(m.group(1)))
    if not out:
        raise SystemExit(
            "check-dir-size: MISCONFIGURED — found no generator sources, so every\n"
            "  generated file would be counted as hand-written. Generators are Go\n"
            "  files under a gen/ directory; if they moved, teach generator_sources()."
        )
    return out

gen = generator_written()
tracked = subprocess.run(["git", "ls-files"], capture_output=True, text=True).stdout.split("\n")

counts = collections.Counter()
for p in tracked:
    if not p or "node_modules" in p or "/out/" in p:
        continue
    if not p.endswith(SCANNED_EXT) or not os.path.isfile(p):
        continue
    base = os.path.basename(p)
    if base in gen or "_gen." in base or "-gen." in base:
        continue
    try:
        head = "".join(open(p, encoding="utf-8", errors="replace").readlines()[:3])
    except OSError:
        continue
    if GEN_MARK.search(head):
        continue
    counts[os.path.dirname(p) or "."] += 1

over = [f"{d}: {n} hand-edited files at top level (ceiling {CEILING})"
        for d, n in sorted(counts.items(), key=lambda kv: -kv[1])
        if n > CEILING and d not in ALLOWED]

bad_reason = [f"{d}: mechanism {r!r} is a description, not a mechanism"
              for d, r in ALLOWED.items()
              if any(b in r.lower() for b in BANNED) or len(r.strip()) < 12]

stale = [d for d in ALLOWED if not os.path.isdir(d)]

out = [f"SCANNED {len(counts)} director(ies), ceiling {CEILING} files, "
       f"{len(ALLOWED)} allowlisted"]
if over:
    out.append("OVER")
    out += over
if bad_reason:
    out.append("BADREASON")
    out += bad_reason
if stale:
    out.append("STALE")
    out += [f"{d}: allowlisted but does not exist" for d in stale]
print("\n".join(out))
PY
)"

summary="$(head -n1 <<< "$report")"
rest="$(tail -n +2 <<< "$report")"
echo "$summary"
[[ -z "$rest" ]] && exit 0

fail=0
while IFS= read -r line; do
  case "$line" in
    OVER)
      echo "DIRECTORY OVER CEILING: a directory holds more hand-edited files at its own top level"
      echo "than the ceiling. Cluster by concern, or add it to ALLOWED in this script with a"
      echo "mechanism. NOTE: file count is a prompt to look, not a verdict — src/Node/nodeactor"
      echo "went 16 -> 23 files while its god object shrank, then 23 -> 12 with no code change but"
      echo "a package boundary. Check the design, not the number:"
      fail=1; continue ;;
    BADREASON)
      echo "ALLOWLIST REASON IS NOT A MECHANISM: name what breaks — an import cycle the compiler"
      echo "reports, a parser reading a hardcoded path, a generator write path, an ordering"
      echo "invariant, a guard forbidding the placement:"
      fail=1; continue ;;
    STALE)
      echo "STALE ALLOWLIST ENTRY: the directory is gone; drop the entry:"
      fail=1; continue ;;
    *) printf '  %s\n' "$line" ;;
  esac
done <<< "$rest"

exit $fail
