#!/usr/bin/env bash
set -euo pipefail

# PLACEMENT: none | repo-wide: no hand-edited file exceeds the code-line ceiling without an allowlisted mechanism

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

report="$(python3 - <<'PY'
import os, re, subprocess

CEILING = 200

ALLOWED = {}

BANNED = ("cohesive", "one concern", "no seam", "already small", "hot path",
          "entry point", "impure", "jsx", "too small", "reads better",
          "no benefit", "not worth")

SCANNED_EXT = (".go", ".ts", ".tsx", ".js", ".md", ".html", ".css", ".sh", ".py")
GEN_MARK = re.compile(r"DO NOT EDIT|Code generated|@generated|GENERATED by", re.I)

def generator_sources():
    """Every generator's Go source. The generators live with the thing each one
    generates, so there is no single directory to walk: a generator is a Go file
    under a gen/ directory, or part of the kind scanner they share."""
    for root, dirs, files in os.walk("."):
        dirs[:] = [d for d in dirs if d not in ("node_modules", "out", ".git", ".probe")]
        rel = os.path.relpath(root, ".")
        parts = rel.split(os.sep)
        if "gen" not in parts and not rel.startswith("src/NodeKinds/gen/kindscan"):
            continue
        for f in files:
            if f.endswith(".go"):
                yield os.path.join(root, f)


def generator_written():
    """Paths the generators write, read out of their own source — never a
    hardcoded list, so moving generated output cannot blind this check."""
    out = set()
    for path in generator_sources():
        try:
            t = open(path, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        for m in re.finditer(r'"([\w\-/.]+\.(?:go|ts))"', t):
            out.add(os.path.basename(m.group(1)))
    if not out:
        raise SystemExit(
            "check-file-size: MISCONFIGURED — found no generator sources, so every\n"
            "  generated file would be measured as hand-written. Generators are Go\n"
            "  files under a gen/ directory; if they moved, teach generator_sources()."
        )
    return out

def code_lines(path):
    n = 0
    for line in open(path, encoding="utf-8", errors="replace"):
        s = line.strip()
        if not s or s.startswith("//") or s.startswith("/*") or s.startswith("*"):
            continue
        n += 1
    return n

gen = generator_written()
tracked = subprocess.run(["git", "ls-files"], capture_output=True, text=True).stdout.split("\n")

over, scanned = [], 0
for p in tracked:
    if not p or "node_modules" in p or "/out/" in p:
        continue
    if not p.endswith(SCANNED_EXT) or not os.path.isfile(p):
        continue
    base = os.path.basename(p)
    if base in gen or "_gen." in base or "-gen." in base:
        continue
    try:
        head = "".join(open(p, encoding="utf-8", errors="replace").readlines()[:3])
    except OSError:
        continue
    if GEN_MARK.search(head):
        continue
    scanned += 1
    n = code_lines(p)
    if n > CEILING and p not in ALLOWED:
        over.append(f"{p}: {n} code lines (ceiling {CEILING})")

bad_reason = [f"{p}: mechanism {r!r} is a description, not a mechanism"
              for p, r in ALLOWED.items()
              if any(b in r.lower() for b in BANNED) or len(r.strip()) < 12]

stale = [p for p in ALLOWED if not os.path.exists(p)]

out = [f"SCANNED {scanned} hand-edited file(s), ceiling {CEILING} code lines, "
       f"{len(ALLOWED)} allowlisted"]
if over:
    out.append("OVER")
    out += over
if bad_reason:
    out.append("BADREASON")
    out += bad_reason
if stale:
    out.append("STALE")
    out += [f"{p}: allowlisted but does not exist" for p in stale]
print("\n".join(out))
PY
)"

summary="$(head -n1 <<< "$report")"
rest="$(tail -n +2 <<< "$report")"
echo "$summary"
[[ -z "$rest" ]] && exit 0

fail=0
while IFS= read -r line; do
  case "$line" in
    OVER)
      echo "FILE OVER CEILING: a hand-edited file exceeds the code-line ceiling. Split it, or add"
      echo "it to ALLOWED in this script with a mechanism a compiler, parser, generator or stated"
      echo "rule enforces:"
      fail=1; continue ;;
    BADREASON)
      echo "ALLOWLIST REASON IS NOT A MECHANISM: name what breaks — an import cycle the compiler"
      echo "reports, a parser reading a hardcoded path, a generator write path, an ordering"
      echo "invariant, a guard forbidding the placement:"
      fail=1; continue ;;
    STALE)
      echo "STALE ALLOWLIST ENTRY: the file is gone; drop the entry so the list stays a map of"
      echo "real exceptions:"
      fail=1; continue ;;
    *) printf '  %s\n' "$line" ;;
  esac
done <<< "$rest"

exit $fail
