package main

//go:generate go run .

import (
	"fmt"
	"github.com/dtauraso/wirefold/scripts/genpaths"
	"github.com/dtauraso/wirefold/scripts/genpaths/params"
	"os"
	"path/filepath"
	"strings"

	Node "github.com/dtauraso/wirefold/Categories/Node"
)

func writePathFiles(pathsDir string) error {
	if err := os.MkdirAll(pathsDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(pathsDir, "block.bin"), []byte(Node.ValueRelTemplate), 0o644); err != nil {
		return err
	}
	entries, err := os.ReadDir(pathsDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || e.Name() == "block.bin" { // path-resolution-ok: the generator's own output directory
			continue
		}
		if err := os.Remove(filepath.Join(pathsDir, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

func writeNames(path string) error {
	var b strings.Builder
	b.WriteString("// GENERATED by Categories/Node/values from NodeValueNames in node_values.go —\n")
	b.WriteString("// do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// One block file per node, written by that node's own goroutine in one update:\n")
	b.WriteString("// its own values, then its tilt arrows, then its channel vectors, in this\n")
	b.WriteString("// order. The row sits in the path, not in the file.\n\n")
	b.WriteString("export const NODE_VALUE_NAMES = [\n")
	for _, name := range Node.NodeBlockValueNames {
		fmt.Fprintf(&b, "  %q,\n", name)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type NodeValueName = (typeof NODE_VALUE_NAMES)[number];\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func main() {
	genpaths.SetName("Categories/Node/values")
	repoRoot, srcRoot := genpaths.Roots()

	dir := filepath.Join(srcRoot, "Node")
	pathsDir := filepath.Join(dir, "paths")
	if err := writePathFiles(pathsDir); err != nil {
		genpaths.Fatalf("write node paths: %v", err)
	}
	genpaths.Announce(pathsDir, 1, "node block path template")

	namesPath := filepath.Join(dir, "node-values-gen.ts")
	if err := writeNames(namesPath); err != nil {
		genpaths.Fatalf("write %s: %v", namesPath, err)
	}
	genpaths.Announce(namesPath, len(Node.NodeBlockValueNames), "node block values")

	shGo := filepath.Join(dir, "shading_params.go")
	shParams, shErr := params.ParseShadingParams(repoRoot, shGo)
	if shErr != nil {
		genpaths.Fatalf("parse shading params: %v", shErr)
	}
	shTs := filepath.Join(dir, "shading-params.ts")
	if err := params.WriteShadingParams(shTs, shParams, genpaths.Name(), "Categories/Node/shading_params.go"); err != nil {
		genpaths.Fatalf("write %s: %v", shTs, err)
	}
	genpaths.Announce(shTs, len(shParams), "constants")

	writeWireTS(srcRoot)
}
