// GENERATED by src/Node/Edge/gen from EdgeValueNames in edge_values.go —
// do not edit.
//
// One block file per edge, written by the source node's goroutine. The row
// sits in the path, not in the file, so no writer touches another edge's bytes.

export const EDGE_VALUE_NAMES = [
  "sx",
  "sy",
  "sz",
  "ex",
  "ey",
  "ez",
  "srcNodeRow",
  "dstNodeRow",
  "deltaR",
  "dragActive",
  "label",
] as const;

export type EdgeValueName = (typeof EDGE_VALUE_NAMES)[number];
