// GENERATED by Categories/Scene/Environment/shading — do not edit.
// Source: Categories/Scene/Environment/shading_params.go ShadingParam* constants.
// Regenerate with: go generate ./...
//
// Go owns the shading PARAMETER values (MODEL.md). TS reads these and applies
// them to GPU materials / bakes the env map from them — no shading values of its
// own. The GPU machinery (three.js materials, PMREM bake, binding) stays in TS.

export const SHADING_PARAM_ENV_SKY_TOP_R = 0.78;
export const SHADING_PARAM_ENV_SKY_TOP_G = 0.77;
export const SHADING_PARAM_ENV_SKY_TOP_B = 0.74;
export const SHADING_PARAM_ENV_SKY_BOTTOM_R = 1.0;
export const SHADING_PARAM_ENV_SKY_BOTTOM_G = 0.88;
export const SHADING_PARAM_ENV_SKY_BOTTOM_B = 0.75;
export const SHADING_PARAM_ENV_SKY_RADIUS = 50.0;
export const SHADING_PARAM_ENV_AMBIENT_COLOR = "#ffffff";
export const SHADING_PARAM_ENV_AMBIENT_INTENSITY = 0.9;
export const SHADING_PARAM_ENV_KEY_COLOR = "#ffeedd";
export const SHADING_PARAM_ENV_KEY_INTENSITY = 0.45;
export const SHADING_PARAM_ENV_RIM_COLOR = "#aabbff";
export const SHADING_PARAM_ENV_RIM_INTENSITY = 0.3;
export const SHADING_PARAM_ENV_PMREM_BLUR = 0.04;
export const SHADING_PARAM_SCENE_AMBIENT_INTENSITY = 0.6;
export const SHADING_PARAM_SCENE_DIR_INTENSITY = 0.8;
