// Code generated by Categories/NodeKinds/gen. DO NOT EDIT.

// Importing this package is what makes every kind exist in the binary: each
// blank import below runs that kind's init(), which is what registers it. A
// kind missing from here compiles, has its SPEC.md and its NODE_DEFS entry,
// and fails at runtime with unknown type.
package NodeKinds

import (
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/NormalSum"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/PairNode"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/PulseLeft"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/PulseRight"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/Time"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/TimeEnd"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/TimeStart"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/holdflip"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/input"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/pacer"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/pulse"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/selectleft"
	_ "github.com/dtauraso/wirefold/Categories/NodeKinds/selectright"
)
