// GENERATED by Categories/NodeKinds/gen — do not edit. Source: Categories/NodeKinds/<Kind>/node.go + SPEC.md

export interface NodeDef {
  bg: string;
  border: string;
  text: string;
  minWidth?: number;
  // NodeTypeDef-compatible fields for schema/adapter consumers.
  shape?: string;
  fill?: string;
  stroke?: string;
  width?: number;
  height?: number;
  // One line saying what this kind IS, from its SPEC.md "## Description" section.
  // The node palette shows it under the kind's name; absent when the SPEC has no such
  // section, which renders as no description rather than as a placeholder.
  desc?: string;
  inputs?: { name: string; kind: string; isMulti?: boolean }[];
  outputs?: { name: string; kind: string; isMulti?: boolean }[];
}

// PascalCase Go kind names that have a Go runtime.
// Single source of truth — derived from bead.Register calls.
export const RUNTIME_IMPLEMENTED_KINDS: ReadonlySet<string> = new Set([
  "Input",
  "PairNode",
  "Pulse",
  "PulseLeft",
  "PulseRight",
  "SelectLeft",
  "SelectRight",
  "Time",
  "TimeEnd",
  "TimeStart",
]);

export const NODE_DEFS: Record<string, NodeDef> = {
  Input: { bg: "#e0e0e0", border: "#666", text: "#1a1a1a", minWidth: 90, shape: "rect", fill: "#e0e0e0", stroke: "#666", width: 80, height: 60, desc: "The source: emits its own authored list of values, last one first, optionally repeating.", inputs: [{ name: "FeedbackIn", kind: "chain" }], outputs: [{ name: "OutCadence", kind: "chain" }, { name: "ToExcitatory", kind: "chain" }] },
  PairNode: { bg: "#fff8e1", border: "#f9a825", text: "#4e342e", minWidth: 70, shape: "rect", fill: "#fff8e1", stroke: "#f9a825", width: 70, height: 60, desc: "One half of a pair: turns its own tilt vector toward rest by exchanging directions with its partner, one step per arrival.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }] },
  Pulse: { bg: "#e1f5fe", border: "#2196f3", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#2196f3", width: 90, height: 60, desc: "Holds the last value it received and drives it out continuously, from the moment it starts.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }, { name: "OutFanout", kind: "chain" }] },
  PulseLeft: { bg: "#e1f5fe", border: "#90caf9", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#90caf9", width: 90, height: 60, desc: "Holds and drives a value like Pulse, feeding the LEFT input of a select gate.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }] },
  PulseRight: { bg: "#e1f5fe", border: "#01579b", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#01579b", width: 90, height: 60, desc: "Holds and drives a value like Pulse, feeding the RIGHT input of a select gate.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }] },
  SelectLeft: { bg: "#fce4ec", border: "#880e4f", text: "#880e4f", minWidth: 110, shape: "rect", fill: "#fce4ec", stroke: "#880e4f", width: 80, height: 60, desc: "Passes a value on only when both inputs arrive within one window, favouring the LEFT one.", inputs: [{ name: "FromLeft", kind: "chain" }, { name: "FromRight", kind: "chain" }], outputs: [{ name: "ToPassed", kind: "chain" }] },
  SelectRight: { bg: "#fce4ec", border: "#f06292", text: "#880e4f", minWidth: 110, shape: "rect", fill: "#fce4ec", stroke: "#f06292", width: 80, height: 60, desc: "Passes a value on only when both inputs arrive within one window, favouring the RIGHT one.", inputs: [{ name: "FromLeft", kind: "chain" }, { name: "FromRight", kind: "chain" }], outputs: [{ name: "ToPassed", kind: "chain" }] },
  Time: { bg: "#fff3e0", border: "#e65100", text: "#bf360c", minWidth: 90, shape: "rect", fill: "#fff3e0", stroke: "#e65100", width: 90, height: 60, desc: "Holds what arrives and sends on what it was holding, so a value comes out one arrival late.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "ToNext", kind: "chain", isMulti: true }] },
  TimeEnd: { bg: "#fff3e0", border: "#7f0000", text: "#bf360c", minWidth: 60, shape: "rect", fill: "#fff3e0", stroke: "#7f0000", width: 60, height: 60, desc: "The end of a time chain: holds what arrives and sends nothing on.", inputs: [{ name: "In", kind: "chain" }] },
  TimeStart: { bg: "#fff3e0", border: "#ffc400", text: "#bf360c", minWidth: 90, shape: "rect", fill: "#fff3e0", stroke: "#ffc400", width: 90, height: 60, desc: "The head of a time chain: holds what arrives and fans the value it was holding to every downstream node at once.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "ToNext", kind: "chain", isMulti: true }] },
};

/** The KindId a node carries when its kind is not in the registry — the one
 * index NODE_DEFS_ARRAY below must never be asked for. Matches KindIDUnknown
 * in Categories/Node/node_kind_id_gen.go. */
export const UNKNOWN_KIND_ID = 0xff;

export const NODE_DEFS_ARRAY: readonly (NodeDef | undefined)[] = [
  { bg: "#fff3e0", border: "#7f0000", text: "#bf360c", minWidth: 60, shape: "rect", fill: "#fff3e0", stroke: "#7f0000", width: 60, height: 60, desc: "The end of a time chain: holds what arrives and sends nothing on.", inputs: [{ name: "In", kind: "chain" }] },
  undefined, // gap left by a removed kind (KindId 1)
  { bg: "#fff3e0", border: "#e65100", text: "#bf360c", minWidth: 90, shape: "rect", fill: "#fff3e0", stroke: "#e65100", width: 90, height: 60, desc: "Holds what arrives and sends on what it was holding, so a value comes out one arrival late.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "ToNext", kind: "chain", isMulti: true }] },
  { bg: "#e0e0e0", border: "#666", text: "#1a1a1a", minWidth: 90, shape: "rect", fill: "#e0e0e0", stroke: "#666", width: 80, height: 60, desc: "The source: emits its own authored list of values, last one first, optionally repeating.", inputs: [{ name: "FeedbackIn", kind: "chain" }], outputs: [{ name: "OutCadence", kind: "chain" }, { name: "ToExcitatory", kind: "chain" }] },
  undefined, // gap left by a removed kind (KindId 4)
  { bg: "#e1f5fe", border: "#2196f3", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#2196f3", width: 90, height: 60, desc: "Holds the last value it received and drives it out continuously, from the moment it starts.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }, { name: "OutFanout", kind: "chain" }] },
  { bg: "#fce4ec", border: "#f06292", text: "#880e4f", minWidth: 110, shape: "rect", fill: "#fce4ec", stroke: "#f06292", width: 80, height: 60, desc: "Passes a value on only when both inputs arrive within one window, favouring the RIGHT one.", inputs: [{ name: "FromLeft", kind: "chain" }, { name: "FromRight", kind: "chain" }], outputs: [{ name: "ToPassed", kind: "chain" }] },
  { bg: "#fce4ec", border: "#880e4f", text: "#880e4f", minWidth: 110, shape: "rect", fill: "#fce4ec", stroke: "#880e4f", width: 80, height: 60, desc: "Passes a value on only when both inputs arrive within one window, favouring the LEFT one.", inputs: [{ name: "FromLeft", kind: "chain" }, { name: "FromRight", kind: "chain" }], outputs: [{ name: "ToPassed", kind: "chain" }] },
  { bg: "#e1f5fe", border: "#90caf9", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#90caf9", width: 90, height: 60, desc: "Holds and drives a value like Pulse, feeding the LEFT input of a select gate.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }] },
  { bg: "#e1f5fe", border: "#01579b", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#01579b", width: 90, height: 60, desc: "Holds and drives a value like Pulse, feeding the RIGHT input of a select gate.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }] },
  { bg: "#fff3e0", border: "#ffc400", text: "#bf360c", minWidth: 90, shape: "rect", fill: "#fff3e0", stroke: "#ffc400", width: 90, height: 60, desc: "The head of a time chain: holds what arrives and fans the value it was holding to every downstream node at once.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "ToNext", kind: "chain", isMulti: true }] },
  { bg: "#fff8e1", border: "#f9a825", text: "#4e342e", minWidth: 70, shape: "rect", fill: "#fff8e1", stroke: "#f9a825", width: 70, height: 60, desc: "One half of a pair: turns its own tilt vector toward rest by exchanging directions with its partner, one step per arrival.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }] },
];

export const NODE_KIND_NAMES: readonly (string | undefined)[] = [
  "TimeEnd",
  undefined, // gap left by a removed kind (KindId 1)
  "Time",
  "Input",
  undefined, // gap left by a removed kind (KindId 4)
  "Pulse",
  "SelectRight",
  "SelectLeft",
  "PulseLeft",
  "PulseRight",
  "TimeStart",
  "PairNode",
];
