// GENERATED by Categories/Chrome/Pills/FitButton/gen from ChipValueNames in
// chip_values.go — do not edit.
//
// The fit chip's values, each one file under the scene root. The renderer learns
// where from Categories/Chrome/Pills/FitButton/paths/, which Go writes from this same
// list, so neither side spells a path.

export const FIT_CHIP_VALUE_NAMES = [
  "x",
  "y",
  "w",
  "h",
  "labelText",
] as const;

export type FitChipValueName = (typeof FIT_CHIP_VALUE_NAMES)[number];
