package main

//go:generate go run .

import (
	"path/filepath"
	"strings"

	"github.com/dtauraso/beadnetwork/scripts/genpaths"
)

func main() {
	genName = "Start/extension/messages"
	repoRoot, _ := roots()

	for dir, up := range map[string]string{
		filepath.Join("Start", "extension"):            "../../Categories/",
		filepath.Join("Start", "extension", "webview"): "../../../Categories/",
	} {
		outPath := filepath.Join(repoRoot, dir, "messages.ts")
		body := "// GENERATED by Start/extension/messages — do not edit.\n" +
			"// Regenerate with: go generate ./...\n\n" +
			strings.ReplaceAll(tsMessagesSource, `from "../`, `from "`+up)
		if err := genpaths.WriteIfChanged(outPath, []byte(body), 0o644); err != nil {
			fatalf("write %s: %v", outPath, err)
		}
		announce(outPath, 1, "webview→host message union")
	}
}
