// GENERATED by Categories/Input/gen — do not edit.
// Source: Categories/Input/gen/record_reader_template.go, copied verbatim.
// Regenerate with: go generate ./...

package Node

import (
	"encoding/binary"
	"errors"
	"math"
)

var ErrShort = errors.New("input record truncated")

type Reader struct {
	b   []byte
	pos int
}

func NewReader(b []byte, pos int) *Reader {
	return &Reader{b: b, pos: pos}
}

func (r *Reader) U8() (byte, error) {
	if r.pos+1 > len(r.b) {
		return 0, ErrShort
	}
	v := r.b[r.pos]
	r.pos++
	return v, nil
}

func (r *Reader) I32() (int32, error) {
	if r.pos+4 > len(r.b) {
		return 0, ErrShort
	}
	v := int32(binary.LittleEndian.Uint32(r.b[r.pos:]))
	r.pos += 4
	return v, nil
}

func (r *Reader) Str() (string, error) {
	if r.pos+4 > len(r.b) {
		return "", ErrShort
	}
	n := int(binary.LittleEndian.Uint32(r.b[r.pos:]))
	r.pos += 4
	if n < 0 || r.pos+n > len(r.b) {
		return "", ErrShort
	}
	s := string(r.b[r.pos : r.pos+n])
	r.pos += n
	return s, nil
}

func (r *Reader) F32() (float32, error) {
	if r.pos+4 > len(r.b) {
		return 0, ErrShort
	}
	v := math.Float32frombits(binary.LittleEndian.Uint32(r.b[r.pos:]))
	r.pos += 4
	return v, nil
}

func (r *Reader) F64() (float64, error) {
	if r.pos+8 > len(r.b) {
		return 0, ErrShort
	}
	v := math.Float64frombits(binary.LittleEndian.Uint64(r.b[r.pos:]))
	r.pos += 8
	return v, nil
}

func (r *Reader) BoolByte() (bool, error) {
	v, err := r.U8()
	return v != 0, err
}

func EnumAt(list []string, i byte) string {
	if int(i) < len(list) {
		return list[i]
	}
	return ""
}
