// GENERATED by Categories/Node/gen — do not edit.
// Source: Categories/Node/shading_params.go ShadingParam* constants.
// Regenerate with: go generate ./...
//
// Go owns the shading PARAMETER values (MODEL.md). TS reads these and applies
// them to GPU materials / bakes the env map from them — no shading values of its
// own. The GPU machinery (three.js materials, PMREM bake, binding) stays in TS.

export const SHADING_PARAM_NODE_RING_TUBE_RATIO = 0.08;
