// GENERATED by Categories/Node/updateattrs — do not edit.
// Source: Node.UpdateAttrs. The message kind and the entity kinds an edit can
// address are Drag's, and are imported from Scene/Drag/input-defs.ts.
// Regenerate with: go generate ./...

export const IN_UPDATE_ATTRS = ["dragPhi", "dragMaxTheta", "dragActive", "kindActive", "selfDragPhi", "selfDragMaxTheta", "selfDragActive", "dragR", "selfDragR"] as const;
