package main

//go:generate go run .

import (
	"fmt"
	"github.com/dtauraso/wirefold/scripts/genpaths"
	"os"
	"path/filepath"
	"strings"

	"github.com/dtauraso/wirefold/Categories/Node/TiltVectors"
)

func writeNames(path string) error {
	var b strings.Builder
	b.WriteString("// GENERATED by Categories/Node/TiltVectors/values from TiltValueNames in\n")
	b.WriteString("// tilt_values.go — do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// One block file per node, holding the tilt arrows it shows. The row sits in\n")
	b.WriteString("// the path, not in the file.\n\n")
	b.WriteString("export const TILT_VALUE_NAMES = [\n")
	for _, name := range TiltVectors.TiltValueNames {
		fmt.Fprintf(&b, "  %q,\n", name)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type TiltValueName = (typeof TILT_VALUE_NAMES)[number];\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func main() {
	genpaths.SetName("Categories/Node/TiltVectors/values")
	_, srcRoot := genpaths.Roots()

	dir := filepath.Join(srcRoot, "Node", "TiltVectors")
	namesPath := filepath.Join(dir, "tilt-values-gen.ts")
	if err := writeNames(namesPath); err != nil {
		genpaths.Fatalf("write %s: %v", namesPath, err)
	}
	genpaths.Announce(namesPath, len(TiltVectors.TiltValueNames), "tilt arrow values")
}
