// GENERATED by src/RingPoint/gen from PointValueNames in point_values.go —
// do not edit.
//
// The canonical ring surfaces, computed once from constants and never changed.
// They are the one thing here that is static, so they cost a slot in
// every frame to say the same thing.

export const RING_POINT_VALUE_NAMES = [
  "nodeX",
  "nodeY",
  "nodeZ",
  "beadX",
  "beadY",
  "beadZ",
] as const;

export type RingPointValueName = (typeof RING_POINT_VALUE_NAMES)[number];
