// GENERATED by Categories/Scene/values from CountsValueNames in
// owner_counts_values.go — do not edit.
//
// How many nodes and edges the scene has, which is what every renderer loop
// over owners counts up to.

export const OWNER_COUNTS_VALUE_NAMES = [
  "nodes",
  "edges",
] as const;

export type OwnerCountsValueName = (typeof OWNER_COUNTS_VALUE_NAMES)[number];
