// GENERATED by Categories/Node/Edge/updateattrs — do not edit.
// Source: Edge.UpdateAttrs. The message kind and the entity kinds an edit can
// address are Drag's, and are imported from Scene/Drag/input-defs.ts.
// Regenerate with: go generate ./...

export const IN_UPDATE_ATTRS = ["dragActive"] as const;
