// GENERATED by Categories/Node/Edge/values — do not edit.
// Source: edge.UpdateAttrs and Stdin's record_kinds.go.
// Regenerate with: go generate ./...

export const IN_KIND_EDIT_UPDATE = 22;

export const IN_UPDATE_ATTRS = ["dragActive"] as const;

// EDIT_UPDATE_KINDS_START
export const IN_UPDATE_KINDS = ["overlays", "clock", "scene", "tiltVector", "panels", "node", "edge"] as const;
// EDIT_UPDATE_KINDS_END

