// GENERATED by Categories/Input/gen — do not edit.
// Source: the Go declarations this file's lists are copied from —
// each concern's UpdateAttrs, Drag's kinds.go, Stdin's record_kinds.go.
// Regenerate with: go generate ./...

export const IN_KIND_EDIT_UPDATE = 22;

export const IN_UPDATE_ATTRS = ["dragActive"] as const;

// EDIT_UPDATE_KINDS_START
export const IN_UPDATE_KINDS = ["overlays", "clock", "scene", "tiltVector", "panels", "node", "edge"] as const;
// EDIT_UPDATE_KINDS_END

export class ByteWriter {
  private buf = new Uint8Array(64);
  private view = new DataView(this.buf.buffer);
  private pos = 0;

  private ensure(n: number): void {
    if (this.pos + n <= this.buf.length) return;
    let cap = this.buf.length * 2;
    while (cap < this.pos + n) cap *= 2;
    const next = new Uint8Array(cap);
    next.set(this.buf);
    this.buf = next;
    this.view = new DataView(this.buf.buffer);
  }

  u8(v: number): void {
    this.ensure(1);
    this.view.setUint8(this.pos, v);
    this.pos += 1;
  }
  u16(v: number): void {
    this.ensure(2);
    this.view.setUint16(this.pos, v, true);
    this.pos += 2;
  }
  i32(v: number): void {
    this.ensure(4);
    this.view.setInt32(this.pos, v, true);
    this.pos += 4;
  }
  u32(v: number): void {
    this.ensure(4);
    this.view.setUint32(this.pos, v, true);
    this.pos += 4;
  }
  f32(v: number): void {
    this.ensure(4);
    this.view.setFloat32(this.pos, v, true);
    this.pos += 4;
  }
  f64(v: number): void {
    this.ensure(8);
    this.view.setFloat64(this.pos, v, true);
    this.pos += 8;
  }
  bool(v: boolean): void {
    this.u8(v ? 1 : 0);
  }
  str(s: string): void {
    const bytes = new TextEncoder().encode(s);
    this.u32(bytes.length);
    this.ensure(bytes.length);
    this.buf.set(bytes, this.pos);
    this.pos += bytes.length;
  }

  toArrayBuffer(): ArrayBuffer {
    return this.buf.buffer.slice(0, this.pos);
  }
}

export function enumIndex(list: readonly string[], s: string): number {
  const i = list.indexOf(s);
  if (i < 0) {
    throw new Error(
      `enumIndex: "${s}" is not in the wire enum [${list.join(",")}] — every caller passes a name ` +
        `that must be there, and the list this file was generated with does not carry it, so the ` +
        `input layout in Categories/Input/gen was not extended when the flag was added. Returning 0 here ` +
        `silently encoded the FIRST enum member instead, sending a correct-looking edit addressed ` +
        `to the wrong one.`,
    );
  }
  return i;
}

export function attrIndex(attr: string): number {
  const i = (IN_UPDATE_ATTRS as readonly string[]).indexOf(attr);
  if (i < 0) {
    throw new Error(
      `attrIndex: no wire byte exists for update attribute "${attr}" — the attr list this file was ` +
        `generated with does not carry it, so an edit naming it could never be encoded. Declare it ` +
        `in Categories/Input/gen's input layout and regenerate, in the same commit as the decoder that ` +
        `reads it.`,
    );
  }
  return i;
}

export function editUpdate(entity: string, attr: string): ByteWriter {
  const w = new ByteWriter();
  w.u8(IN_KIND_EDIT_UPDATE);
  w.u8(enumIndex(IN_UPDATE_KINDS, entity));
  w.u8(attrIndex(attr));
  return w;
}
