// GENERATED by tools/gen-node-defs — do not edit.
// Source: nodes/Wiring/input_codec.go's InputLayoutFingerprint const.
// Regenerate with: npm run gen:node-defs
//
// Go is the single source of the TS<->Go input-record layout: Go's InputLayoutFingerprint
// string is parsed here (the same tokenization Go's own parseFPList uses) to emit the
// fingerprint string and its directly-derived constants/arrays for TS. There is no
// separate TS-side fingerprint to hand-keep in lockstep, so the two languages cannot
// drift apart on record kinds or enum orderings.

// INPUT_LAYOUT_FINGERPRINT: kinds=save:4,raw-input:10,edit-update:22 eventKinds=pointerdown,pointermove,pointerup,wheel,home hitKinds=port,handhold,node,edge,torus,empty updateKinds=overlays,clock,distanceGroup updateAttrs=toggle,speed,length overlayFlags=tori,scenePoles,nodePoles,selSpherePoles,handholds,labelsGlobal,overlays,cascadeLinks,polarVectors,beadTweens
export const INPUT_LAYOUT_FINGERPRINT =
  "kinds=save:4,raw-input:10,edit-update:22 eventKinds=pointerdown,pointermove,pointerup,wheel,home hitKinds=port,handhold,node,edge,torus,empty updateKinds=overlays,clock,distanceGroup updateAttrs=toggle,speed,length overlayFlags=tori,scenePoles,nodePoles,selSpherePoles,handholds,labelsGlobal,overlays,cascadeLinks,polarVectors,beadTweens";

// Record kind bytes (first byte of every record). Must match input_codec.go.
export const IN_KIND_SAVE = 4;
export const IN_KIND_RAW_INPUT = 10;
export const IN_KIND_EDIT_UPDATE = 22;

// Enum orderings (u8 index -> string), shared with input_codec.go.
export const IN_EVENT_KINDS = ["pointerdown", "pointermove", "pointerup", "wheel", "home"] as const;
export const IN_HIT_KINDS = ["port", "handhold", "node", "edge", "torus", "empty"] as const;
// EDIT_UPDATE_KINDS_START
export const IN_UPDATE_KINDS = ["overlays", "clock", "distanceGroup"] as const;
// EDIT_UPDATE_KINDS_END
export const IN_UPDATE_ATTRS = ["toggle", "speed", "length"] as const;
