// GENERATED by tools/gen-node-defs — do not edit. Source: nodes/<Kind>/<Kind>.go + SPEC.md

export interface NodeDef {
  bg: string;
  border: string;
  text: string;
  minWidth?: number;
  // NodeTypeDef-compatible fields for schema/adapter consumers.
  shape?: string;
  fill?: string;
  stroke?: string;
  width?: number;
  height?: number;
  inputs?: { name: string; kind: string; isMulti?: boolean }[];
  outputs?: { name: string; kind: string; isMulti?: boolean }[];
}

// PascalCase Go kind names that have a Go runtime.
// Single source of truth — derived from wire.Register calls.
export const RUNTIME_IMPLEMENTED_KINDS: ReadonlySet<string> = new Set([
  "HoldFlip",
  "Input",
  "Pacer",
  "Pulse",
  "PulseLeft",
  "PulseRight",
  "Time",
  "TimeEnd",
  "TimeStart",
  "WindowAndInhibitLeftGate",
  "WindowAndInhibitRightGate",
]);

export const NODE_DEFS: Record<string, NodeDef> = {
  HoldFlip: { bg: "#eceff1", border: "#263238", text: "#263238", minWidth: 36, shape: "rect", fill: "#eceff1", stroke: "#263238", width: 36, height: 36, inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }] },
  Input: { bg: "#e0e0e0", border: "#666", text: "#1a1a1a", minWidth: 90, shape: "rect", fill: "#e0e0e0", stroke: "#666", width: 80, height: 60, inputs: [{ name: "FeedbackIn", kind: "chain" }], outputs: [{ name: "ToTime", kind: "chain" }, { name: "ToExcitatory", kind: "chain" }, { name: "ToPacer", kind: "chain" }] },
  Pacer: { bg: "#e8f5e9", border: "#2e7d32", text: "#1b5e20", minWidth: 60, shape: "rect", fill: "#e8f5e9", stroke: "#2e7d32", width: 60, height: 60, inputs: [{ name: "FromInput", kind: "chain" }], outputs: [{ name: "FeedbackOut", kind: "chain" }] },
  Pulse: { bg: "#e1f5fe", border: "#01579b", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#01579b", width: 90, height: 60, inputs: [{ name: "FromInput", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }, { name: "Out2", kind: "chain" }] },
  PulseLeft: { bg: "#e1f5fe", border: "#01579b", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#01579b", width: 90, height: 60, inputs: [{ name: "FromInput", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }, { name: "Out2", kind: "chain" }] },
  PulseRight: { bg: "#e1f5fe", border: "#01579b", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#01579b", width: 90, height: 60, inputs: [{ name: "FromInput", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }, { name: "Out2", kind: "chain" }] },
  Time: { bg: "#fff3e0", border: "#e65100", text: "#bf360c", minWidth: 90, shape: "rect", fill: "#fff3e0", stroke: "#e65100", width: 90, height: 60, inputs: [{ name: "FromPrevTimeNode", kind: "chain" }], outputs: [{ name: "ToNext", kind: "chain", isMulti: true }] },
  TimeEnd: { bg: "#f3e5f5", border: "#6a1b9a", text: "#4a148c", minWidth: 60, shape: "rect", fill: "#f3e5f5", stroke: "#6a1b9a", width: 60, height: 60, inputs: [{ name: "In", kind: "chain" }] },
  TimeStart: { bg: "#fff3e0", border: "#e65100", text: "#bf360c", minWidth: 90, shape: "rect", fill: "#fff3e0", stroke: "#e65100", width: 90, height: 60, inputs: [{ name: "FromPrevTimeNode", kind: "chain" }], outputs: [{ name: "ToNext", kind: "chain", isMulti: true }] },
  WindowAndInhibitLeftGate: { bg: "#fce4ec", border: "#880e4f", text: "#880e4f", minWidth: 110, shape: "rect", fill: "#fce4ec", stroke: "#880e4f", width: 80, height: 60, inputs: [{ name: "FromLeft", kind: "chain" }, { name: "FromRight", kind: "chain" }], outputs: [{ name: "ToPassed", kind: "chain" }] },
  WindowAndInhibitRightGate: { bg: "#fce4ec", border: "#880e4f", text: "#880e4f", minWidth: 110, shape: "rect", fill: "#fce4ec", stroke: "#880e4f", width: 80, height: 60, inputs: [{ name: "FromLeft", kind: "chain" }, { name: "FromRight", kind: "chain" }], outputs: [{ name: "ToPassed", kind: "chain" }] },
};

export const NODE_DEFS_ARRAY: readonly NodeDef[] = [
  { bg: "#f3e5f5", border: "#6a1b9a", text: "#4a148c", minWidth: 60, shape: "rect", fill: "#f3e5f5", stroke: "#6a1b9a", width: 60, height: 60, inputs: [{ name: "In", kind: "chain" }] },
  { bg: "#eceff1", border: "#263238", text: "#263238", minWidth: 36, shape: "rect", fill: "#eceff1", stroke: "#263238", width: 36, height: 36, inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }] },
  { bg: "#fff3e0", border: "#e65100", text: "#bf360c", minWidth: 90, shape: "rect", fill: "#fff3e0", stroke: "#e65100", width: 90, height: 60, inputs: [{ name: "FromPrevTimeNode", kind: "chain" }], outputs: [{ name: "ToNext", kind: "chain", isMulti: true }] },
  { bg: "#e0e0e0", border: "#666", text: "#1a1a1a", minWidth: 90, shape: "rect", fill: "#e0e0e0", stroke: "#666", width: 80, height: 60, inputs: [{ name: "FeedbackIn", kind: "chain" }], outputs: [{ name: "ToTime", kind: "chain" }, { name: "ToExcitatory", kind: "chain" }, { name: "ToPacer", kind: "chain" }] },
  { bg: "#e8f5e9", border: "#2e7d32", text: "#1b5e20", minWidth: 60, shape: "rect", fill: "#e8f5e9", stroke: "#2e7d32", width: 60, height: 60, inputs: [{ name: "FromInput", kind: "chain" }], outputs: [{ name: "FeedbackOut", kind: "chain" }] },
  { bg: "#e1f5fe", border: "#01579b", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#01579b", width: 90, height: 60, inputs: [{ name: "FromInput", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }, { name: "Out2", kind: "chain" }] },
  { bg: "#fce4ec", border: "#880e4f", text: "#880e4f", minWidth: 110, shape: "rect", fill: "#fce4ec", stroke: "#880e4f", width: 80, height: 60, inputs: [{ name: "FromLeft", kind: "chain" }, { name: "FromRight", kind: "chain" }], outputs: [{ name: "ToPassed", kind: "chain" }] },
  { bg: "#fce4ec", border: "#880e4f", text: "#880e4f", minWidth: 110, shape: "rect", fill: "#fce4ec", stroke: "#880e4f", width: 80, height: 60, inputs: [{ name: "FromLeft", kind: "chain" }, { name: "FromRight", kind: "chain" }], outputs: [{ name: "ToPassed", kind: "chain" }] },
  { bg: "#e1f5fe", border: "#01579b", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#01579b", width: 90, height: 60, inputs: [{ name: "FromInput", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }, { name: "Out2", kind: "chain" }] },
  { bg: "#e1f5fe", border: "#01579b", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#01579b", width: 90, height: 60, inputs: [{ name: "FromInput", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }, { name: "Out2", kind: "chain" }] },
  { bg: "#fff3e0", border: "#e65100", text: "#bf360c", minWidth: 90, shape: "rect", fill: "#fff3e0", stroke: "#e65100", width: 90, height: 60, inputs: [{ name: "FromPrevTimeNode", kind: "chain" }], outputs: [{ name: "ToNext", kind: "chain", isMulti: true }] },
];

export const NODE_KIND_NAMES: readonly string[] = [
  "TimeEnd",
  "HoldFlip",
  "Time",
  "Input",
  "Pacer",
  "Pulse",
  "WindowAndInhibitLeftGate",
  "WindowAndInhibitRightGate",
  "PulseLeft",
  "PulseRight",
  "TimeStart",
];
