// GENERATED by tools/gen-node-defs — do not edit.
// Source: OVERLAY_FLAG_NAMES in tools/topology-vscode/src/messages.ts.
// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs

package OverlaysDropdown

import (
	T "github.com/dtauraso/wirefold/tools/topology-vscode/Trace"
)

// DefaultOverlayState is the startup overlay snapshot used by Wiring's newMoveDispatch.
func DefaultOverlayState() OverlayState {
	return OverlayState{
		SceneToriVisible:      true,
		ScenePolesVisible:     true,
		NodePolesVisible:      true,
		HandholdsVisible:      true,
		LabelsGlobalVisible:   true,
		OverlaysVisible:       true,
		NodeBodyVisible:       true,
		NodeRingVisible:       true,
		RingPickVisible:       true,
		SelectionRingVisible:  true,
		HoverRingVisible:      true,
		SceneVectorsVisible:   true,
		RuleChannelsVisible:   true,
		NodePoleSphereVisible: true,
	}
}

// OverlayToggles maps an overlay FLAG name (the attr="toggle" wire name) to the
// OverlayState method that flips it.
//
// OVERLAY_TOGGLES_START
var OverlayToggles = map[string]func(*OverlayState, *T.Trace){
	"tori":           (*OverlayState).ToggleSceneTori,
	"scenePoles":     (*OverlayState).ToggleScenePoles,
	"nodePoles":      (*OverlayState).ToggleNodePoles,
	"handholds":      (*OverlayState).ToggleHandholds,
	"labelsGlobal":   (*OverlayState).ToggleLabelsGlobal,
	"overlays":       (*OverlayState).ToggleOverlaysVis,
	"nodeBody":       (*OverlayState).ToggleNodeBody,
	"nodeRing":       (*OverlayState).ToggleNodeRing,
	"ringPick":       (*OverlayState).ToggleRingPick,
	"selectionRing":  (*OverlayState).ToggleSelectionRing,
	"hoverRing":      (*OverlayState).ToggleHoverRing,
	"sceneVectors":   (*OverlayState).ToggleSceneVectors,
	"ruleChannels":   (*OverlayState).ToggleRuleChannels,
	"nodePoleSphere": (*OverlayState).ToggleNodePoleSphere,
	"allPoleSpheres": (*OverlayState).ToggleAllPoleSpheres,
}

// OVERLAY_TOGGLES_END

// OverlayFlagBreadcrumbScope names the overlay flags whose Toggle also logs a
// structured "pole-toggle-go" debug breadcrumb, and the scope text that breadcrumb
// carries. Flags absent here emit no such breadcrumb.
//
// OVERLAY_BREADCRUMB_SCOPES_START
var OverlayFlagBreadcrumbScope = map[string]string{
	"scenePoles": "scene",
	"nodePoles":  "nodes",
}

// OVERLAY_BREADCRUMB_SCOPES_END

// OverlayFlagValue reads the post-toggle bool for the flags named in
// OverlayFlagBreadcrumbScope (same key set).
var OverlayFlagValue = map[string]func(*OverlayState) bool{
	"scenePoles": func(o *OverlayState) bool { return o.ScenePolesVisible },
	"nodePoles":  func(o *OverlayState) bool { return o.NodePolesVisible },
}
