// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/bufschema/layout.go  Regenerate: npm run gen:node-defs

// This half holds the Edge, EdgeBead, TiltArrow, ChannelVector, Event block(s). Row blocks are split across two files
// purely to stay under check-file-size.sh's limit — the division is by position in
// Buffer/bufschema/layout.go, not by meaning, so neither file is a category.

// ── Edge block ───────────────────────────────────────────────
export const EDGE_COL_SX                         = 0; // f32
export const EDGE_COL_SY                         = 4; // f32
export const EDGE_COL_SZ                         = 8; // f32
export const EDGE_COL_EX                         = 12; // f32
export const EDGE_COL_EY                         = 16; // f32
export const EDGE_COL_EZ                         = 20; // f32
export const EDGE_COL_SRC_NODE_ROW               = 24; // i32
export const EDGE_COL_DST_NODE_ROW               = 28; // i32
export const EDGE_COL_DELTA_R                    = 32; // f32
export const EDGE_COL_DRAG_ACTIVE                = 36; // u8
export const EDGE_COL_EDGE_LABEL_OFF             = 37; // u32
export const EDGE_COL_EDGE_LABEL_LEN             = 41; // u32
export const EDGE_STRIDE                         = 45;

export function readEdgeSX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SX, true); }
export function readEdgeSY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SY, true); }
export function readEdgeSZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SZ, true); }
export function readEdgeEX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EX, true); }
export function readEdgeEY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EY, true); }
export function readEdgeEZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EZ, true); }
export function readEdgeSrcNodeRow(view: DataView, row: number): number { return view.getInt32(row * EDGE_STRIDE + EDGE_COL_SRC_NODE_ROW, true); }
export function readEdgeDstNodeRow(view: DataView, row: number): number { return view.getInt32(row * EDGE_STRIDE + EDGE_COL_DST_NODE_ROW, true); }
export function readEdgeDeltaR(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_DELTA_R, true); }
export function readEdgeDragActive(view: DataView, row: number): number { return view.getUint8(row * EDGE_STRIDE + EDGE_COL_DRAG_ACTIVE); }
export function readEdgeEdgeLabelOff(view: DataView, row: number): number { return view.getUint32(row * EDGE_STRIDE + EDGE_COL_EDGE_LABEL_OFF, true); }
export function readEdgeEdgeLabelLen(view: DataView, row: number): number { return view.getUint32(row * EDGE_STRIDE + EDGE_COL_EDGE_LABEL_LEN, true); }

// ── EdgeBead block ───────────────────────────────────────────
export const EDGE_BEAD_COL_X                     = 0; // f32
export const EDGE_BEAD_COL_Y                     = 4; // f32
export const EDGE_BEAD_COL_Z                     = 8; // f32
export const EDGE_BEAD_COL_VALUE                 = 12; // i32
export const EDGE_BEAD_COL_EDGE_ROW              = 16; // i32
export const EDGE_BEAD_COL_RING_M0               = 20; // f32
export const EDGE_BEAD_COL_RING_M1               = 24; // f32
export const EDGE_BEAD_COL_RING_M2               = 28; // f32
export const EDGE_BEAD_COL_RING_M3               = 32; // f32
export const EDGE_BEAD_COL_RING_M4               = 36; // f32
export const EDGE_BEAD_COL_RING_M5               = 40; // f32
export const EDGE_BEAD_COL_RING_M6               = 44; // f32
export const EDGE_BEAD_COL_RING_M7               = 48; // f32
export const EDGE_BEAD_COL_RING_M8               = 52; // f32
export const EDGE_BEAD_COL_RING_M9               = 56; // f32
export const EDGE_BEAD_COL_RING_M10              = 60; // f32
export const EDGE_BEAD_COL_RING_M11              = 64; // f32
export const EDGE_BEAD_COL_RING_M12              = 68; // f32
export const EDGE_BEAD_COL_RING_M13              = 72; // f32
export const EDGE_BEAD_COL_RING_M14              = 76; // f32
export const EDGE_BEAD_COL_RING_M15              = 80; // f32
export const EDGE_BEAD_STRIDE                    = 84;

export function readEdgeBeadX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_X, true); }
export function readEdgeBeadY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_Y, true); }
export function readEdgeBeadZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_Z, true); }
export function readEdgeBeadValue(view: DataView, row: number): number { return view.getInt32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_VALUE, true); }
export function readEdgeBeadEdgeRow(view: DataView, row: number): number { return view.getInt32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_EDGE_ROW, true); }
export function readEdgeBeadRingM0(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M0, true); }
export function readEdgeBeadRingM1(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M1, true); }
export function readEdgeBeadRingM2(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M2, true); }
export function readEdgeBeadRingM3(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M3, true); }
export function readEdgeBeadRingM4(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M4, true); }
export function readEdgeBeadRingM5(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M5, true); }
export function readEdgeBeadRingM6(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M6, true); }
export function readEdgeBeadRingM7(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M7, true); }
export function readEdgeBeadRingM8(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M8, true); }
export function readEdgeBeadRingM9(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M9, true); }
export function readEdgeBeadRingM10(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M10, true); }
export function readEdgeBeadRingM11(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M11, true); }
export function readEdgeBeadRingM12(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M12, true); }
export function readEdgeBeadRingM13(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M13, true); }
export function readEdgeBeadRingM14(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M14, true); }
export function readEdgeBeadRingM15(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M15, true); }

// ── TiltArrow block ──────────────────────────────────────────
export const TILT_ARROW_COL_RECEIVED             = 0; // u8
export const TILT_ARROW_COL_SHAFT_M0             = 1; // f32
export const TILT_ARROW_COL_SHAFT_M1             = 5; // f32
export const TILT_ARROW_COL_SHAFT_M2             = 9; // f32
export const TILT_ARROW_COL_SHAFT_M3             = 13; // f32
export const TILT_ARROW_COL_SHAFT_M4             = 17; // f32
export const TILT_ARROW_COL_SHAFT_M5             = 21; // f32
export const TILT_ARROW_COL_SHAFT_M6             = 25; // f32
export const TILT_ARROW_COL_SHAFT_M7             = 29; // f32
export const TILT_ARROW_COL_SHAFT_M8             = 33; // f32
export const TILT_ARROW_COL_SHAFT_M9             = 37; // f32
export const TILT_ARROW_COL_SHAFT_M10            = 41; // f32
export const TILT_ARROW_COL_SHAFT_M11            = 45; // f32
export const TILT_ARROW_COL_SHAFT_M12            = 49; // f32
export const TILT_ARROW_COL_SHAFT_M13            = 53; // f32
export const TILT_ARROW_COL_SHAFT_M14            = 57; // f32
export const TILT_ARROW_COL_SHAFT_M15            = 61; // f32
export const TILT_ARROW_COL_HEAD_M0              = 65; // f32
export const TILT_ARROW_COL_HEAD_M1              = 69; // f32
export const TILT_ARROW_COL_HEAD_M2              = 73; // f32
export const TILT_ARROW_COL_HEAD_M3              = 77; // f32
export const TILT_ARROW_COL_HEAD_M4              = 81; // f32
export const TILT_ARROW_COL_HEAD_M5              = 85; // f32
export const TILT_ARROW_COL_HEAD_M6              = 89; // f32
export const TILT_ARROW_COL_HEAD_M7              = 93; // f32
export const TILT_ARROW_COL_HEAD_M8              = 97; // f32
export const TILT_ARROW_COL_HEAD_M9              = 101; // f32
export const TILT_ARROW_COL_HEAD_M10             = 105; // f32
export const TILT_ARROW_COL_HEAD_M11             = 109; // f32
export const TILT_ARROW_COL_HEAD_M12             = 113; // f32
export const TILT_ARROW_COL_HEAD_M13             = 117; // f32
export const TILT_ARROW_COL_HEAD_M14             = 121; // f32
export const TILT_ARROW_COL_HEAD_M15             = 125; // f32
export const TILT_ARROW_STRIDE                   = 129;

export function readTiltArrowReceived(view: DataView, row: number): number { return view.getUint8(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_RECEIVED); }
export function readTiltArrowShaftM0(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M0, true); }
export function readTiltArrowShaftM1(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M1, true); }
export function readTiltArrowShaftM2(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M2, true); }
export function readTiltArrowShaftM3(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M3, true); }
export function readTiltArrowShaftM4(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M4, true); }
export function readTiltArrowShaftM5(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M5, true); }
export function readTiltArrowShaftM6(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M6, true); }
export function readTiltArrowShaftM7(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M7, true); }
export function readTiltArrowShaftM8(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M8, true); }
export function readTiltArrowShaftM9(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M9, true); }
export function readTiltArrowShaftM10(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M10, true); }
export function readTiltArrowShaftM11(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M11, true); }
export function readTiltArrowShaftM12(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M12, true); }
export function readTiltArrowShaftM13(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M13, true); }
export function readTiltArrowShaftM14(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M14, true); }
export function readTiltArrowShaftM15(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_SHAFT_M15, true); }
export function readTiltArrowHeadM0(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M0, true); }
export function readTiltArrowHeadM1(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M1, true); }
export function readTiltArrowHeadM2(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M2, true); }
export function readTiltArrowHeadM3(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M3, true); }
export function readTiltArrowHeadM4(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M4, true); }
export function readTiltArrowHeadM5(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M5, true); }
export function readTiltArrowHeadM6(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M6, true); }
export function readTiltArrowHeadM7(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M7, true); }
export function readTiltArrowHeadM8(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M8, true); }
export function readTiltArrowHeadM9(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M9, true); }
export function readTiltArrowHeadM10(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M10, true); }
export function readTiltArrowHeadM11(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M11, true); }
export function readTiltArrowHeadM12(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M12, true); }
export function readTiltArrowHeadM13(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M13, true); }
export function readTiltArrowHeadM14(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M14, true); }
export function readTiltArrowHeadM15(view: DataView, row: number): number { return view.getFloat32(row * TILT_ARROW_STRIDE + TILT_ARROW_COL_HEAD_M15, true); }

// ── ChannelVector block ──────────────────────────────────────
export const CHANNEL_VECTOR_COL_SHAFT_M0         = 0; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M1         = 4; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M2         = 8; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M3         = 12; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M4         = 16; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M5         = 20; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M6         = 24; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M7         = 28; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M8         = 32; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M9         = 36; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M10        = 40; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M11        = 44; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M12        = 48; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M13        = 52; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M14        = 56; // f32
export const CHANNEL_VECTOR_COL_SHAFT_M15        = 60; // f32
export const CHANNEL_VECTOR_COL_HEAD_M0          = 64; // f32
export const CHANNEL_VECTOR_COL_HEAD_M1          = 68; // f32
export const CHANNEL_VECTOR_COL_HEAD_M2          = 72; // f32
export const CHANNEL_VECTOR_COL_HEAD_M3          = 76; // f32
export const CHANNEL_VECTOR_COL_HEAD_M4          = 80; // f32
export const CHANNEL_VECTOR_COL_HEAD_M5          = 84; // f32
export const CHANNEL_VECTOR_COL_HEAD_M6          = 88; // f32
export const CHANNEL_VECTOR_COL_HEAD_M7          = 92; // f32
export const CHANNEL_VECTOR_COL_HEAD_M8          = 96; // f32
export const CHANNEL_VECTOR_COL_HEAD_M9          = 100; // f32
export const CHANNEL_VECTOR_COL_HEAD_M10         = 104; // f32
export const CHANNEL_VECTOR_COL_HEAD_M11         = 108; // f32
export const CHANNEL_VECTOR_COL_HEAD_M12         = 112; // f32
export const CHANNEL_VECTOR_COL_HEAD_M13         = 116; // f32
export const CHANNEL_VECTOR_COL_HEAD_M14         = 120; // f32
export const CHANNEL_VECTOR_COL_HEAD_M15         = 124; // f32
export const CHANNEL_VECTOR_STRIDE               = 128;

export function readChannelVectorShaftM0(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M0, true); }
export function readChannelVectorShaftM1(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M1, true); }
export function readChannelVectorShaftM2(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M2, true); }
export function readChannelVectorShaftM3(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M3, true); }
export function readChannelVectorShaftM4(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M4, true); }
export function readChannelVectorShaftM5(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M5, true); }
export function readChannelVectorShaftM6(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M6, true); }
export function readChannelVectorShaftM7(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M7, true); }
export function readChannelVectorShaftM8(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M8, true); }
export function readChannelVectorShaftM9(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M9, true); }
export function readChannelVectorShaftM10(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M10, true); }
export function readChannelVectorShaftM11(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M11, true); }
export function readChannelVectorShaftM12(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M12, true); }
export function readChannelVectorShaftM13(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M13, true); }
export function readChannelVectorShaftM14(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M14, true); }
export function readChannelVectorShaftM15(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_SHAFT_M15, true); }
export function readChannelVectorHeadM0(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M0, true); }
export function readChannelVectorHeadM1(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M1, true); }
export function readChannelVectorHeadM2(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M2, true); }
export function readChannelVectorHeadM3(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M3, true); }
export function readChannelVectorHeadM4(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M4, true); }
export function readChannelVectorHeadM5(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M5, true); }
export function readChannelVectorHeadM6(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M6, true); }
export function readChannelVectorHeadM7(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M7, true); }
export function readChannelVectorHeadM8(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M8, true); }
export function readChannelVectorHeadM9(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M9, true); }
export function readChannelVectorHeadM10(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M10, true); }
export function readChannelVectorHeadM11(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M11, true); }
export function readChannelVectorHeadM12(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M12, true); }
export function readChannelVectorHeadM13(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M13, true); }
export function readChannelVectorHeadM14(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M14, true); }
export function readChannelVectorHeadM15(view: DataView, row: number): number { return view.getFloat32(row * CHANNEL_VECTOR_STRIDE + CHANNEL_VECTOR_COL_HEAD_M15, true); }

// ── Event block ──────────────────────────────────────────────
export const EVENT_COL_KIND                      = 0; // u8
export const EVENT_COL_NODE_ROW                  = 1; // i32
export const EVENT_COL_PORT_ROW                  = 5; // i32
export const EVENT_COL_TARGET_ROW                = 9; // i32
export const EVENT_COL_TARGET_PORT_ROW           = 13; // i32
export const EVENT_COL_EDGE_ROW                  = 17; // i32
export const EVENT_COL_SLOT                      = 21; // i32
export const EVENT_COL_VALUE                     = 25; // i32
export const EVENT_COL_BEAD                      = 29; // u32
export const EVENT_COL_BEAD_STEPS                = 33; // f32
export const EVENT_COL_X                         = 37; // f32
export const EVENT_COL_Y                         = 41; // f32
export const EVENT_COL_Z                         = 45; // f32
export const EVENT_COL_F                         = 49; // f32
export const EVENT_COL_LABEL                     = 53; // u8
export const EVENT_COL_DEBUG                     = 54; // u8
export const EVENT_COL_TEXT_OFF                  = 55; // u32
export const EVENT_COL_TEXT_LEN                  = 59; // u32
export const EVENT_STRIDE                        = 63;

export function readEventKind(view: DataView, row: number): number { return view.getUint8(row * EVENT_STRIDE + EVENT_COL_KIND); }
export function readEventNodeRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_NODE_ROW, true); }
export function readEventPortRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_PORT_ROW, true); }
export function readEventTargetRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_TARGET_ROW, true); }
export function readEventTargetPortRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_TARGET_PORT_ROW, true); }
export function readEventEdgeRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_EDGE_ROW, true); }
export function readEventSlot(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_SLOT, true); }
export function readEventValue(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_VALUE, true); }
export function readEventBead(view: DataView, row: number): number { return view.getUint32(row * EVENT_STRIDE + EVENT_COL_BEAD, true); }
export function readEventBeadSteps(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_BEAD_STEPS, true); }
export function readEventX(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_X, true); }
export function readEventY(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_Y, true); }
export function readEventZ(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_Z, true); }
export function readEventF(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_F, true); }
export function readEventLabel(view: DataView, row: number): number { return view.getUint8(row * EVENT_STRIDE + EVENT_COL_LABEL); }
export function readEventDebug(view: DataView, row: number): number { return view.getUint8(row * EVENT_STRIDE + EVENT_COL_DEBUG); }
export function readEventTextOff(view: DataView, row: number): number { return view.getUint32(row * EVENT_STRIDE + EVENT_COL_TEXT_OFF, true); }
export function readEventTextLen(view: DataView, row: number): number { return view.getUint32(row * EVENT_STRIDE + EVENT_COL_TEXT_LEN, true); }

