// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/bufschema/layout.go  Regenerate: npm run gen:node-defs

// This half holds the Node, Interior block(s). Row blocks are split across two files
// purely to stay under check-file-size.sh's limit — the division is by position in
// Buffer/bufschema/layout.go, not by meaning, so neither file is a category.

// ── Node block ───────────────────────────────────────────────
export const NODE_COL_NODE_ID                    = 0; // i32
export const NODE_COL_CX                         = 4; // f32
export const NODE_COL_CY                         = 8; // f32
export const NODE_COL_CZ                         = 12; // f32
export const NODE_COL_RADIUS                     = 16; // f32
export const NODE_COL_POLE_PHI                   = 20; // f32
export const NODE_COL_POLE_THETA                 = 24; // f32
export const NODE_COL_RING_M0                    = 28; // f32
export const NODE_COL_RING_M1                    = 32; // f32
export const NODE_COL_RING_M2                    = 36; // f32
export const NODE_COL_RING_M3                    = 40; // f32
export const NODE_COL_RING_M4                    = 44; // f32
export const NODE_COL_RING_M5                    = 48; // f32
export const NODE_COL_RING_M6                    = 52; // f32
export const NODE_COL_RING_M7                    = 56; // f32
export const NODE_COL_RING_M8                    = 60; // f32
export const NODE_COL_RING_M9                    = 64; // f32
export const NODE_COL_RING_M10                   = 68; // f32
export const NODE_COL_RING_M11                   = 72; // f32
export const NODE_COL_RING_M12                   = 76; // f32
export const NODE_COL_RING_M13                   = 80; // f32
export const NODE_COL_RING_M14                   = 84; // f32
export const NODE_COL_RING_M15                   = 88; // f32
export const NODE_COL_TOP_TILT_VECTOR_LEN        = 92; // f32
export const NODE_COL_TOP_TILT_VECTOR_IDX        = 96; // i32
export const NODE_COL_TOP_TILT_VECTOR_PHI        = 100; // f32
export const NODE_COL_BOTTOM_TILT_VECTOR_PHI     = 104; // f32
export const NODE_COL_COPLANAR_NORMAL_PHI        = 108; // f32
export const NODE_COL_RECEIVED_VECTOR_LEN        = 112; // f32
export const NODE_COL_RECEIVED_VECTOR_PHI        = 116; // f32
export const NODE_COL_SELECTED                   = 120; // u8
export const NODE_COL_KIND_ID                    = 121; // u8
export const NODE_COL_LABEL_OFF                  = 122; // u32
export const NODE_COL_LABEL_LEN                  = 126; // u32
export const NODE_COL_HOVERED                    = 130; // u8
export const NODE_COL_LATCHED_SEL                = 131; // u8
export const NODE_COL_LATTICE_POINTS             = 132; // u8
export const NODE_COL_ROUNDS_TO_PARALLEL         = 133; // i32
export const NODE_COL_MSGS_TO_PARALLEL           = 137; // i32
export const NODE_COL_DRAG_RLOCKED               = 141; // u8
export const NODE_COL_DRAG_PHI_LOCKED            = 142; // u8
export const NODE_COL_DRAG_THETA_MAX             = 143; // f32
export const NODE_COL_DRAG_ACTIVE                = 147; // u8
export const NODE_COL_HAS_KIND_RULE              = 148; // u8
export const NODE_COL_KIND_RULE_ACTIVE           = 149; // u8
export const NODE_COL_POLE_RING_R                = 150; // f32
export const NODE_COL_SELF_RLOCKED               = 154; // u8
export const NODE_COL_SELF_PHI_LOCKED            = 155; // u8
export const NODE_COL_SELF_THETA_MAX             = 156; // f32
export const NODE_COL_SELF_ACTIVE                = 160; // u8
export const NODE_COL_RULE_GROUP_ID              = 161; // i32
export const NODE_COL_RULE_GROUP_SIZE            = 165; // i32
export const NODE_STRIDE                         = 169;

export function readNodeNodeId(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_NODE_ID, true); }
export function readNodeCX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CX, true); }
export function readNodeCY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CY, true); }
export function readNodeCZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CZ, true); }
export function readNodeRadius(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RADIUS, true); }
export function readNodePolePhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_POLE_PHI, true); }
export function readNodePoleTheta(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_POLE_THETA, true); }
export function readNodeRingM0(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M0, true); }
export function readNodeRingM1(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M1, true); }
export function readNodeRingM2(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M2, true); }
export function readNodeRingM3(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M3, true); }
export function readNodeRingM4(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M4, true); }
export function readNodeRingM5(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M5, true); }
export function readNodeRingM6(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M6, true); }
export function readNodeRingM7(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M7, true); }
export function readNodeRingM8(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M8, true); }
export function readNodeRingM9(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M9, true); }
export function readNodeRingM10(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M10, true); }
export function readNodeRingM11(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M11, true); }
export function readNodeRingM12(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M12, true); }
export function readNodeRingM13(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M13, true); }
export function readNodeRingM14(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M14, true); }
export function readNodeRingM15(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M15, true); }
export function readNodeTopTiltVectorLen(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_TOP_TILT_VECTOR_LEN, true); }
export function readNodeTopTiltVectorIdx(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_TOP_TILT_VECTOR_IDX, true); }
export function readNodeTopTiltVectorPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_TOP_TILT_VECTOR_PHI, true); }
export function readNodeBottomTiltVectorPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_BOTTOM_TILT_VECTOR_PHI, true); }
export function readNodeCoplanarNormalPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_COPLANAR_NORMAL_PHI, true); }
export function readNodeReceivedVectorLen(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RECEIVED_VECTOR_LEN, true); }
export function readNodeReceivedVectorPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RECEIVED_VECTOR_PHI, true); }
export function readNodeSelected(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELECTED); }
export function readNodeKindId(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_KIND_ID); }
export function readNodeLabelOff(view: DataView, row: number): number { return view.getUint32(row * NODE_STRIDE + NODE_COL_LABEL_OFF, true); }
export function readNodeLabelLen(view: DataView, row: number): number { return view.getUint32(row * NODE_STRIDE + NODE_COL_LABEL_LEN, true); }
export function readNodeHovered(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_HOVERED); }
export function readNodeLatchedSel(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_LATCHED_SEL); }
export function readNodeLatticePoints(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_LATTICE_POINTS); }
export function readNodeRoundsToParallel(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_ROUNDS_TO_PARALLEL, true); }
export function readNodeMsgsToParallel(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_MSGS_TO_PARALLEL, true); }
export function readNodeDragRLocked(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_DRAG_RLOCKED); }
export function readNodeDragPhiLocked(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_DRAG_PHI_LOCKED); }
export function readNodeDragThetaMax(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_DRAG_THETA_MAX, true); }
export function readNodeDragActive(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_DRAG_ACTIVE); }
export function readNodeHasKindRule(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_HAS_KIND_RULE); }
export function readNodeKindRuleActive(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_KIND_RULE_ACTIVE); }
export function readNodePoleRingR(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_POLE_RING_R, true); }
export function readNodeSelfRLocked(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELF_RLOCKED); }
export function readNodeSelfPhiLocked(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELF_PHI_LOCKED); }
export function readNodeSelfThetaMax(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_SELF_THETA_MAX, true); }
export function readNodeSelfActive(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELF_ACTIVE); }
export function readNodeRuleGroupId(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_RULE_GROUP_ID, true); }
export function readNodeRuleGroupSize(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_RULE_GROUP_SIZE, true); }

// ── Interior block ───────────────────────────────────────────
export const INTERIOR_COL_PRESENT                = 0; // u8
export const INTERIOR_COL_VALUE                  = 1; // i32
export const INTERIOR_COL_X                      = 5; // f32
export const INTERIOR_COL_Y                      = 9; // f32
export const INTERIOR_COL_Z                      = 13; // f32
export const INTERIOR_STRIDE                     = 17;

export function readInteriorPresent(view: DataView, row: number): number { return view.getUint8(row * INTERIOR_STRIDE + INTERIOR_COL_PRESENT); }
export function readInteriorValue(view: DataView, row: number): number { return view.getInt32(row * INTERIOR_STRIDE + INTERIOR_COL_VALUE, true); }
export function readInteriorX(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_X, true); }
export function readInteriorY(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_Y, true); }
export function readInteriorZ(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_Z, true); }

