// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/bufschema/layout.go  Regenerate: npm run gen:node-defs

// This half holds the Node, Interior block(s). Row blocks are split across two files
// purely to stay under check-file-size.sh's limit — the division is by position in
// Buffer/bufschema/layout.go, not by meaning, so neither file is a category.

// ── Node block ───────────────────────────────────────────────
export const NODE_COL_NODE_ID                    = 0; // i32
export const NODE_COL_CX                         = 4; // f32
export const NODE_COL_CY                         = 8; // f32
export const NODE_COL_CZ                         = 12; // f32
export const NODE_COL_RADIUS                     = 16; // f32
export const NODE_COL_VRX                        = 20; // f32
export const NODE_COL_VRY                        = 24; // f32
export const NODE_COL_VRZ                        = 28; // f32
export const NODE_COL_FRX                        = 32; // f32
export const NODE_COL_FRY                        = 36; // f32
export const NODE_COL_FRZ                        = 40; // f32
export const NODE_COL_POLE_PHI                   = 44; // f32
export const NODE_COL_POLE_THETA                 = 48; // f32
export const NODE_COL_RING_M0                    = 52; // f32
export const NODE_COL_RING_M1                    = 56; // f32
export const NODE_COL_RING_M2                    = 60; // f32
export const NODE_COL_RING_M3                    = 64; // f32
export const NODE_COL_RING_M4                    = 68; // f32
export const NODE_COL_RING_M5                    = 72; // f32
export const NODE_COL_RING_M6                    = 76; // f32
export const NODE_COL_RING_M7                    = 80; // f32
export const NODE_COL_RING_M8                    = 84; // f32
export const NODE_COL_RING_M9                    = 88; // f32
export const NODE_COL_RING_M10                   = 92; // f32
export const NODE_COL_RING_M11                   = 96; // f32
export const NODE_COL_RING_M12                   = 100; // f32
export const NODE_COL_RING_M13                   = 104; // f32
export const NODE_COL_RING_M14                   = 108; // f32
export const NODE_COL_RING_M15                   = 112; // f32
export const NODE_COL_TOP_TILT_VECTOR_LEN        = 116; // f32
export const NODE_COL_TOP_TILT_VECTOR_IDX        = 120; // i32
export const NODE_COL_TOP_TILT_VECTOR_PHI        = 124; // f32
export const NODE_COL_BOTTOM_TILT_VECTOR_PHI     = 128; // f32
export const NODE_COL_COPLANAR_NORMAL_PHI        = 132; // f32
export const NODE_COL_RECEIVED_VECTOR_LEN        = 136; // f32
export const NODE_COL_RECEIVED_VECTOR_PHI        = 140; // f32
export const NODE_COL_SELECTED                   = 144; // u8
export const NODE_COL_KIND_ID                    = 145; // u8
export const NODE_COL_LABEL_OFF                  = 146; // u32
export const NODE_COL_LABEL_LEN                  = 150; // u32
export const NODE_COL_HOVERED                    = 154; // u8
export const NODE_COL_LATCHED_SEL                = 155; // u8
export const NODE_COL_LATTICE_POINTS             = 156; // u8
export const NODE_COL_ROUNDS_TO_PARALLEL         = 157; // i32
export const NODE_COL_MSGS_TO_PARALLEL           = 161; // i32
export const NODE_COL_DRAG_RLOCKED               = 165; // u8
export const NODE_COL_DRAG_PHI_LOCKED            = 166; // u8
export const NODE_COL_DRAG_THETA_MAX             = 167; // f32
export const NODE_COL_DRAG_ACTIVE                = 171; // u8
export const NODE_COL_HAS_KIND_RULE              = 172; // u8
export const NODE_COL_KIND_RULE_ACTIVE           = 173; // u8
export const NODE_COL_POLE_RING_R                = 174; // f32
export const NODE_COL_SELF_RLOCKED               = 178; // u8
export const NODE_COL_SELF_PHI_LOCKED            = 179; // u8
export const NODE_COL_SELF_THETA_MAX             = 180; // f32
export const NODE_COL_SELF_ACTIVE                = 184; // u8
export const NODE_COL_RULE_GROUP_ID              = 185; // i32
export const NODE_COL_RULE_GROUP_SIZE            = 189; // i32
export const NODE_STRIDE                         = 193;

export function readNodeNodeId(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_NODE_ID, true); }
export function readNodeCX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CX, true); }
export function readNodeCY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CY, true); }
export function readNodeCZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CZ, true); }
export function readNodeRadius(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RADIUS, true); }
export function readNodeVRX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRX, true); }
export function readNodeVRY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRY, true); }
export function readNodeVRZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRZ, true); }
export function readNodeFRX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRX, true); }
export function readNodeFRY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRY, true); }
export function readNodeFRZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRZ, true); }
export function readNodePolePhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_POLE_PHI, true); }
export function readNodePoleTheta(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_POLE_THETA, true); }
export function readNodeRingM0(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M0, true); }
export function readNodeRingM1(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M1, true); }
export function readNodeRingM2(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M2, true); }
export function readNodeRingM3(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M3, true); }
export function readNodeRingM4(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M4, true); }
export function readNodeRingM5(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M5, true); }
export function readNodeRingM6(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M6, true); }
export function readNodeRingM7(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M7, true); }
export function readNodeRingM8(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M8, true); }
export function readNodeRingM9(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M9, true); }
export function readNodeRingM10(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M10, true); }
export function readNodeRingM11(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M11, true); }
export function readNodeRingM12(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M12, true); }
export function readNodeRingM13(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M13, true); }
export function readNodeRingM14(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M14, true); }
export function readNodeRingM15(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M15, true); }
export function readNodeTopTiltVectorLen(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_TOP_TILT_VECTOR_LEN, true); }
export function readNodeTopTiltVectorIdx(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_TOP_TILT_VECTOR_IDX, true); }
export function readNodeTopTiltVectorPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_TOP_TILT_VECTOR_PHI, true); }
export function readNodeBottomTiltVectorPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_BOTTOM_TILT_VECTOR_PHI, true); }
export function readNodeCoplanarNormalPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_COPLANAR_NORMAL_PHI, true); }
export function readNodeReceivedVectorLen(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RECEIVED_VECTOR_LEN, true); }
export function readNodeReceivedVectorPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RECEIVED_VECTOR_PHI, true); }
export function readNodeSelected(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELECTED); }
export function readNodeKindId(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_KIND_ID); }
export function readNodeLabelOff(view: DataView, row: number): number { return view.getUint32(row * NODE_STRIDE + NODE_COL_LABEL_OFF, true); }
export function readNodeLabelLen(view: DataView, row: number): number { return view.getUint32(row * NODE_STRIDE + NODE_COL_LABEL_LEN, true); }
export function readNodeHovered(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_HOVERED); }
export function readNodeLatchedSel(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_LATCHED_SEL); }
export function readNodeLatticePoints(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_LATTICE_POINTS); }
export function readNodeRoundsToParallel(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_ROUNDS_TO_PARALLEL, true); }
export function readNodeMsgsToParallel(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_MSGS_TO_PARALLEL, true); }
export function readNodeDragRLocked(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_DRAG_RLOCKED); }
export function readNodeDragPhiLocked(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_DRAG_PHI_LOCKED); }
export function readNodeDragThetaMax(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_DRAG_THETA_MAX, true); }
export function readNodeDragActive(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_DRAG_ACTIVE); }
export function readNodeHasKindRule(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_HAS_KIND_RULE); }
export function readNodeKindRuleActive(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_KIND_RULE_ACTIVE); }
export function readNodePoleRingR(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_POLE_RING_R, true); }
export function readNodeSelfRLocked(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELF_RLOCKED); }
export function readNodeSelfPhiLocked(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELF_PHI_LOCKED); }
export function readNodeSelfThetaMax(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_SELF_THETA_MAX, true); }
export function readNodeSelfActive(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELF_ACTIVE); }
export function readNodeRuleGroupId(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_RULE_GROUP_ID, true); }
export function readNodeRuleGroupSize(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_RULE_GROUP_SIZE, true); }

// ── Interior block ───────────────────────────────────────────
export const INTERIOR_COL_PRESENT                = 0; // u8
export const INTERIOR_COL_VALUE                  = 1; // i32
export const INTERIOR_COL_OX                     = 5; // f32
export const INTERIOR_COL_OY                     = 9; // f32
export const INTERIOR_COL_OZ                     = 13; // f32
export const INTERIOR_STRIDE                     = 17;

export function readInteriorPresent(view: DataView, row: number): number { return view.getUint8(row * INTERIOR_STRIDE + INTERIOR_COL_PRESENT); }
export function readInteriorValue(view: DataView, row: number): number { return view.getInt32(row * INTERIOR_STRIDE + INTERIOR_COL_VALUE, true); }
export function readInteriorOX(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OX, true); }
export function readInteriorOY(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OY, true); }
export function readInteriorOZ(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OZ, true); }

