// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/frame_tags.go's //frametag:ts=... marked constants.
// Regenerate with: npm run gen:node-defs
//
//

export const BUF_BLOCK_TAG_VIEW = 4;

export const BUF_VIEW_FRAME_HEADER_SIZE = 8;

export const BUF_BLOCK_TAG_EDGE_STREAM = 5;

export const BUF_EDGE_STREAM_FRAME_HEADER_SIZE = 8;

export const BUF_BLOCK_TAG_NODE_STREAM = 6;

export const BUF_BLOCK_TAG_INTERIOR_STREAM = 7;

export const BUF_NODE_STREAM_FRAME_HEADER_SIZE = 16;

export const BUF_INTERIOR_STREAM_FRAME_HEADER_SIZE = 4;

export const BUF_BLOCK_TAG_BEAD_STREAM = 8;

/**
 * A single column channel value. The snapshot message carries the column index where a
 * row frame carries its row, so a column needs no message kind of its own.
 */
export const BUF_BLOCK_TAG_COLUMN = 9;

export const BUF_BEAD_STREAM_FRAME_HEADER_SIZE = 12;
