// frame-tags.ts emitter: mirrors Buffer/frame_tags.go's marked constants into
// tools/topology-vscode/src/schema/frame-tags.ts. This is the single source-of-truth
// pipeline for the envelope-level frame tags/header sizes (memory/
// feedback_no_single_writer_bridge.md) — mirroring input_codec.go / input-layout.ts's
// hand-paired split, but generated instead of hand-kept-in-lockstep.
//
// A const is picked up ONLY if it carries a `//frametag:ts=NAME` marker comment
// immediately preceding it (or trailing in its doc block) — this is what lets
// BufNodeStreamLayoutLinkStride (which does not follow the BUF_ prefix naming
// convention) name its own irregular TS export name explicitly, rather than deriving it
// mechanically from the Go name the way curve-params/shading-params do.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

// frameTagConst is one //frametag:ts=... marked constant from Buffer/frame_tags.go.
type frameTagConst struct {
	tsName string // exact TS export name, from the frametag:ts=NAME marker
	value  string // raw literal value (numeric only — all current frame tags are ints)
	doc    string // doc comment text (marker line stripped), used as the TS JSDoc body
}

// parseFrameTags reads Buffer/frame_tags.go and returns every const carrying a
// `//frametag:ts=NAME` marker comment, along with the file's own header doc comment
// (used as the generated file's leading prose block).
func parseFrameTags(goPath string) (header string, consts []frameTagConst, err error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, goPath, nil, parser.ParseComments)
	if err != nil {
		return "", nil, err
	}
	if f.Doc != nil {
		header = f.Doc.Text()
	}

	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}
		for _, spec := range genDecl.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			doc := vs.Doc
			if doc == nil {
				// Unparenthesized single-const decls attach the doc comment to the
				// GenDecl, not the ValueSpec.
				doc = genDecl.Doc
			}
			if doc == nil {
				continue
			}
			tsName := ""
			var docLines []string
			for _, c := range doc.List {
				text := strings.TrimPrefix(c.Text, "//")
				if marker, ok := strings.CutPrefix(strings.TrimSpace(text), "frametag:ts="); ok {
					tsName = strings.TrimSpace(marker)
					continue
				}
				docLines = append(docLines, strings.TrimPrefix(text, " "))
			}
			if tsName == "" {
				continue
			}
			if len(vs.Names) != 1 || len(vs.Values) != 1 {
				return "", nil, fmt.Errorf("frametag marker on non-single const/value spec (name=%s)", tsName)
			}
			lit, ok := vs.Values[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.INT {
				return "", nil, fmt.Errorf("frametag %s: value is not an integer literal", tsName)
			}
			// Trim the trailing blank line(s) left by the blank-comment separator
			// before the marker.
			for len(docLines) > 0 && strings.TrimSpace(docLines[len(docLines)-1]) == "" {
				docLines = docLines[:len(docLines)-1]
			}
			consts = append(consts, frameTagConst{
				tsName: tsName,
				value:  lit.Value,
				doc:    strings.Join(docLines, "\n"),
			})
		}
	}
	if len(consts) == 0 {
		return "", nil, fmt.Errorf("no //frametag:ts=... marked constants found in %s", goPath)
	}
	return header, consts, nil
}

// writeFrameTags emits tools/topology-vscode/src/schema/frame-tags.ts from the parsed
// Buffer/frame_tags.go constants. Value-identical to the previously hand-authored file;
// only structure/provenance comments differ.
func writeFrameTags(outPath, header string, consts []frameTagConst) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: Buffer/frame_tags.go's //frametag:ts=... marked constants.`)
	fmt.Fprintln(w, `// Regenerate with: npm run gen:node-defs`)
	fmt.Fprintln(w, `//`)
	for _, line := range strings.Split(strings.TrimRight(header, "\n"), "\n") {
		if line == "" {
			fmt.Fprintln(w, `//`)
		} else {
			fmt.Fprintf(w, "// %s\n", line)
		}
	}
	fmt.Fprintln(w)

	for _, c := range consts {
		if c.doc != "" {
			fmt.Fprintln(w, "/**")
			for _, line := range strings.Split(strings.TrimRight(c.doc, "\n"), "\n") {
				if line == "" {
					fmt.Fprintln(w, " *")
				} else {
					fmt.Fprintf(w, " * %s\n", line)
				}
			}
			fmt.Fprintln(w, " */")
		}
		fmt.Fprintf(w, "export const %s = %s;\n\n", c.tsName, c.value)
	}

	w.Flush()
	out := strings.TrimRight(buf.String(), "\n") + "\n"
	return os.WriteFile(outPath, []byte(out), 0644)
}
