package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

type frameTagConst struct {
	tsName string
	value  string
	doc    string
}

func parseFrameTags(goPath string) (header string, consts []frameTagConst, err error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, goPath, nil, parser.ParseComments)
	if err != nil {
		return "", nil, err
	}
	if f.Doc != nil {
		header = f.Doc.Text()
	}

	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}
		for _, spec := range genDecl.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			if len(vs.Names) != 1 || len(vs.Values) != 1 {
				return "", nil, fmt.Errorf(
					"%s: const %v declares more than one name or value — a frame tag is one name and one "+
						"integer, since the TS export is derived from that name",
					goPath, vs.Names)
			}
			goName := vs.Names[0].Name
			if !ast.IsExported(goName) {
				continue
			}
			tsName := screamingSnake(goName)

			doc := vs.Doc
			if doc == nil {
				doc = genDecl.Doc
			}
			var docLines []string
			if doc != nil {
				for _, c := range doc.List {
					docLines = append(docLines, strings.TrimPrefix(strings.TrimPrefix(c.Text, "//"), " "))
				}
			}
			lit, ok := vs.Values[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.INT {
				return "", nil, fmt.Errorf("%s: const %s is not an integer literal — a frame tag is a number on the wire", goPath, goName)
			}

			for len(docLines) > 0 && strings.TrimSpace(docLines[len(docLines)-1]) == "" {
				docLines = docLines[:len(docLines)-1]
			}
			consts = append(consts, frameTagConst{
				tsName: tsName,
				value:  lit.Value,
				doc:    strings.Join(docLines, "\n"),
			})
		}
	}
	if len(consts) == 0 {
		return "", nil, fmt.Errorf(
			"no exported constants found in %s — the file IS the list of frame tags, so an empty "+
				"one means the tags moved and this generator is now writing nothing",
			goPath)
	}
	return header, consts, nil
}

func screamingSnake(goName string) string {
	var b strings.Builder
	for i, r := range goName {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		b.WriteRune(r)
	}
	return strings.ToUpper(b.String())
}

func writeFrameTags(outPath, header string, consts []frameTagConst) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: the exported constants in Buffer/frame_tags.go, named as they are there.`)
	fmt.Fprintln(w, `// Regenerate with: npm run gen:node-defs`)
	fmt.Fprintln(w, `//`)
	for _, line := range strings.Split(strings.TrimRight(header, "\n"), "\n") {
		if line == "" {
			fmt.Fprintln(w, `//`)
		} else {
			fmt.Fprintf(w, "// %s\n", line)
		}
	}
	fmt.Fprintln(w)

	for _, c := range consts {
		if c.doc != "" {
			fmt.Fprintln(w, "/**")
			for _, line := range strings.Split(strings.TrimRight(c.doc, "\n"), "\n") {
				if line == "" {
					fmt.Fprintln(w, " *")
				} else {
					fmt.Fprintf(w, " * %s\n", line)
				}
			}
			fmt.Fprintln(w, " */")
		}
		fmt.Fprintf(w, "export const %s = %s;\n\n", c.tsName, c.value)
	}

	w.Flush()
	out := strings.TrimRight(buf.String(), "\n") + "\n"
	return os.WriteFile(outPath, []byte(out), 0644)
}
