package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type sceneEntry struct {
	Name string
	Dir  string
}

func parseScenes(path string) ([]sceneEntry, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}

	var scenes []sceneEntry
	ast.Inspect(f, func(n ast.Node) bool {
		vs, ok := n.(*ast.ValueSpec)
		if !ok || len(vs.Names) != 1 || vs.Names[0].Name != "All" || len(vs.Values) != 1 {
			return true
		}
		lit, ok := vs.Values[0].(*ast.CompositeLit)
		if !ok {
			return true
		}
		for _, el := range lit.Elts {
			entry, ok := el.(*ast.CompositeLit)
			if !ok {
				continue
			}
			var s sceneEntry
			for _, f := range entry.Elts {
				kv, ok := f.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				key, ok := kv.Key.(*ast.Ident)
				if !ok {
					continue
				}
				val, ok := kv.Value.(*ast.BasicLit)
				if !ok || val.Kind != token.STRING {
					continue
				}
				unquoted, err := strconv.Unquote(val.Value)
				if err != nil {
					continue
				}
				switch key.Name {
				case "Name":
					s.Name = unquoted
				case "Dir":
					s.Dir = unquoted
				}
			}
			if s.Name != "" && s.Dir != "" {
				scenes = append(scenes, s)
			}
		}
		return false
	})

	if len(scenes) == 0 {
		return nil, fmt.Errorf("no scenes parsed from %s: scene.All must be a literal of entries with Name and Dir", path)
	}
	return scenes, nil
}

func writeScenes(path string, scenes []sceneEntry) error {
	var b strings.Builder
	b.WriteString("// GENERATED by tools/gen-node-defs from nodes/Wiring/scene/scene.go — do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// Which sibling scene trees exist, and which directory each one is. The extension\n")
	b.WriteString("// host needs this before Go runs: it sizes the stdio array from the SELECTED\n")
	b.WriteString("// scene's counts, and Go — the one that resolves the selection — is not running\n")
	b.WriteString("// yet. Generated rather than written twice, because the two disagreeing is a\n")
	b.WriteString("// panic on every spawn.\n\n")
	b.WriteString("export interface SceneEntry {\n  name: string;\n  dir: string;\n}\n\n")
	b.WriteString("export const SCENES: SceneEntry[] = [\n")
	for _, s := range scenes {
		fmt.Fprintf(&b, "  { name: %q, dir: %q },\n", s.Name, s.Dir)
	}
	b.WriteString("];\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func generateScenes(repoRoot string) {
	scenePath := filepath.Join(repoRoot, "nodes", "Wiring", "scene", "scene.go")
	scenes, err := parseScenes(scenePath)
	if err != nil {
		fatalf("parse scenes: %v", err)
	}
	outPath := filepath.Join(srcRoot(repoRoot), "schema", "scenes-gen.ts")
	if err := writeScenes(outPath, scenes); err != nil {
		fatalf("write %s: %v", outPath, err)
	}
	fmt.Fprintf(os.Stderr, "gen-node-defs: wrote %s (%d scenes)\n", outPath, len(scenes))
}
