// input-layout-gen.ts emitter: mirrors the nodes/Wiring InputLayoutFingerprint const
// (input_fingerprint.go) into tools/topology-vscode/src/schema/input-layout-gen.ts.
//
// The const is located by SCANNING the package, never by a hardcoded filename
// (memory/feedback_guards_hardcoding_single_file_break_on_split.md — it used to live in
// input_codec.go and moved when that file was split by job).
//
// Go's InputLayoutFingerprint string is the single source of truth for the TS→Go input
// record layout (record kind bytes + enum orderings). Go derives its own kind consts and
// enum arrays from that same string via parseFPList (see input_fingerprint.go) — this generator
// derives the TS-side equivalents the same way, so the two languages can never carry a
// hand-copied fingerprint that silently drifts. Only the fingerprint STRING and its
// directly-derived constants/arrays are generated here; the codec functions
// (encode*/decode*, ByteWriter/ByteReader, etc.) stay hand-written in input-encode.ts,
// input-decode.ts, byte-writer.ts, byte-reader.ts, and input-attrs.ts.
//
// Parsing the fingerprint out of Go source lives in input_layout_parse.go; this file is
// only the emit half (writeInputLayout/writeTSArray).
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"strings"
)

// writeInputLayout emits tools/topology-vscode/src/schema/input-layout-gen.ts from the
// parsed fingerprint. Value-identical to what input-layout.ts previously hand-carried for
// these constants; only structure/provenance comments differ.
func writeInputLayout(outPath string, fp *inputLayoutFingerprint) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: nodes/Wiring/inputcodec/input_fingerprint.go's InputLayoutFingerprint const.`)
	fmt.Fprintln(w, `// Regenerate with: npm run gen:node-defs`)
	fmt.Fprintln(w, `//`)
	fmt.Fprintln(w, `// Go is the single source of the TS<->Go input-record layout: Go's InputLayoutFingerprint`)
	fmt.Fprintln(w, `// string is parsed here (the same tokenization Go's own parseFPList uses) to emit the`)
	fmt.Fprintln(w, `// fingerprint string and its directly-derived constants/arrays for TS. There is no`)
	fmt.Fprintln(w, `// separate TS-side fingerprint to hand-keep in lockstep, so the two languages cannot`)
	fmt.Fprintln(w, `// drift apart on record kinds or enum orderings.`)
	fmt.Fprintln(w)

	fmt.Fprintln(w, `// INPUT_LAYOUT_FINGERPRINT: `+fp.raw)
	fmt.Fprintf(w, "export const INPUT_LAYOUT_FINGERPRINT =\n  %q;\n\n", fp.raw)

	fmt.Fprintln(w, `// Record kind bytes (first byte of every record). Must match input_fingerprint.go.`)
	for _, name := range fp.kindNames {
		fmt.Fprintf(w, "export const %s = %s;\n", kindConstName(name), fp.kindValues[name])
	}
	fmt.Fprintln(w)

	fmt.Fprintln(w, `// Enum orderings (u8 index -> string), shared with input_fingerprint.go.`)
	writeTSArray(w, "IN_EVENT_KINDS", fp.eventKinds)
	writeTSArray(w, "IN_HIT_KINDS", fp.hitKinds)
	// EDIT_UPDATE_KINDS_START / _END bound tools/bridge/check-edit-op-parity.sh's axis-2 extraction
	// (the 3rd update-kind parity source, alongside messages.ts EditMsg + stdin_reader.go
	// applyUpdate). Keep the sentinel lines immediately around IN_UPDATE_KINDS.
	fmt.Fprintln(w, `// EDIT_UPDATE_KINDS_START`)
	writeTSArray(w, "IN_UPDATE_KINDS", fp.updateKinds)
	fmt.Fprintln(w, `// EDIT_UPDATE_KINDS_END`)
	writeTSArray(w, "IN_UPDATE_ATTRS", fp.updateAttrs)

	w.Flush()
	out := strings.TrimRight(buf.String(), "\n") + "\n"
	return os.WriteFile(outPath, []byte(out), 0644)
}

func writeTSArray(w *bufio.Writer, name string, values []string) {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	fmt.Fprintf(w, "export const %s = [%s] as const;\n", name, strings.Join(quoted, ", "))
}
