package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
)

// writeKindImports writes kinds_generated.go at the repo root: blank imports for every node
// package that registers a kind, so its init() (and therefore its wire.Register call) runs.
// Folded in from the former standalone tools/gen-kind-imports generator — a package reaches
// wire.Register ONLY via this file's blank import; a missing import means the kind fails at
// runtime with `unknown type "X"`. The import list is sorted by directory name (the import
// path segment), independent of the goKind sort used elsewhere.
func writeKindImports(outPath string, kinds []kindEntry) error {
	const modulePath = "github.com/dtauraso/wirefold"

	dirs := make([]string, 0, len(kinds))
	for _, k := range kinds {
		dirs = append(dirs, k.dir)
	}
	sort.Strings(dirs)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/gen-node-defs. DO NOT EDIT.\n\n")
	buf.WriteString("package main\n\nimport (\n")
	for _, d := range dirs {
		fmt.Fprintf(&buf, "\t_ %q\n", modulePath+"/nodes/"+d)
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format: %w", err)
	}
	return os.WriteFile(outPath, formatted, 0644)
}
