// node-defs.ts emitter: builds NODE_DEFS/NODE_DEFS_ARRAY/NODE_KIND_NAMES from
// the parsed kindEntry slice.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"strings"
)

// writeNodeDefs emits the node-defs.ts file.
func writeNodeDefs(outPath string, kinds []kindEntry) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit. Source: nodes/<Kind>/node.go + SPEC.md`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `export interface NodeDef {`)
	fmt.Fprintln(w, `  bg: string;`)
	fmt.Fprintln(w, `  border: string;`)
	fmt.Fprintln(w, `  text: string;`)
	fmt.Fprintln(w, `  minWidth?: number;`)
	fmt.Fprintln(w, `  // NodeTypeDef-compatible fields for schema/adapter consumers.`)
	fmt.Fprintln(w, `  shape?: string;`)
	fmt.Fprintln(w, `  fill?: string;`)
	fmt.Fprintln(w, `  stroke?: string;`)
	fmt.Fprintln(w, `  width?: number;`)
	fmt.Fprintln(w, `  height?: number;`)
	fmt.Fprintln(w, `  inputs?: { name: string; kind: string; isMulti?: boolean }[];`)
	fmt.Fprintln(w, `  outputs?: { name: string; kind: string; isMulti?: boolean }[];`)
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
	// Emit RUNTIME_IMPLEMENTED_KINDS from goKind names.
	fmt.Fprintln(w, `// PascalCase Go kind names that have a Go runtime.`)
	fmt.Fprintln(w, `// Single source of truth — derived from wire.Register calls.`)
	fmt.Fprintf(w, "export const RUNTIME_IMPLEMENTED_KINDS: ReadonlySet<string> = new Set([\n")
	for _, e := range kinds {
		fmt.Fprintf(w, "  %q,\n", e.goKind)
	}
	fmt.Fprintln(w, `]);`)
	fmt.Fprintln(w)
	// Pre-build the def strings so we can reuse them for both NODE_DEFS and NODE_DEFS_ARRAY.
	// NODE_DEFS itself is keyed by goKind name, so it stays in the alphabetical `kinds` order.
	type kindDef struct {
		goKind string
		kindID uint8
		def    string
	}
	defs := make([]kindDef, len(kinds))
	for i, e := range kinds {
		defs[i] = kindDef{goKind: e.goKind, kindID: e.kindID, def: buildDef(e.view, e.ports)}
	}
	fmt.Fprintln(w, `export const NODE_DEFS: Record<string, NodeDef> = {`)
	for _, kd := range defs {
		fmt.Fprintf(w, "  %s: %s,\n", kd.goKind, kd.def)
	}
	fmt.Fprint(w, `};`, "\n")
	fmt.Fprintln(w)
	// NODE_DEFS_ARRAY is indexed by the stable buffer KindId (see assignKindIDs in
	// main.go), NOT by alphabetical position — a removed kind can leave a gap, which
	// is emitted here as `undefined` so NODE_DEFS_ARRAY[id] still resolves correctly
	// for every OTHER id (TS consumers already tolerate undefined via `def?.x ?? default`).
	// Emitting literals directly (not NODE_DEFS[key]) so tsc with noUncheckedIndexedAccess
	// can't widen to NodeDef|undefined for the populated slots.
	maxID := -1
	byID := map[uint8]kindDef{}
	for _, kd := range defs {
		byID[kd.kindID] = kd
		if int(kd.kindID) > maxID {
			maxID = int(kd.kindID)
		}
	}
	hasGap := len(byID) <= maxID // fewer entries than slots means at least one gap
	arrayType := "readonly NodeDef[]"
	namesType := "readonly string[]"
	if hasGap {
		// Only widen the declared element type when a gap actually exists, so the
		// dense (no-gap) case emits the exact same type annotation as before.
		arrayType = "readonly (NodeDef | undefined)[]"
		namesType = "readonly (string | undefined)[]"
	}
	fmt.Fprintf(w, "export const NODE_DEFS_ARRAY: %s = [\n", arrayType)
	for id := 0; id <= maxID; id++ {
		if kd, ok := byID[uint8(id)]; ok {
			fmt.Fprintf(w, "  %s,\n", kd.def)
		} else {
			fmt.Fprintf(w, "  undefined, // gap left by a removed kind (KindId %d)\n", id)
		}
	}
	fmt.Fprintln(w, `];`)
	fmt.Fprintln(w)
	// NODE_KIND_NAMES: the PascalCase Go kind name for each KindId index, same
	// indexing as NODE_DEFS_ARRAY (index i ↔ buffer KindId i, gaps → undefined).
	// Used by the ext-host buffer-decoded .probe logger to reconstruct a
	// node-geometry event's `nodeKind` string from the numeric KindId column, so
	// no kind string is streamed per node.
	fmt.Fprintf(w, "export const NODE_KIND_NAMES: %s = [\n", namesType)
	for id := 0; id <= maxID; id++ {
		if kd, ok := byID[uint8(id)]; ok {
			fmt.Fprintf(w, "  %q,\n", kd.goKind)
		} else {
			fmt.Fprintf(w, "  undefined, // gap left by a removed kind (KindId %d)\n", id)
		}
	}
	fmt.Fprintln(w, `];`)

	w.Flush()
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}

func buildDef(v viewDef, ports []port) string {
	targets := filterPorts(ports, "in")
	sources := filterPorts(ports, "out")

	var fields []string
	fields = append(fields, fmt.Sprintf(`bg: "%s"`, v.bg))
	fields = append(fields, fmt.Sprintf(`border: "%s"`, v.border))
	fields = append(fields, fmt.Sprintf(`text: "%s"`, v.text))
	if v.minWidth != "" {
		fields = append(fields, fmt.Sprintf(`minWidth: %s`, v.minWidth))
	}
	if v.shape != "" {
		fields = append(fields, fmt.Sprintf(`shape: "%s"`, v.shape))
	}
	if v.fill != "" {
		fields = append(fields, fmt.Sprintf(`fill: "%s"`, v.fill))
	}
	if v.stroke != "" {
		fields = append(fields, fmt.Sprintf(`stroke: "%s"`, v.stroke))
	}
	if v.width != "" {
		fields = append(fields, fmt.Sprintf(`width: %s`, v.width))
	}
	if v.height != "" {
		fields = append(fields, fmt.Sprintf(`height: %s`, v.height))
	}
	// Emit typed inputs/outputs for schema/adapter consumers.
	if len(targets) > 0 {
		fields = append(fields, fmt.Sprintf(`inputs: [%s]`, joinPortsTyped(targets)))
	}
	if len(sources) > 0 {
		fields = append(fields, fmt.Sprintf(`outputs: [%s]`, joinPortsTyped(sources)))
	}
	return "{ " + strings.Join(fields, ", ") + " }"
}

func filterPorts(ports []port, dir string) []port {
	var out []port
	for _, p := range ports {
		if p.direction == dir {
			out = append(out, p)
		}
	}
	return out
}

// joinPortsTyped emits {name, kind, isMulti?} pairs for NodeTypeDef-compatible consumers.
func joinPortsTyped(ports []port) string {
	var parts []string
	for _, p := range ports {
		ek := p.edgeKind
		if ek == "" {
			ek = "chain" // default
		}
		if p.isMulti {
			parts = append(parts, fmt.Sprintf(`{ name: "%s", kind: "%s", isMulti: true }`, p.id, ek))
		} else {
			parts = append(parts, fmt.Sprintf(`{ name: "%s", kind: "%s" }`, p.id, ek))
		}
	}
	return strings.Join(parts, ", ")
}
