// node_dims_gen.go / node_kind_id_gen.go emitters: per-kind render dimensions
// (mirrors SPEC.md View width/height) and the buffer KindId numbering.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
)

// writeNodeDims emits nodes/Wiring/node_dims_gen.go: a kind → render width/height
// map sourced from each kind's SPEC.md ## View width/height fields. The Go
// Go uses these to mirror nodeRadius/nodeWorldPos in geometry-helpers.ts
// when computing port-to-port arc length. Single source of truth = SPEC.md.
func writeNodeDims(outPath string, kinds []kindEntry) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: nodes/<Kind>/SPEC.md ## View width/height fields.`)
	fmt.Fprintln(w, `// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `package Wiring`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// kindDim is the render width/height for one node kind, mirroring`)
	fmt.Fprintln(w, `// NODE_DEFS[kind].width/height in node-defs.ts.`)
	fmt.Fprintln(w, `type kindDim struct{ Width, Height float64 }`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// kindDims maps each runtime kind to its render dimensions.`)
	fmt.Fprintln(w, `var kindDims = map[string]kindDim{`)
	for _, e := range kinds {
		width := e.view.width
		height := e.view.height
		if width == "" {
			width = "110"
		}
		if height == "" {
			height = "60"
		}
		fmt.Fprintf(w, "\t%q: {Width: %s, Height: %s},\n", e.goKind, width, height)
	}
	fmt.Fprintln(w, `}`)

	w.Flush()
	// gofmt the generated Go so the output is canonical and the repo-wide
	// gofmt guard (tools/check-gofmt.sh) stays in agreement with check-generated.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format node_dims_gen.go: %w", err)
	}
	return os.WriteFile(outPath, formatted, 0644)
}

// writeNodeKindID emits Buffer/node_kind_id_gen.go: a kind → uint8 id map so
// each node's own emit path can populate the KindId column in the buffer node block.
// The id is the STABLE, assigned-once value from each kind's SPEC.md "kindId" field
// (see assignKindIDs in main.go) — NOT a sort-derived index, so adding a kind never
// renumbers an existing one. NODE_DEFS_ARRAY in node-defs.ts is indexed by this same id.
func writeNodeKindID(outPath string, kinds []kindEntry) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: nodes/<Kind>/SPEC.md + Wiring.Register calls.`)
	fmt.Fprintln(w, `// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `package Buffer`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// KindIDUnknown is the sentinel KindId value when a node's kind is not in kindIDMap.`)
	fmt.Fprintln(w, `const KindIDUnknown uint8 = 0xFF`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// kindIDMap maps a node's Go kind name (PascalCase) to its stable buffer KindId,`)
	fmt.Fprintln(w, `// assigned once per kind in nodes/<Kind>/SPEC.md and never renumbered by sort`)
	fmt.Fprintln(w, `// order. Id i here ↔ NODE_DEFS_ARRAY[i] on the TS side (gaps left by a removed`)
	fmt.Fprintln(w, `// kind get an undefined placeholder there, not a shift).`)
	fmt.Fprintln(w, `var kindIDMap = map[string]uint8{`)
	// Emit in ascending id order for a stable, readable diff independent of the
	// alphabetical goKind emission order used elsewhere.
	byID := append([]kindEntry(nil), kinds...)
	sort.Slice(byID, func(i, j int) bool { return byID[i].kindID < byID[j].kindID })
	for _, e := range byID {
		fmt.Fprintf(w, "\t%q: %d,\n", e.goKind, e.kindID)
	}
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// NodeKindID returns the buffer KindId for a node's Go kind string.`)
	fmt.Fprintln(w, `// Returns KindIDUnknown (0xFF) when the kind is not in the registry.`)
	fmt.Fprintln(w, `func NodeKindID(kind string) uint8 {`)
	fmt.Fprintln(w, `	if id, ok := kindIDMap[kind]; ok {`)
	fmt.Fprintln(w, `		return id`)
	fmt.Fprintln(w, `	}`)
	fmt.Fprintln(w, `	return KindIDUnknown`)
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// KnownKinds returns every Go kind name present in kindIDMap. IDs are stable`)
	fmt.Fprintln(w, `// and assigned once (see nodes/<Kind>/SPEC.md kindId), so — unlike the id`)
	fmt.Fprintln(w, `// space itself — this set is NOT guaranteed contiguous or dense; a removed`)
	fmt.Fprintln(w, `// kind just leaves its id unused.`)
	fmt.Fprintln(w, `func KnownKinds() []string {`)
	fmt.Fprintln(w, `	out := make([]string, 0, len(kindIDMap))`)
	fmt.Fprintln(w, `	for k := range kindIDMap {`)
	fmt.Fprintln(w, `		out = append(out, k)`)
	fmt.Fprintln(w, `	}`)
	fmt.Fprintln(w, `	return out`)
	fmt.Fprintln(w, `}`)

	w.Flush()
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format node_kind_id_gen.go: %w", err)
	}
	return os.WriteFile(outPath, formatted, 0644)
}
