// writeOverlayGen: the emit half of the overlay pipeline. Parsing OVERLAY_FLAG_NAMES
// out of messages.ts into the overlayFlag slice this reads is overlay_gen.go.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
)

// writeOverlayGen emits nodes/Wiring/viewstate/overlay_state.go: the entire Go-side overlay
// wiring mechanically derived from OVERLAY_FLAG_NAMES — the OverlayState struct + flip/emit
// methods, the DefaultOverlayState constructor, and the OverlayToggles method-expression
// table (bound directly to OverlayState, no MoveDispatch delegator tier). Deviating flags
// (scene/node poles Breadcrumb) are generated from overlayOverrides. Adding an overlay flag
// now means editing OVERLAY_FLAG_NAMES (+ the ~4-5 TS/render sites); every Go site above
// is regenerated. Parity of the generated table is guarded by check-edit-op-parity.sh
// (which reads this file's OVERLAY_TOGGLES sentinel) and staleness by check-generated.sh.
func writeOverlayGen(outPath string, flags []overlayFlag) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: OVERLAY_FLAG_NAMES in tools/topology-vscode/src/messages.ts.`)
	fmt.Fprintln(w, `// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `package viewstate`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `import (`)
	fmt.Fprintln(w, "\t\"fmt\"")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "\tT \"github.com/dtauraso/wirefold/Trace\"")
	fmt.Fprintln(w, `)`)
	fmt.Fprintln(w)

	writeOverlayStateStruct(w, flags)
	writeOverlaySetFlagHelper(w)
	writeOverlayToggleMethods(w, flags)
	writeOverlaySetGuideVisibility(w)
	writeOverlayDefaultConstructor(w, flags)
	writeOverlayTogglesMap(w, flags)
	writeOverlayBreadcrumbTables(w, flags)
	writeOverlayTraceKindMap(w, flags)

	w.Flush()
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format overlay_gen.go: %w", err)
	}
	return os.WriteFile(outPath, formatted, 0644)
}

// writeOverlayStateStruct emits the OverlayState struct: one bool field per flag.
func writeOverlayStateStruct(w *bufio.Writer, flags []overlayFlag) {
	fmt.Fprintln(w, `// OverlayState groups the per-toggle overlay-visibility booleans and their`)
	fmt.Fprintln(w, `// flip/emit logic. Owned by UIState (ui.OV); Wiring's stdin reader's OverlayToggles`)
	fmt.Fprintln(w, `// method-expression table binds these methods directly.`)
	fmt.Fprintln(w, `type OverlayState struct {`)
	for _, f := range flags {
		fmt.Fprintf(w, "\t%s bool\n", exportField(f.field))
	}
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
}

// writeOverlaySetFlagHelper emits setFlag, the shared body of the uniform Toggle* methods.
func writeOverlaySetFlagHelper(w *bufio.Writer) {
	fmt.Fprintln(w, `// setFlag flips *field. Shared body of the uniform Toggle* methods. The RowEvent`)
	fmt.Fprintln(w, `// carrying the new value is written by the caller's own goroutine directly (see`)
	fmt.Fprintln(w, `// Wiring's stdin_dispatch.go's applyUpdate) — this no longer emits through Trace.`)
	fmt.Fprintln(w, `func (o *OverlayState) setFlag(field *bool) {`)
	fmt.Fprintln(w, "\t*field = !*field")
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
}

// writeOverlayToggleMethods emits the per-flag Toggle (+ accessor) on OverlayState. tr is
// kept only for the breadcrumb variants (scenePoles/nodePoles) and to keep every Toggle*
// method's signature uniform for the OverlayToggles method-expression table; the per-owner
// RowEvent write lives at the call site (Wiring's stdin_dispatch.go's applyUpdate), not here.
func writeOverlayToggleMethods(w *bufio.Writer, flags []overlayFlag) {
	for _, f := range flags {
		field := exportField(f.field)
		fmt.Fprintf(w, "// Toggle%s flips %s.\n", f.method, field)
		fmt.Fprintf(w, "func (o *OverlayState) Toggle%s(tr *T.Trace) {\n", f.method)
		if f.breadcrumb != "" {
			fmt.Fprintf(w, "\to.%s = !o.%s\n", field, field)
			fmt.Fprintf(w, "\ttr.Breadcrumb(\"pole-toggle-go\", %q, \"\", fmt.Sprintf(\"visible=%%v\", o.%s))\n", f.breadcrumb, field)
		} else {
			fmt.Fprintf(w, "\to.setFlag(&o.%s)\n", field)
		}
		fmt.Fprintln(w, `}`)
		fmt.Fprintln(w)
		if f.accessor {
			fmt.Fprintf(w, "// %s returns the current %s.\n", f.method, field)
			fmt.Fprintf(w, "func (o *OverlayState) %s() bool {\n", f.method)
			fmt.Fprintf(w, "\treturn o.%s\n", field)
			fmt.Fprintln(w, `}`)
			fmt.Fprintln(w)
		}
	}
}

// writeOverlaySetGuideVisibility emits SetGuideVisibility on OverlayState. The 8 RowEvents
// this snapshot implies are written by the caller (Wiring's scene_overlays_persist.go's
// LoadOverlays) directly.
func writeOverlaySetGuideVisibility(w *bufio.Writer) {
	fmt.Fprintln(w, `// SetGuideVisibility installs an explicit-visibility snapshot wholesale (the TS`)
	fmt.Fprintln(w, `// startup push so settings survive a Go respawn).`)
	fmt.Fprintln(w, `func (o *OverlayState) SetGuideVisibility(ov OverlayState) {`)
	fmt.Fprintln(w, "\t*o = ov")
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
}
