package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
)

func writeOverlayGen(outPath string, flags []overlayFlag) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: OVERLAY_FLAG_NAMES in tools/topology-vscode/src/messages.ts.`)
	fmt.Fprintln(w, `// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `package viewstate`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `import (`)
	fmt.Fprintln(w, "\t\"fmt\"")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "\tT \"github.com/dtauraso/wirefold/Trace\"")
	fmt.Fprintln(w, `)`)
	fmt.Fprintln(w)

	writeOverlayStateStruct(w, flags)
	writeOverlaySetFlagHelper(w)
	writeOverlayToggleMethods(w, flags)
	writeOverlaySetGuideVisibility(w)
	writeOverlayDefaultConstructor(w, flags)
	writeOverlayTogglesMap(w, flags)
	writeOverlayBreadcrumbTables(w, flags)
	writeOverlayTraceKindMap(w, flags)

	w.Flush()
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format overlay_gen.go: %w", err)
	}
	return os.WriteFile(outPath, formatted, 0644)
}

func writeOverlayStateStruct(w *bufio.Writer, flags []overlayFlag) {
	fmt.Fprintln(w, `// OverlayState groups the per-toggle overlay-visibility booleans and their`)
	fmt.Fprintln(w, `// flip/emit logic. Owned by UIState (ui.OV); Wiring's stdin reader's OverlayToggles`)
	fmt.Fprintln(w, `// method-expression table binds these methods directly.`)
	fmt.Fprintln(w, `type OverlayState struct {`)
	for _, f := range flags {
		fmt.Fprintf(w, "\t%s bool\n", exportField(f.field))
	}
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
}

func writeOverlaySetFlagHelper(w *bufio.Writer) {
	fmt.Fprintln(w, `// setFlag flips *field. Shared body of the uniform Toggle* methods. The RowEvent`)
	fmt.Fprintln(w, `// carrying the new value is written by the caller's own goroutine directly (see`)
	fmt.Fprintln(w, `// Wiring's stdin_dispatch.go's applyUpdate) — this no longer emits through Trace.`)
	fmt.Fprintln(w, `func (o *OverlayState) setFlag(field *bool) {`)
	fmt.Fprintln(w, "\t*field = !*field")
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
}

func writeOverlayToggleMethods(w *bufio.Writer, flags []overlayFlag) {
	for _, f := range flags {
		field := exportField(f.field)
		fmt.Fprintf(w, "// Toggle%s flips %s.\n", f.method, field)
		fmt.Fprintf(w, "func (o *OverlayState) Toggle%s(tr *T.Trace) {\n", f.method)
		if f.breadcrumb != "" {
			fmt.Fprintf(w, "\to.%s = !o.%s\n", field, field)
			fmt.Fprintf(w, "\ttr.Breadcrumb(\"pole-toggle-go\", %q, \"\", fmt.Sprintf(\"visible=%%v\", o.%s))\n", f.breadcrumb, field)
		} else {
			fmt.Fprintf(w, "\to.setFlag(&o.%s)\n", field)
		}
		fmt.Fprintln(w, `}`)
		fmt.Fprintln(w)
		if f.accessor {
			fmt.Fprintf(w, "// %s returns the current %s.\n", f.method, field)
			fmt.Fprintf(w, "func (o *OverlayState) %s() bool {\n", f.method)
			fmt.Fprintf(w, "\treturn o.%s\n", field)
			fmt.Fprintln(w, `}`)
			fmt.Fprintln(w)
		}
	}
}

func writeOverlaySetGuideVisibility(w *bufio.Writer) {
	fmt.Fprintln(w, `// SetGuideVisibility installs an explicit-visibility snapshot wholesale (the TS`)
	fmt.Fprintln(w, `// startup push so settings survive a Go respawn).`)
	fmt.Fprintln(w, `func (o *OverlayState) SetGuideVisibility(ov OverlayState) {`)
	fmt.Fprintln(w, "\t*o = ov")
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
}
