package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

// curveParam is one exported constant from curve_params.go with a "CurveParam"
// name prefix.
type curveParam struct {
	tsName string // TS export name (SCREAMING_SNAKE, CurveParam prefix stripped)
	value  string // raw literal value (string or numeric)
	isInt  bool   // true if the literal contains no decimal point
}

// parseCurveParams reads the Go source at goPath and returns all top-level
// const declarations whose names start with "CurveParam".
func parseCurveParams(goPath string) ([]curveParam, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, goPath, nil, 0)
	if err != nil {
		return nil, err
	}
	var params []curveParam
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}
		for _, spec := range genDecl.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, name := range vs.Names {
				if !strings.HasPrefix(name.Name, "CurveParam") {
					continue
				}
				if i >= len(vs.Values) {
					continue
				}
				lit, ok := vs.Values[i].(*ast.BasicLit)
				if !ok {
					continue
				}
				raw := lit.Value
				// Strip surrounding quotes from string literals.
				if lit.Kind == token.STRING {
					raw = strings.Trim(raw, `"`)
				}
				// Convert Go name CurveParamFooBar → TS name CURVE_PARAM_FOO_BAR
				tsName := camelToScreamingSnake(name.Name)
				isInt := lit.Kind == token.INT
				params = append(params, curveParam{tsName: tsName, value: raw, isInt: isInt})
			}
		}
	}
	if len(params) == 0 {
		return nil, fmt.Errorf("no CurveParam* constants found in %s", goPath)
	}
	return params, nil
}

// writeCurveParams emits curve-params.ts from the parsed curveParam slice.
func writeCurveParams(outPath string, params []curveParam) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: nodes/Wiring/nodegeom/curve_params.go CurveParam* constants.`)
	fmt.Fprintln(w, `// Regenerate with: npm run gen:node-defs`)
	fmt.Fprintln(w)
	for _, p := range params {
		if p.isInt {
			fmt.Fprintf(w, "export const %s = %s;\n", p.tsName, p.value)
		} else {
			fmt.Fprintf(w, "export const %s = %s;\n", p.tsName, p.value)
		}
	}

	w.Flush()
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}
