// curve-params.ts / shading-params.ts emitters: mechanically mirror
// CurveParam*/ShadingParam* Go constants into TS exports.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/constant"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// curveParam is one exported constant from curve_params.go with a "CurveParam"
// name prefix.
type curveParam struct {
	tsName string // TS export name (SCREAMING_SNAKE, CurveParam prefix stripped)
	value  string // raw literal value (string or numeric)
	isInt  bool   // true if the literal contains no decimal point
}

// parseCurveParams reads the Go source at goPath and returns all top-level
// const declarations whose names start with "CurveParam".
func parseCurveParams(goPath string) ([]curveParam, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, goPath, nil, 0)
	if err != nil {
		return nil, err
	}
	var params []curveParam
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}
		for _, spec := range genDecl.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, name := range vs.Names {
				if !strings.HasPrefix(name.Name, "CurveParam") {
					continue
				}
				if i >= len(vs.Values) {
					continue
				}
				lit, ok := vs.Values[i].(*ast.BasicLit)
				if !ok {
					continue
				}
				raw := lit.Value
				// Strip surrounding quotes from string literals.
				if lit.Kind == token.STRING {
					raw = strings.Trim(raw, `"`)
				}
				// Convert Go name CurveParamFooBar → TS name CURVE_PARAM_FOO_BAR
				tsName := camelToScreamingSnake(name.Name)
				isInt := lit.Kind == token.INT
				params = append(params, curveParam{tsName: tsName, value: raw, isInt: isInt})
			}
		}
	}
	if len(params) == 0 {
		return nil, fmt.Errorf("no CurveParam* constants found in %s", goPath)
	}
	return params, nil
}

// camelToScreamingSnake converts PascalCase/camelCase to SCREAMING_SNAKE_CASE.
// e.g. CurveParamBulgeFactor → CURVE_PARAM_BULGE_FACTOR
// Inserts '_' before an uppercase letter only when the PRECEDING rune was
// lowercase, so abbreviations like "BeadID" → "BEAD_ID" and "CX" → "CX"
// stay intact (consecutive uppercase letters are NOT split).
func camelToScreamingSnake(s string) string {
	runes := []rune(s)
	var out []rune
	for i, r := range runes {
		if i > 0 && r >= 'A' && r <= 'Z' {
			prev := runes[i-1]
			if prev >= 'a' && prev <= 'z' {
				out = append(out, '_')
			}
		}
		if r >= 'a' && r <= 'z' {
			out = append(out, r-32) // to upper
		} else {
			out = append(out, r)
		}
	}
	return string(out)
}

// writeCurveParams emits curve-params.ts from the parsed curveParam slice.
func writeCurveParams(outPath string, params []curveParam) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: nodes/Wiring/curve_params.go CurveParam* constants.`)
	fmt.Fprintln(w, `// Regenerate with: npm run gen:node-defs`)
	fmt.Fprintln(w)
	for _, p := range params {
		if p.isInt {
			fmt.Fprintf(w, "export const %s = %s;\n", p.tsName, p.value)
		} else {
			fmt.Fprintf(w, "export const %s = %s;\n", p.tsName, p.value)
		}
	}

	w.Flush()
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}

// shadingParam is one exported constant from shading_params.go with a
// "ShadingParam" name prefix. Unlike curveParam, shading params include string
// literals (hex colors), so isStr drives quoting in the emitted TS.
type shadingParam struct {
	tsName string // TS export name (SCREAMING_SNAKE, ShadingParam prefix stripped)
	value  string // raw literal value (unquoted for strings)
	isStr  bool   // true if the Go literal is a string (emit quoted in TS)
}

// parseShadingParams reads the Go source at goPath and returns all top-level
// const declarations whose names start with "ShadingParam". Mirrors
// parseCurveParams but records string-ness so writeShadingParams can quote
// color literals correctly.
//
// Unlike parseCurveParams, a ShadingParam* value need not be a bare literal:
// docs/bead-lattice.md wants ShadingParamBeadRadius written as the actual
// derivation (`wire.BeadTorusOuterR / (1 + ShadingParamBeadRingTubeRatio)`)
// rather than a hand-computed literal that is a second copy of the same fact.
// A plain *ast.BasicLit is still handled with the old direct text extraction
// (byte-identical output for every param that stays a literal); anything else
// is evaluated via constEnv, which resolves identifiers — including ones
// qualified into another package — against real Go constant arithmetic
// (go/constant), so the emitted value is exactly what the Go compiler would
// compute, not a re-derivation that could itself drift from the formula.
func parseShadingParams(repoRoot, goPath string) ([]shadingParam, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, goPath, nil, 0)
	if err != nil {
		return nil, err
	}
	dir := filepath.Dir(goPath)
	var env *constEnv // built lazily: only a non-literal value expression needs it (and its go.mod read)
	var params []shadingParam
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}
		for _, spec := range genDecl.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, name := range vs.Names {
				if !strings.HasPrefix(name.Name, "ShadingParam") {
					continue
				}
				if i >= len(vs.Values) {
					continue
				}
				tsName := camelToScreamingSnake(name.Name)
				if lit, ok := vs.Values[i].(*ast.BasicLit); ok {
					raw := lit.Value
					isStr := lit.Kind == token.STRING
					if isStr {
						raw = strings.Trim(raw, `"`)
					}
					params = append(params, shadingParam{tsName: tsName, value: raw, isStr: isStr})
					continue
				}
				if env == nil {
					env, err = newConstEnv(fset, repoRoot)
					if err != nil {
						return nil, err
					}
				}
				val, err := env.eval(dir, f, vs.Values[i])
				if err != nil {
					return nil, fmt.Errorf("evaluate %s: %w", name.Name, err)
				}
				params = append(params, shadingParam{tsName: tsName, value: constValueString(val), isStr: false})
			}
		}
	}
	if len(params) == 0 {
		return nil, fmt.Errorf("no ShadingParam* constants found in %s", goPath)
	}
	return params, nil
}

// constValueString renders an evaluated go/constant.Value as the literal Go
// (and TS, since both use plain decimal syntax for a float) would print it —
// the shortest decimal that round-trips to the same float64, matching
// strconv.FormatFloat(f, 'g', -1, 64). Untyped constant arithmetic in
// go/constant stays exact (arbitrary-precision rational) until this
// conversion, so this is the one and only place precision can be lost, and
// it loses exactly as much as assigning the constant to a Go float64 would.
func constValueString(v constant.Value) string {
	if v.Kind() == constant.Int {
		return v.ExactString()
	}
	f, _ := constant.Float64Val(v)
	return strconv.FormatFloat(f, 'g', -1, 64)
}

// writeShadingParams emits shading-params.ts from the parsed shadingParam slice.
// String literals (hex colors) are emitted quoted; numeric literals raw.
func writeShadingParams(outPath string, params []shadingParam) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: nodes/Wiring/shading_params.go ShadingParam* constants.`)
	fmt.Fprintln(w, `// Regenerate with: npm run gen:node-defs`)
	fmt.Fprintln(w, `//`)
	fmt.Fprintln(w, `// Go owns the shading PARAMETER values (MODEL.md). TS reads these and applies`)
	fmt.Fprintln(w, `// them to GPU materials / bakes the env map from them — no shading values of its`)
	fmt.Fprintln(w, `// own. The GPU machinery (three.js materials, PMREM bake, binding) stays in TS.`)
	fmt.Fprintln(w)
	for _, p := range params {
		if p.isStr {
			fmt.Fprintf(w, "export const %s = %q;\n", p.tsName, p.value)
		} else {
			fmt.Fprintf(w, "export const %s = %s;\n", p.tsName, p.value)
		}
	}

	w.Flush()
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}
