package main

//go:generate go run .

import (
	"github.com/dtauraso/beadnetwork/scripts/genpaths"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dtauraso/beadnetwork/Categories/RingPoint"
)

func writePathFiles(pathsDir string) error {
	if err := os.MkdirAll(pathsDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(pathsDir, "block.bin"), []byte(RingPoint.ValueRelPath()), 0o644); err != nil {
		return err
	}
	entries, err := os.ReadDir(pathsDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || e.Name() == "block.bin" { // path-resolution-ok: the generator's own output directory
			continue
		}
		if err := os.Remove(filepath.Join(pathsDir, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

func writeNames(path string) error {
	var b strings.Builder
	b.WriteString("// GENERATED by Categories/RingPoint/values from PointValueNames in point_values.go —\n")
	b.WriteString("// do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// The canonical ring surfaces, computed once from constants and never changed.\n")
	b.WriteString("// They are the one thing here that is static, so they cost a slot in\n")
	b.WriteString("// every frame to say the same thing.\n\n")
	b.WriteString("export const RING_POINT_VALUE_NAMES = [\n")
	for _, name := range RingPoint.PointValueNames {
		fmt.Fprintf(&b, "  %q,\n", name)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type RingPointValueName = (typeof RING_POINT_VALUE_NAMES)[number];\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func main() {
	genpaths.SetName("Categories/RingPoint/layout")
	_, srcRoot := genpaths.Roots()

	dir := filepath.Join(srcRoot, "RingPoint")
	pathsDir := filepath.Join(dir, "paths")
	if err := writePathFiles(pathsDir); err != nil {
		genpaths.Fatalf("write ring point paths: %v", err)
	}
	genpaths.Announce(pathsDir, 1, "ring point block path")

	namesPath := filepath.Join(dir, "point-values-gen.ts")
	if err := writeNames(namesPath); err != nil {
		genpaths.Fatalf("write %s: %v", namesPath, err)
	}
	genpaths.Announce(namesPath, len(RingPoint.PointValueNames), "ring point values")
}
