package main

//go:generate go run .

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dtauraso/wirefold/scripts/genpaths"

	ChannelVectors "github.com/dtauraso/wirefold/Categories/Node/ChannelVectors"
)

func writeNames(path string) error {
	var b strings.Builder
	b.WriteString("// GENERATED by Categories/Node/ChannelVectors/values from VectorValueNames in\n")
	b.WriteString("// vector_values.go — do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// One block file per node, holding the channel vectors leaving it. The row\n")
	b.WriteString("// sits in the path, not in the file.\n\n")
	b.WriteString("export const VECTOR_VALUE_NAMES = [\n")
	for _, name := range ChannelVectors.VectorValueNames {
		fmt.Fprintf(&b, "  %q,\n", name)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type VectorValueName = (typeof VECTOR_VALUE_NAMES)[number];\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func main() {
	genpaths.SetName("Categories/Node/ChannelVectors/values")
	_, srcRoot := genpaths.Roots()

	dir := filepath.Join(srcRoot, "Node", "ChannelVectors")
	namesPath := filepath.Join(dir, "vector-values-gen.ts")
	if err := writeNames(namesPath); err != nil {
		genpaths.Fatalf("write %s: %v", namesPath, err)
	}
	genpaths.Announce(namesPath, len(ChannelVectors.VectorValueNames), "channel vector values")

}
