// GENERATED by Categories/Ring/Bead/layout from RingPointValueNames in
// ring_point_values.go — do not edit.
//
// The canonical bead ring surface, computed once from constants and never
// changed. Written at startup, not per frame.

export const RING_POINT_VALUE_NAMES = [
  "x",
  "y",
  "z",
] as const;

export type RingPointValueName = (typeof RING_POINT_VALUE_NAMES)[number];
