// GENERATED by Categories/Ring/Bead/shading — do not edit.
// Source: Categories/Ring/Bead/shading_params.go ShadingParam* constants.
// Regenerate with: go generate ./...
//
// Go owns the shading PARAMETER values (MODEL.md). TS reads these and applies
// them to GPU materials / bakes the env map from them — no shading values of its
// own. The GPU machinery (three.js materials, PMREM bake, binding) stays in TS.

export const SHADING_PARAM_BEAD_RADIUS = 4;
export const SHADING_PARAM_BEAD_RING_TUBE_RATIO = 0.12;
export const SHADING_PARAM_BEAD_RING_SURFACE_NU = 16;
export const SHADING_PARAM_BEAD_RING_SURFACE_NV = 6;
export const SHADING_PARAM_BEAD_COLOR = "#ffffff";
export const SHADING_PARAM_BEAD_EMISSIVE = "#ffffff";
export const SHADING_PARAM_BEAD_EMISSIVE_INTENSITY = 2.5;
export const SHADING_PARAM_CHAIN_BEAD_FILL = "#9acdd3";
