// GENERATED by Categories/NodeKinds/selectright/portsdef — do not edit.
// Source: this kind's own SPEC.md ## View, ## Ports and ## Description.
// Regenerate with: go generate ./...

import type { NodeDef } from "../node-def";

// What this kind looks like in the editor, and the id it carries on the wire.
// node-defs.ts collects this fragment together with the other kinds'; the id
// is authored in SPEC.md and never renumbered, so a removed kind leaves a gap.
export const KIND_NAME = "SelectRight";
export const KIND_ID = 6;
export const DEF: NodeDef = { bg: "#fce4ec", border: "#f06292", text: "#880e4f", minWidth: 110, shape: "rect", fill: "#fce4ec", stroke: "#f06292", width: 80, height: 60, desc: "Passes a value on only when both inputs arrive within one window, favouring the RIGHT one.", inputs: [{ name: "FromLeft", kind: "chain" }, { name: "FromRight", kind: "chain" }], outputs: [{ name: "ToPassed", kind: "chain" }] };
