// GENERATED by Categories/Scene/View/Flags/flags — do not edit.
// Source: Categories/Scene/View/Flags/flags.ts.
//
// What each flag is BEFORE the block has been read. Go's DefaultOverlayState
// turns most of them on, so defaulting to false here would blank the diagram
// on the first frames and on any read that fails - nodeBody and nodeRing off
// means no nodes are drawn at all.

export const OVERLAY_FLAG_DEFAULTS: Record<string, boolean> = {
  "tori": true,
  "scenePoles": true,
  "nodePoles": true,
  "handholds": true,
  "labelsGlobal": true,
  "overlays": true,
  "nodeBody": true,
  "nodeRing": true,
  "ringPick": true,
  "selectionRing": true,
  "hoverRing": true,
  "sceneVectors": true,
  "edgeVectors": true,
  "ruleChannels": true,
  "nodePoleSphere": true,
  "allPoleSpheres": false,
};
