// GENERATED by Categories/Scene/View/Flags/updateattrs — do not edit.
// Source: Flags.UpdateAttrs. The message kind and the entity kinds an edit can
// address are Drag's, and are imported from Scene/Drag/input-defs.ts.
// Regenerate with: go generate ./...

export const IN_UPDATE_ATTRS = ["toggle"] as const;
