// GENERATED by Categories/Scene/Drag/gen — do not edit.
// Source: Drag's kinds.go and Stdin's record_kinds.go.
// Regenerate with: go generate ./...

export const IN_KIND_RAW_INPUT = 10;

export const IN_EVENT_KINDS = ["pointerdown", "pointermove", "pointerup", "wheel", "home", "delete", "key"] as const;

export const IN_HIT_KINDS = ["port", "handhold", "node", "edge", "torus", "empty"] as const;

