// GENERATED by Categories/Chrome/Panels/Panel/flags — do not edit.
// Source: Categories/Chrome/Panels/Panel/flags.ts.
// Regenerate with: go generate ./...
//
// The flags ride ONE file, in this order. The order IS the layout: each value
// is a u32 length then that many bytes. Categories/Chrome/Panels/Panel/paths/block.bin
// hands the renderer the same path, so neither side builds this string itself.

package Panel

const BlockRelPath = "view/panels.bin"

var FlagNames = []string{
	"overlays",
	"node",
	"nodeShape",
	"nodeState",
	"nodePoles",
	"nodeRules",
	"scene",
	"sceneGuides",
	"scenePoles",
	"sceneVectors",
	"sceneLabels",
}
