package main

//go:generate go run .

import (
	"github.com/dtauraso/beadnetwork/scripts/genpaths"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dtauraso/beadnetwork/Categories/Chrome/Pills/NodesDropdown"
)

func writePathFiles(pathsDir string) error {
	if err := os.MkdirAll(pathsDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(pathsDir, "block.bin"), []byte(NodesDropdown.ValueRelPath()), 0o644); err != nil {
		return err
	}
	entries, err := os.ReadDir(pathsDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || e.Name() == "block.bin" { // path-resolution-ok: the generator's own output directory
			continue
		}
		if err := os.Remove(filepath.Join(pathsDir, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

func writeNames(path string) error {
	var b strings.Builder
	b.WriteString("// GENERATED by Categories/Chrome/Pills/NodesDropdown/values from PillValueNames in\n")
	b.WriteString("// pill_values.go — do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// The nodes dropdown's values, each one file under the scene root. The renderer\n")
	b.WriteString("// learns where from Categories/Chrome/Pills/NodesDropdown/paths/, which Go writes from\n")
	b.WriteString("// this same list, so neither side spells a path.\n\n")
	b.WriteString("export const NODES_PILL_VALUE_NAMES = [\n")
	for _, name := range NodesDropdown.PillValueNames {
		fmt.Fprintf(&b, "  %q,\n", name)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type NodesPillValueName = (typeof NODES_PILL_VALUE_NAMES)[number];\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func main() {
	genpaths.SetName("Categories/Chrome/Pills/NodesDropdown/layout")
	_, srcRoot := genpaths.Roots()

	dir := filepath.Join(srcRoot, "Chrome", "Pills", "NodesDropdown")
	pathsDir := filepath.Join(dir, "paths")
	if err := writePathFiles(pathsDir); err != nil {
		genpaths.Fatalf("write nodes pill paths: %v", err)
	}
	genpaths.Announce(pathsDir, len(NodesDropdown.PillValueNames), "nodes pill paths")

	namesPath := filepath.Join(dir, "pill-values-gen.ts")
	if err := writeNames(namesPath); err != nil {
		genpaths.Fatalf("write %s: %v", namesPath, err)
	}
	genpaths.Announce(namesPath, len(NodesDropdown.PillValueNames), "nodes pill values")
}
