// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/bufschema/layout.go  Regenerate: npm run gen:node-defs

// ── Node block ───────────────────────────────────────────────
export const NODE_COL_NODE_ID                    = 0; // i32
export const NODE_COL_CX                         = 4; // f32
export const NODE_COL_CY                         = 8; // f32
export const NODE_COL_CZ                         = 12; // f32
export const NODE_COL_RADIUS                     = 16; // f32
export const NODE_COL_SPHERE_R                   = 20; // f32
export const NODE_COL_VRX                        = 24; // f32
export const NODE_COL_VRY                        = 28; // f32
export const NODE_COL_VRZ                        = 32; // f32
export const NODE_COL_FRX                        = 36; // f32
export const NODE_COL_FRY                        = 40; // f32
export const NODE_COL_FRZ                        = 44; // f32
export const NODE_COL_POLE_PHI                   = 48; // f32
export const NODE_COL_POLE_THETA                 = 52; // f32
export const NODE_COL_RING_AXIS_PHI              = 56; // f32
export const NODE_COL_RING_AXIS_THETA            = 60; // f32
export const NODE_COL_RING_M0                    = 64; // f32
export const NODE_COL_RING_M1                    = 68; // f32
export const NODE_COL_RING_M2                    = 72; // f32
export const NODE_COL_RING_M3                    = 76; // f32
export const NODE_COL_RING_M4                    = 80; // f32
export const NODE_COL_RING_M5                    = 84; // f32
export const NODE_COL_RING_M6                    = 88; // f32
export const NODE_COL_RING_M7                    = 92; // f32
export const NODE_COL_RING_M8                    = 96; // f32
export const NODE_COL_RING_M9                    = 100; // f32
export const NODE_COL_RING_M10                   = 104; // f32
export const NODE_COL_RING_M11                   = 108; // f32
export const NODE_COL_RING_M12                   = 112; // f32
export const NODE_COL_RING_M13                   = 116; // f32
export const NODE_COL_RING_M14                   = 120; // f32
export const NODE_COL_RING_M15                   = 124; // f32
export const NODE_COL_TOP_TILT_VECTOR_LEN        = 128; // f32
export const NODE_COL_TOP_TILT_VECTOR_IDX        = 132; // i32
export const NODE_COL_TOP_TILT_VECTOR_PHI        = 136; // f32
export const NODE_COL_BOTTOM_TILT_VECTOR_PHI     = 140; // f32
export const NODE_COL_COPLANAR_NORMAL_PHI        = 144; // f32
export const NODE_COL_RECEIVED_VECTOR_LEN        = 148; // f32
export const NODE_COL_RECEIVED_VECTOR_PHI        = 152; // f32
export const NODE_COL_SELECTED                   = 156; // u8
export const NODE_COL_KIND_ID                    = 157; // u8
export const NODE_COL_LABEL_OFF                  = 158; // u32
export const NODE_COL_LABEL_LEN                  = 162; // u32
export const NODE_COL_HOVERED                    = 166; // u8
export const NODE_COL_LATCHED_SEL                = 167; // u8
export const NODE_COL_LATTICE_POINTS             = 168; // u8
export const NODE_COL_ROUNDS_TO_PARALLEL         = 169; // i32
export const NODE_COL_MSGS_TO_PARALLEL           = 173; // i32
export const NODE_COL_ORBIT_RLOCKED              = 177; // u8
export const NODE_COL_ORBIT_PHI_LOCKED           = 178; // u8
export const NODE_COL_ORBIT_THETA_MAX            = 179; // f32
export const NODE_COL_ORBIT_ACTIVE               = 183; // u8
export const NODE_STRIDE                         = 184;

export function readNodeNodeId(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_NODE_ID, true); }
export function readNodeCX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CX, true); }
export function readNodeCY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CY, true); }
export function readNodeCZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CZ, true); }
export function readNodeRadius(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RADIUS, true); }
export function readNodeSphereR(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_SPHERE_R, true); }
export function readNodeVRX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRX, true); }
export function readNodeVRY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRY, true); }
export function readNodeVRZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRZ, true); }
export function readNodeFRX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRX, true); }
export function readNodeFRY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRY, true); }
export function readNodeFRZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRZ, true); }
export function readNodePolePhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_POLE_PHI, true); }
export function readNodePoleTheta(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_POLE_THETA, true); }
export function readNodeRingAxisPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_AXIS_PHI, true); }
export function readNodeRingAxisTheta(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_AXIS_THETA, true); }
export function readNodeRingM0(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M0, true); }
export function readNodeRingM1(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M1, true); }
export function readNodeRingM2(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M2, true); }
export function readNodeRingM3(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M3, true); }
export function readNodeRingM4(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M4, true); }
export function readNodeRingM5(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M5, true); }
export function readNodeRingM6(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M6, true); }
export function readNodeRingM7(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M7, true); }
export function readNodeRingM8(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M8, true); }
export function readNodeRingM9(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M9, true); }
export function readNodeRingM10(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M10, true); }
export function readNodeRingM11(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M11, true); }
export function readNodeRingM12(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M12, true); }
export function readNodeRingM13(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M13, true); }
export function readNodeRingM14(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M14, true); }
export function readNodeRingM15(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RING_M15, true); }
export function readNodeTopTiltVectorLen(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_TOP_TILT_VECTOR_LEN, true); }
export function readNodeTopTiltVectorIdx(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_TOP_TILT_VECTOR_IDX, true); }
export function readNodeTopTiltVectorPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_TOP_TILT_VECTOR_PHI, true); }
export function readNodeBottomTiltVectorPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_BOTTOM_TILT_VECTOR_PHI, true); }
export function readNodeCoplanarNormalPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_COPLANAR_NORMAL_PHI, true); }
export function readNodeReceivedVectorLen(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RECEIVED_VECTOR_LEN, true); }
export function readNodeReceivedVectorPhi(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RECEIVED_VECTOR_PHI, true); }
export function readNodeSelected(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELECTED); }
export function readNodeKindId(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_KIND_ID); }
export function readNodeLabelOff(view: DataView, row: number): number { return view.getUint32(row * NODE_STRIDE + NODE_COL_LABEL_OFF, true); }
export function readNodeLabelLen(view: DataView, row: number): number { return view.getUint32(row * NODE_STRIDE + NODE_COL_LABEL_LEN, true); }
export function readNodeHovered(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_HOVERED); }
export function readNodeLatchedSel(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_LATCHED_SEL); }
export function readNodeLatticePoints(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_LATTICE_POINTS); }
export function readNodeRoundsToParallel(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_ROUNDS_TO_PARALLEL, true); }
export function readNodeMsgsToParallel(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_MSGS_TO_PARALLEL, true); }
export function readNodeOrbitRLocked(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_ORBIT_RLOCKED); }
export function readNodeOrbitPhiLocked(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_ORBIT_PHI_LOCKED); }
export function readNodeOrbitThetaMax(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_ORBIT_THETA_MAX, true); }
export function readNodeOrbitActive(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_ORBIT_ACTIVE); }

// ── Interior block ───────────────────────────────────────────
export const INTERIOR_COL_PRESENT                = 0; // u8
export const INTERIOR_COL_VALUE                  = 1; // i32
export const INTERIOR_COL_OX                     = 5; // f32
export const INTERIOR_COL_OY                     = 9; // f32
export const INTERIOR_COL_OZ                     = 13; // f32
export const INTERIOR_STRIDE                     = 17;

export function readInteriorPresent(view: DataView, row: number): number { return view.getUint8(row * INTERIOR_STRIDE + INTERIOR_COL_PRESENT); }
export function readInteriorValue(view: DataView, row: number): number { return view.getInt32(row * INTERIOR_STRIDE + INTERIOR_COL_VALUE, true); }
export function readInteriorOX(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OX, true); }
export function readInteriorOY(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OY, true); }
export function readInteriorOZ(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OZ, true); }

