// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/bufschema/layout.go  Regenerate: npm run gen:node-defs

// ── Edge block ───────────────────────────────────────────────
export const EDGE_COL_SX                         = 0; // f32
export const EDGE_COL_SY                         = 4; // f32
export const EDGE_COL_SZ                         = 8; // f32
export const EDGE_COL_EX                         = 12; // f32
export const EDGE_COL_EY                         = 16; // f32
export const EDGE_COL_EZ                         = 20; // f32
export const EDGE_COL_SRC_NODE_ROW               = 24; // i32
export const EDGE_COL_EDGE_LABEL_OFF             = 28; // u32
export const EDGE_COL_EDGE_LABEL_LEN             = 32; // u32
export const EDGE_STRIDE                         = 36;

export function readEdgeSX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SX, true); }
export function readEdgeSY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SY, true); }
export function readEdgeSZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SZ, true); }
export function readEdgeEX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EX, true); }
export function readEdgeEY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EY, true); }
export function readEdgeEZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EZ, true); }
export function readEdgeSrcNodeRow(view: DataView, row: number): number { return view.getInt32(row * EDGE_STRIDE + EDGE_COL_SRC_NODE_ROW, true); }
export function readEdgeEdgeLabelOff(view: DataView, row: number): number { return view.getUint32(row * EDGE_STRIDE + EDGE_COL_EDGE_LABEL_OFF, true); }
export function readEdgeEdgeLabelLen(view: DataView, row: number): number { return view.getUint32(row * EDGE_STRIDE + EDGE_COL_EDGE_LABEL_LEN, true); }

// ── EdgeBead block ───────────────────────────────────────────
export const EDGE_BEAD_COL_X                     = 0; // f32
export const EDGE_BEAD_COL_Y                     = 4; // f32
export const EDGE_BEAD_COL_Z                     = 8; // f32
export const EDGE_BEAD_COL_VALUE                 = 12; // i32
export const EDGE_BEAD_COL_RING_M0               = 16; // f32
export const EDGE_BEAD_COL_RING_M1               = 20; // f32
export const EDGE_BEAD_COL_RING_M2               = 24; // f32
export const EDGE_BEAD_COL_RING_M3               = 28; // f32
export const EDGE_BEAD_COL_RING_M4               = 32; // f32
export const EDGE_BEAD_COL_RING_M5               = 36; // f32
export const EDGE_BEAD_COL_RING_M6               = 40; // f32
export const EDGE_BEAD_COL_RING_M7               = 44; // f32
export const EDGE_BEAD_COL_RING_M8               = 48; // f32
export const EDGE_BEAD_COL_RING_M9               = 52; // f32
export const EDGE_BEAD_COL_RING_M10              = 56; // f32
export const EDGE_BEAD_COL_RING_M11              = 60; // f32
export const EDGE_BEAD_COL_RING_M12              = 64; // f32
export const EDGE_BEAD_COL_RING_M13              = 68; // f32
export const EDGE_BEAD_COL_RING_M14              = 72; // f32
export const EDGE_BEAD_COL_RING_M15              = 76; // f32
export const EDGE_BEAD_STRIDE                    = 80;

export function readEdgeBeadX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_X, true); }
export function readEdgeBeadY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_Y, true); }
export function readEdgeBeadZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_Z, true); }
export function readEdgeBeadValue(view: DataView, row: number): number { return view.getInt32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_VALUE, true); }
export function readEdgeBeadRingM0(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M0, true); }
export function readEdgeBeadRingM1(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M1, true); }
export function readEdgeBeadRingM2(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M2, true); }
export function readEdgeBeadRingM3(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M3, true); }
export function readEdgeBeadRingM4(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M4, true); }
export function readEdgeBeadRingM5(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M5, true); }
export function readEdgeBeadRingM6(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M6, true); }
export function readEdgeBeadRingM7(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M7, true); }
export function readEdgeBeadRingM8(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M8, true); }
export function readEdgeBeadRingM9(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M9, true); }
export function readEdgeBeadRingM10(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M10, true); }
export function readEdgeBeadRingM11(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M11, true); }
export function readEdgeBeadRingM12(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M12, true); }
export function readEdgeBeadRingM13(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M13, true); }
export function readEdgeBeadRingM14(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M14, true); }
export function readEdgeBeadRingM15(view: DataView, row: number): number { return view.getFloat32(row * EDGE_BEAD_STRIDE + EDGE_BEAD_COL_RING_M15, true); }

// ── RingPoint block ──────────────────────────────────────────
export const RING_POINT_COL_X                    = 0; // f32
export const RING_POINT_COL_Y                    = 4; // f32
export const RING_POINT_COL_Z                    = 8; // f32
export const RING_POINT_STRIDE                   = 12;

export function readRingPointX(view: DataView, row: number): number { return view.getFloat32(row * RING_POINT_STRIDE + RING_POINT_COL_X, true); }
export function readRingPointY(view: DataView, row: number): number { return view.getFloat32(row * RING_POINT_STRIDE + RING_POINT_COL_Y, true); }
export function readRingPointZ(view: DataView, row: number): number { return view.getFloat32(row * RING_POINT_STRIDE + RING_POINT_COL_Z, true); }

// ── Event block ──────────────────────────────────────────────
export const EVENT_COL_KIND                      = 0; // u8
export const EVENT_COL_NODE_ROW                  = 1; // i32
export const EVENT_COL_PORT_ROW                  = 5; // i32
export const EVENT_COL_TARGET_ROW                = 9; // i32
export const EVENT_COL_TARGET_PORT_ROW           = 13; // i32
export const EVENT_COL_EDGE_ROW                  = 17; // i32
export const EVENT_COL_SLOT                      = 21; // i32
export const EVENT_COL_VALUE                     = 25; // i32
export const EVENT_COL_BEAD                      = 29; // u32
export const EVENT_COL_BEAD_STEPS                = 33; // f32
export const EVENT_COL_SIM_LATENCY_MS            = 37; // f32
export const EVENT_COL_X                         = 41; // f32
export const EVENT_COL_Y                         = 45; // f32
export const EVENT_COL_Z                         = 49; // f32
export const EVENT_COL_F                         = 53; // f32
export const EVENT_COL_LABEL                     = 57; // u8
export const EVENT_COL_DEBUG                     = 58; // u8
export const EVENT_COL_TEXT_OFF                  = 59; // u32
export const EVENT_COL_TEXT_LEN                  = 63; // u32
export const EVENT_STRIDE                        = 67;

export function readEventKind(view: DataView, row: number): number { return view.getUint8(row * EVENT_STRIDE + EVENT_COL_KIND); }
export function readEventNodeRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_NODE_ROW, true); }
export function readEventPortRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_PORT_ROW, true); }
export function readEventTargetRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_TARGET_ROW, true); }
export function readEventTargetPortRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_TARGET_PORT_ROW, true); }
export function readEventEdgeRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_EDGE_ROW, true); }
export function readEventSlot(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_SLOT, true); }
export function readEventValue(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_VALUE, true); }
export function readEventBead(view: DataView, row: number): number { return view.getUint32(row * EVENT_STRIDE + EVENT_COL_BEAD, true); }
export function readEventBeadSteps(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_BEAD_STEPS, true); }
export function readEventSimLatencyMs(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_SIM_LATENCY_MS, true); }
export function readEventX(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_X, true); }
export function readEventY(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_Y, true); }
export function readEventZ(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_Z, true); }
export function readEventF(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_F, true); }
export function readEventLabel(view: DataView, row: number): number { return view.getUint8(row * EVENT_STRIDE + EVENT_COL_LABEL); }
export function readEventDebug(view: DataView, row: number): number { return view.getUint8(row * EVENT_STRIDE + EVENT_COL_DEBUG); }
export function readEventTextOff(view: DataView, row: number): number { return view.getUint32(row * EVENT_STRIDE + EVENT_COL_TEXT_OFF, true); }
export function readEventTextLen(view: DataView, row: number): number { return view.getUint32(row * EVENT_STRIDE + EVENT_COL_TEXT_LEN, true); }

