// GENERATED by cmd/gen-node-defs — do not edit.
// Source: OVERLAY_FLAG_NAMES in src/messages.ts.
// Regenerate with: npm run gen:node-defs

package OverlaysDropdown

import (
	"fmt"

	T "github.com/dtauraso/wirefold/src/Trace"
)

// OverlayState groups the per-toggle overlay-visibility booleans and their
// flip/emit logic. Owned by UIState (ui.OV); Wiring's stdin reader's OverlayToggles
// method-expression table binds these methods directly.
type OverlayState struct {
	SceneToriVisible      bool
	ScenePolesVisible     bool
	NodePolesVisible      bool
	HandholdsVisible      bool
	LabelsGlobalVisible   bool
	OverlaysVisible       bool
	NodeBodyVisible       bool
	NodeRingVisible       bool
	RingPickVisible       bool
	SelectionRingVisible  bool
	HoverRingVisible      bool
	SceneVectorsVisible   bool
	RuleChannelsVisible   bool
	NodePoleSphereVisible bool
	AllPoleSpheresVisible bool
}

// setFlag flips *field. Shared body of the uniform Toggle* methods. The RowEvent
// carrying the new value is written by the caller's own goroutine directly (see
// Wiring's stdin_dispatch.go's applyUpdate) — this no longer emits through Trace.
func (o *OverlayState) setFlag(field *bool) {
	*field = !*field
}

// ToggleSceneTori flips SceneToriVisible.
func (o *OverlayState) ToggleSceneTori(tr *T.Trace) {
	o.setFlag(&o.SceneToriVisible)
}

// ToggleScenePoles flips ScenePolesVisible.
func (o *OverlayState) ToggleScenePoles(tr *T.Trace) {
	o.ScenePolesVisible = !o.ScenePolesVisible
	tr.Breadcrumb("pole-toggle-go", "scene", "", fmt.Sprintf("visible=%v", o.ScenePolesVisible))
}

// ToggleNodePoles flips NodePolesVisible.
func (o *OverlayState) ToggleNodePoles(tr *T.Trace) {
	o.NodePolesVisible = !o.NodePolesVisible
	tr.Breadcrumb("pole-toggle-go", "nodes", "", fmt.Sprintf("visible=%v", o.NodePolesVisible))
}

// ToggleHandholds flips HandholdsVisible.
func (o *OverlayState) ToggleHandholds(tr *T.Trace) {
	o.setFlag(&o.HandholdsVisible)
}

// ToggleLabelsGlobal flips LabelsGlobalVisible.
func (o *OverlayState) ToggleLabelsGlobal(tr *T.Trace) {
	o.setFlag(&o.LabelsGlobalVisible)
}

// ToggleOverlaysVis flips OverlaysVisible.
func (o *OverlayState) ToggleOverlaysVis(tr *T.Trace) {
	o.setFlag(&o.OverlaysVisible)
}

// ToggleNodeBody flips NodeBodyVisible.
func (o *OverlayState) ToggleNodeBody(tr *T.Trace) {
	o.setFlag(&o.NodeBodyVisible)
}

// ToggleNodeRing flips NodeRingVisible.
func (o *OverlayState) ToggleNodeRing(tr *T.Trace) {
	o.setFlag(&o.NodeRingVisible)
}

// ToggleRingPick flips RingPickVisible.
func (o *OverlayState) ToggleRingPick(tr *T.Trace) {
	o.setFlag(&o.RingPickVisible)
}

// ToggleSelectionRing flips SelectionRingVisible.
func (o *OverlayState) ToggleSelectionRing(tr *T.Trace) {
	o.setFlag(&o.SelectionRingVisible)
}

// ToggleHoverRing flips HoverRingVisible.
func (o *OverlayState) ToggleHoverRing(tr *T.Trace) {
	o.setFlag(&o.HoverRingVisible)
}

// ToggleSceneVectors flips SceneVectorsVisible.
func (o *OverlayState) ToggleSceneVectors(tr *T.Trace) {
	o.setFlag(&o.SceneVectorsVisible)
}

// ToggleRuleChannels flips RuleChannelsVisible.
func (o *OverlayState) ToggleRuleChannels(tr *T.Trace) {
	o.setFlag(&o.RuleChannelsVisible)
}

// ToggleNodePoleSphere flips NodePoleSphereVisible.
func (o *OverlayState) ToggleNodePoleSphere(tr *T.Trace) {
	o.setFlag(&o.NodePoleSphereVisible)
}

// ToggleAllPoleSpheres flips AllPoleSpheresVisible.
func (o *OverlayState) ToggleAllPoleSpheres(tr *T.Trace) {
	o.setFlag(&o.AllPoleSpheresVisible)
}

// SetGuideVisibility installs an explicit-visibility snapshot wholesale (the TS
// startup push so settings survive a Go respawn).
func (o *OverlayState) SetGuideVisibility(ov OverlayState) {
	*o = ov
}
