// GENERATED by Categories/Node/TiltVectors/values from TiltValueNames in
// tilt_values.go — do not edit.
//
// One block file per node, holding the tilt arrows it shows. The row sits in
// the path, not in the file.

export const TILT_VALUE_NAMES = [
  "received",
  "tiltShaftM0",
  "tiltShaftM1",
  "tiltShaftM2",
  "tiltShaftM3",
  "tiltShaftM4",
  "tiltShaftM5",
  "tiltShaftM6",
  "tiltShaftM7",
  "tiltShaftM8",
  "tiltShaftM9",
  "tiltShaftM10",
  "tiltShaftM11",
  "tiltShaftM12",
  "tiltShaftM13",
  "tiltShaftM14",
  "tiltShaftM15",
  "tiltHeadM0",
  "tiltHeadM1",
  "tiltHeadM2",
  "tiltHeadM3",
  "tiltHeadM4",
  "tiltHeadM5",
  "tiltHeadM6",
  "tiltHeadM7",
  "tiltHeadM8",
  "tiltHeadM9",
  "tiltHeadM10",
  "tiltHeadM11",
  "tiltHeadM12",
  "tiltHeadM13",
  "tiltHeadM14",
  "tiltHeadM15",
] as const;

export type TiltValueName = (typeof TILT_VALUE_NAMES)[number];
