// GENERATED by Categories/NodeKinds/TimeStart/portsdef — do not edit.
// Source: this kind's own SPEC.md ## View, ## Ports and ## Description.
// Regenerate with: go generate ./...

import type { NodeDef } from "../node-def";

// What this kind looks like in the editor, and the id it carries on the wire.
// node-defs.ts collects this fragment together with the other kinds'; the id
// is authored in SPEC.md and never renumbered, so a removed kind leaves a gap.
export const KIND_NAME = "TimeStart";
export const KIND_ID = 10;
export const DEF: NodeDef = { bg: "#fff3e0", border: "#ffc400", text: "#bf360c", minWidth: 90, shape: "rect", fill: "#fff3e0", stroke: "#ffc400", width: 90, height: 60, desc: "The head of a time chain: holds what arrives and fans the value it was holding to every downstream node at once.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "ToNext", kind: "chain", isMulti: true }] };
