// GENERATED by tools/gen-node-defs — do not edit.
// Source: OVERLAY_FLAG_NAMES in tools/topology-vscode/src/messages.ts.
// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs

package viewstate

import (
	T "github.com/dtauraso/wirefold/Trace"
)

// DefaultOverlayState is the startup overlay snapshot used by Wiring's newMoveDispatch.
func DefaultOverlayState() OverlayState {
	return OverlayState{
		SceneToriVisible:      true,
		ScenePolesVisible:     true,
		NodePolesVisible:      true,
		SelSpherePolesVisible: true,
		HandholdsVisible:      true,
		LabelsGlobalVisible:   true,
		OverlaysVisible:       true,
		NodeBodyVisible:       true,
		NodeRingVisible:       true,
		RingPickVisible:       true,
		SelectionRingVisible:  true,
		HoverRingVisible:      true,
		ReachSphereVisible:    true,
		SceneVectorsVisible:   true,
	}
}

// OverlayToggles maps an overlay FLAG name (the attr="toggle" wire name) to the
// OverlayState method that flips it.
//
// OVERLAY_TOGGLES_START
var OverlayToggles = map[string]func(*OverlayState, *T.Trace){
	"tori":           (*OverlayState).ToggleSceneTori,
	"scenePoles":     (*OverlayState).ToggleScenePoles,
	"nodePoles":      (*OverlayState).ToggleNodePoles,
	"selSpherePoles": (*OverlayState).ToggleSelSpherePoles,
	"handholds":      (*OverlayState).ToggleHandholds,
	"labelsGlobal":   (*OverlayState).ToggleLabelsGlobal,
	"overlays":       (*OverlayState).ToggleOverlaysVis,
	"nodeBody":       (*OverlayState).ToggleNodeBody,
	"nodeRing":       (*OverlayState).ToggleNodeRing,
	"ringPick":       (*OverlayState).ToggleRingPick,
	"selectionRing":  (*OverlayState).ToggleSelectionRing,
	"hoverRing":      (*OverlayState).ToggleHoverRing,
	"reachSphere":    (*OverlayState).ToggleReachSphere,
	"sceneVectors":   (*OverlayState).ToggleSceneVectors,
	"commEdges":      (*OverlayState).ToggleCommEdges,
}

// OVERLAY_TOGGLES_END

// OverlayFlagBreadcrumbScope names the overlay flags whose Toggle also logs a
// structured "pole-toggle-go" debug breadcrumb, and the scope text that breadcrumb
// carries. Flags absent here emit no such breadcrumb.
//
// OVERLAY_BREADCRUMB_SCOPES_START
var OverlayFlagBreadcrumbScope = map[string]string{
	"scenePoles": "scene",
	"nodePoles":  "nodes",
}

// OVERLAY_BREADCRUMB_SCOPES_END

// OverlayFlagValue reads the post-toggle bool for the flags named in
// OverlayFlagBreadcrumbScope (same key set).
var OverlayFlagValue = map[string]func(*OverlayState) bool{
	"scenePoles": func(o *OverlayState) bool { return o.ScenePolesVisible },
	"nodePoles":  func(o *OverlayState) bool { return o.NodePolesVisible },
}

// OverlayFlagTraceKind maps the wire FLAG name (same keys as OverlayToggles) to its
// Trace.Kind* string, so Wiring's applyUpdate case can hand EmitViewFrame the ONE event
// that flag's toggle logged (matching the per-toggle tr.X(bool) call).
// Referencing T.Kind<Method> by name means a flag missing its Trace kind constant is a
// Go compile error here, not a silent no-op — see writeOverlayGen in
// tools/gen-node-defs/overlay_gen.go.
//
// OVERLAY_TRACE_KINDS_START
var OverlayFlagTraceKind = map[string]string{
	"tori":           T.KindSceneTori,
	"scenePoles":     T.KindScenePoles,
	"nodePoles":      T.KindNodePoles,
	"selSpherePoles": T.KindSelSpherePoles,
	"handholds":      T.KindHandholds,
	"labelsGlobal":   T.KindLabelsGlobal,
	"overlays":       T.KindOverlaysVis,
	"nodeBody":       T.KindNodeBody,
	"nodeRing":       T.KindNodeRing,
	"ringPick":       T.KindRingPick,
	"selectionRing":  T.KindSelectionRing,
	"hoverRing":      T.KindHoverRing,
	"reachSphere":    T.KindReachSphere,
	"sceneVectors":   T.KindSceneVectors,
	"commEdges":      T.KindCommEdges,
}

// OVERLAY_TRACE_KINDS_END
