// GENERATED by tools/gen-node-defs — do not edit.
// Source: OVERLAY_FLAG_NAMES in tools/topology-vscode/src/messages.ts.
// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs

package viewstate

import (
	"fmt"

	T "github.com/dtauraso/wirefold/Trace"
)

// OverlayState groups the per-toggle overlay-visibility booleans and their
// flip/emit logic. Owned by UIState (ui.OV); Wiring's stdin reader's OverlayToggles
// method-expression table binds these methods directly.
type OverlayState struct {
	SceneToriVisible      bool
	ScenePolesVisible     bool
	NodePolesVisible      bool
	SelSpherePolesVisible bool
	HandholdsVisible      bool
	LabelsGlobalVisible   bool
	OverlaysVisible       bool
	NodeBodyVisible       bool
	NodeRingVisible       bool
	RingPickVisible       bool
	SelectionRingVisible  bool
	HoverRingVisible      bool
	ReachSphereVisible    bool
}

// setFlag flips *field. Shared body of the uniform Toggle* methods. The RowEvent
// carrying the new value is written by the caller's own goroutine directly (see
// Wiring's stdin_dispatch.go's applyUpdate) — this no longer emits through Trace.
func (o *OverlayState) setFlag(field *bool) {
	*field = !*field
}

// ToggleSceneTori flips SceneToriVisible.
func (o *OverlayState) ToggleSceneTori(tr *T.Trace) {
	o.setFlag(&o.SceneToriVisible)
}

// ToggleScenePoles flips ScenePolesVisible.
func (o *OverlayState) ToggleScenePoles(tr *T.Trace) {
	o.ScenePolesVisible = !o.ScenePolesVisible
	tr.Breadcrumb("pole-toggle-go", "scene", "", fmt.Sprintf("visible=%v", o.ScenePolesVisible))
}

// ToggleNodePoles flips NodePolesVisible.
func (o *OverlayState) ToggleNodePoles(tr *T.Trace) {
	o.NodePolesVisible = !o.NodePolesVisible
	tr.Breadcrumb("pole-toggle-go", "nodes", "", fmt.Sprintf("visible=%v", o.NodePolesVisible))
}

// ToggleSelSpherePoles flips SelSpherePolesVisible.
func (o *OverlayState) ToggleSelSpherePoles(tr *T.Trace) {
	o.setFlag(&o.SelSpherePolesVisible)
}

// ToggleHandholds flips HandholdsVisible.
func (o *OverlayState) ToggleHandholds(tr *T.Trace) {
	o.setFlag(&o.HandholdsVisible)
}

// ToggleLabelsGlobal flips LabelsGlobalVisible.
func (o *OverlayState) ToggleLabelsGlobal(tr *T.Trace) {
	o.setFlag(&o.LabelsGlobalVisible)
}

// ToggleOverlaysVis flips OverlaysVisible.
func (o *OverlayState) ToggleOverlaysVis(tr *T.Trace) {
	o.setFlag(&o.OverlaysVisible)
}

// ToggleNodeBody flips NodeBodyVisible.
func (o *OverlayState) ToggleNodeBody(tr *T.Trace) {
	o.setFlag(&o.NodeBodyVisible)
}

// ToggleNodeRing flips NodeRingVisible.
func (o *OverlayState) ToggleNodeRing(tr *T.Trace) {
	o.setFlag(&o.NodeRingVisible)
}

// ToggleRingPick flips RingPickVisible.
func (o *OverlayState) ToggleRingPick(tr *T.Trace) {
	o.setFlag(&o.RingPickVisible)
}

// ToggleSelectionRing flips SelectionRingVisible.
func (o *OverlayState) ToggleSelectionRing(tr *T.Trace) {
	o.setFlag(&o.SelectionRingVisible)
}

// ToggleHoverRing flips HoverRingVisible.
func (o *OverlayState) ToggleHoverRing(tr *T.Trace) {
	o.setFlag(&o.HoverRingVisible)
}

// ToggleReachSphere flips ReachSphereVisible.
func (o *OverlayState) ToggleReachSphere(tr *T.Trace) {
	o.setFlag(&o.ReachSphereVisible)
}

// SetGuideVisibility installs an explicit-visibility snapshot wholesale (the TS
// startup push so settings survive a Go respawn).
func (o *OverlayState) SetGuideVisibility(ov OverlayState) {
	*o = ov
}

// DefaultOverlayState is the startup overlay snapshot used by Wiring's newMoveDispatch.
func DefaultOverlayState() OverlayState {
	return OverlayState{
		SceneToriVisible:      true,
		ScenePolesVisible:     true,
		NodePolesVisible:      true,
		SelSpherePolesVisible: true,
		HandholdsVisible:      true,
		LabelsGlobalVisible:   true,
		OverlaysVisible:       true,
		NodeBodyVisible:       true,
		NodeRingVisible:       true,
		RingPickVisible:       true,
		SelectionRingVisible:  true,
		HoverRingVisible:      true,
		ReachSphereVisible:    true,
	}
}

// OverlayToggles maps an overlay FLAG name (the attr="toggle" wire name) to the
// OverlayState method that flips it.
//
// OVERLAY_TOGGLES_START
var OverlayToggles = map[string]func(*OverlayState, *T.Trace){
	"tori":           (*OverlayState).ToggleSceneTori,
	"scenePoles":     (*OverlayState).ToggleScenePoles,
	"nodePoles":      (*OverlayState).ToggleNodePoles,
	"selSpherePoles": (*OverlayState).ToggleSelSpherePoles,
	"handholds":      (*OverlayState).ToggleHandholds,
	"labelsGlobal":   (*OverlayState).ToggleLabelsGlobal,
	"overlays":       (*OverlayState).ToggleOverlaysVis,
	"nodeBody":       (*OverlayState).ToggleNodeBody,
	"nodeRing":       (*OverlayState).ToggleNodeRing,
	"ringPick":       (*OverlayState).ToggleRingPick,
	"selectionRing":  (*OverlayState).ToggleSelectionRing,
	"hoverRing":      (*OverlayState).ToggleHoverRing,
	"reachSphere":    (*OverlayState).ToggleReachSphere,
}

// OVERLAY_TOGGLES_END

// OverlayFlagBreadcrumbScope names the overlay flags whose Toggle also logs a
// structured "pole-toggle-go" debug breadcrumb, and the scope text that breadcrumb
// carries. Flags absent here emit no such breadcrumb.
//
// OVERLAY_BREADCRUMB_SCOPES_START
var OverlayFlagBreadcrumbScope = map[string]string{
	"scenePoles": "scene",
	"nodePoles":  "nodes",
}

// OVERLAY_BREADCRUMB_SCOPES_END

// OverlayFlagValue reads the post-toggle bool for the flags named in
// OverlayFlagBreadcrumbScope (same key set).
var OverlayFlagValue = map[string]func(*OverlayState) bool{
	"scenePoles": func(o *OverlayState) bool { return o.ScenePolesVisible },
	"nodePoles":  func(o *OverlayState) bool { return o.NodePolesVisible },
}

// OverlayFlagTraceKind maps the wire FLAG name (same keys as OverlayToggles) to its
// Trace.Kind* string, so Wiring's applyUpdate case can hand EmitViewFrame the ONE event
// that flag's toggle logged (matching the per-toggle tr.X(bool) call).
// Referencing T.Kind<Method> by name means a flag missing its Trace kind constant is a
// Go compile error here, not a silent no-op — see writeOverlayGen in
// tools/gen-node-defs/overlay_gen.go.
//
// OVERLAY_TRACE_KINDS_START
var OverlayFlagTraceKind = map[string]string{
	"tori":           T.KindSceneTori,
	"scenePoles":     T.KindScenePoles,
	"nodePoles":      T.KindNodePoles,
	"selSpherePoles": T.KindSelSpherePoles,
	"handholds":      T.KindHandholds,
	"labelsGlobal":   T.KindLabelsGlobal,
	"overlays":       T.KindOverlaysVis,
	"nodeBody":       T.KindNodeBody,
	"nodeRing":       T.KindNodeRing,
	"ringPick":       T.KindRingPick,
	"selectionRing":  T.KindSelectionRing,
	"hoverRing":      T.KindHoverRing,
	"reachSphere":    T.KindReachSphere,
}

// OVERLAY_TRACE_KINDS_END
