// GENERATED by Categories/NodeKinds/NodePhi/portsdef — do not edit.
// Source: this kind's own SPEC.md ## View, ## Ports and ## Description.
// Regenerate with: go generate ./...

import type { NodeDef } from "../node-def";

// What this kind looks like in the editor, and the id it carries on the wire.
// node-defs.ts collects this fragment together with the other kinds'; the id
// is authored in SPEC.md and never renumbered, so a removed kind leaves a gap.
export const KIND_NAME = "NodePhi";
export const KIND_ID = 11;
export const DEF: NodeDef = { bg: "#fff8e1", border: "#f9a825", text: "#4e342e", minWidth: 70, shape: "rect", fill: "#fff8e1", stroke: "#f9a825", width: 70, height: 60, desc: "One half of a pair: turns its own tilt vector toward rest by exchanging directions with its partner, one step per arrival.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }] };
