// GENERATED by Categories/NodeKinds/NodePhiTheta3/portsdef — do not edit.
// Source: this kind's own SPEC.md ## View, ## Ports and ## Description.
// Regenerate with: go generate ./...

import type { NodeDef } from "../node-def";

// What this kind looks like in the editor, and the id it carries on the wire.
// node-defs.ts collects this fragment together with the other kinds'; the id
// is authored in SPEC.md and never renumbered, so a removed kind leaves a gap.
export const KIND_NAME = "NodePhiTheta3";
export const KIND_ID = 13;
export const DEF: NodeDef = { bg: "#e3f2fd", border: "#1565c0", text: "#0d2b4a", minWidth: 70, shape: "rect", fill: "#e3f2fd", stroke: "#1565c0", width: 70, height: 60, desc: "One of three φ, θ nodes running the three-node card: receives a local arrival on each of its two links, picks one with k, steps it with dir_down/dir_up, and sends it on." };
