package main

//go:generate go run .

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dtauraso/beadnetwork/scripts/genpaths"

	"github.com/dtauraso/beadnetwork/Categories/Chrome/Panels/PolarRulesPanel"
)

func writePathFiles(pathsDir string) error {
	if err := os.MkdirAll(pathsDir, 0o755); err != nil {
		return err
	}
	if err := genpaths.WriteIfChanged(filepath.Join(pathsDir, "block.bin"), []byte(PolarRulesPanel.ValueRelPath()), 0o644); err != nil {
		return err
	}
	entries, err := os.ReadDir(pathsDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || e.Name() == "block.bin" { // path-resolution-ok: the generator's own output directory
			continue
		}
		if err := os.Remove(filepath.Join(pathsDir, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

func writeNames(path string) error {
	var b strings.Builder
	b.WriteString("// GENERATED by Categories/Chrome/Panels/PolarRulesPanel/values from PanelValueNames in\n")
	b.WriteString("// panel_values.go — do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// The rules panel's values, each one file under the scene root. The renderer\n")
	b.WriteString("// learns where from Categories/Chrome/Panels/PolarRulesPanel/paths/, which Go writes\n")
	b.WriteString("// from this same list, so neither side spells a path.\n\n")
	b.WriteString("export const RULES_VALUE_NAMES = [\n")
	for _, name := range PolarRulesPanel.PanelValueNames {
		fmt.Fprintf(&b, "  %q,\n", name)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type RulesValueName = (typeof RULES_VALUE_NAMES)[number];\n")
	return genpaths.WriteIfChanged(path, []byte(b.String()), 0o644)
}

func main() {
	genpaths.SetName("Categories/Chrome/Panels/PolarRulesPanel/layout")
	_, srcRoot := genpaths.Roots()

	dir := filepath.Join(srcRoot, "Chrome", "Panels", "PolarRulesPanel")
	pathsDir := filepath.Join(dir, "paths")
	if err := writePathFiles(pathsDir); err != nil {
		genpaths.Fatalf("write rules panel paths: %v", err)
	}
	genpaths.Announce(pathsDir, len(PolarRulesPanel.PanelValueNames), "rules panel paths")

	namesPath := filepath.Join(dir, "rules-values-gen.ts")
	if err := writeNames(namesPath); err != nil {
		genpaths.Fatalf("write %s: %v", namesPath, err)
	}
	genpaths.Announce(namesPath, len(PolarRulesPanel.PanelValueNames), "rules panel values")
}
