package main

//go:generate go run .

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/dtauraso/beadnetwork/scripts/genpaths"

	"github.com/dtauraso/beadnetwork/Categories/Chrome/Panels/Panel"
)

func main() {
	genpaths.SetName("Categories/Chrome/Panels/Panel/updateattrs")
	_, srcRoot := genpaths.Roots()

	var b strings.Builder
	fmt.Fprintln(&b, "// GENERATED by Categories/Chrome/Panels/Panel/updateattrs — do not edit.")
	fmt.Fprintln(&b, "// Source: Panel.UpdateAttrs. The message kind and the entity kinds an edit can")
	fmt.Fprintln(&b, "// address are Drag's, and are imported from Scene/Drag/input-defs.ts.")
	fmt.Fprintln(&b, "// Regenerate with: go generate ./...")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "export const IN_UPDATE_ATTRS = [")
	for i, v := range Panel.UpdateAttrs {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", v)
	}
	fmt.Fprintln(&b, "] as const;")

	outPath := filepath.Join(srcRoot, "Chrome", "Panels", "Panel", "update-attrs.ts")
	if err := genpaths.WriteIfChanged(outPath, []byte(b.String()), 0o644); err != nil {
		genpaths.Fatalf("write %s: %v", outPath, err)
	}
	genpaths.Announce(outPath, len(Panel.UpdateAttrs), "update attrs")
}
