package main

//go:generate go run .

import (
	"github.com/dtauraso/beadnetwork/scripts/genpaths"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dtauraso/beadnetwork/Categories/Chrome/Panels/TiltPanel"
)

func writePathFiles(pathsDir string) error {
	if err := os.MkdirAll(pathsDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(pathsDir, "block.bin"), []byte(TiltPanel.ValueRelPath()), 0o644); err != nil {
		return err
	}
	entries, err := os.ReadDir(pathsDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || e.Name() == "block.bin" { // path-resolution-ok: the generator's own output directory
			continue
		}
		if err := os.Remove(filepath.Join(pathsDir, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

func writeNames(path string) error {
	var b strings.Builder
	b.WriteString("// GENERATED by Categories/Chrome/Panels/TiltPanel/values from PanelValueNames in\n")
	b.WriteString("// panel_values.go — do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// The tilt panel's values, in the order they sit in the block. The renderer\n")
	b.WriteString("// learns where that block is from Categories/Chrome/Panels/TiltPanel/paths/, which Go\n")
	b.WriteString("// writes from this same list, so neither side spells a path.\n\n")
	b.WriteString("export const TILT_PANEL_VALUE_NAMES = [\n")
	for _, name := range TiltPanel.PanelValueNames {
		fmt.Fprintf(&b, "  %q,\n", name)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type TiltPanelValueName = (typeof TILT_PANEL_VALUE_NAMES)[number];\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func main() {
	genpaths.SetName("Categories/Chrome/Panels/TiltPanel/layout")
	_, srcRoot := genpaths.Roots()

	dir := filepath.Join(srcRoot, "Chrome", "Panels", "TiltPanel")
	pathsDir := filepath.Join(dir, "paths")
	if err := writePathFiles(pathsDir); err != nil {
		genpaths.Fatalf("write tilt panel paths: %v", err)
	}
	genpaths.Announce(pathsDir, 1, "tilt panel block path")

	namesPath := filepath.Join(dir, "panel-values-gen.ts")
	if err := writeNames(namesPath); err != nil {
		genpaths.Fatalf("write %s: %v", namesPath, err)
	}
	genpaths.Announce(namesPath, len(TiltPanel.PanelValueNames), "tilt panel values")
}
