// GENERATED by src/Input/gen — do not edit.
// Source: the input layout declared in src/Input/gen.
// Regenerate with: go generate ./...

package Stdin

const (
	InKindSave = 4
	InKindRawInput = 10
	InKindEditUpdate = 22
)

var InUpdateKinds = []string{"overlays", "clock", "scene", "tiltVector", "panels", "node", "edge"}

func enumAt(list []string, i byte) string {
	if int(i) >= len(list) {
		return ""
	}
	return list[i]
}
