// GENERATED by src/Scene/TiltVectors/gen from TiltValueNames in
// tilt_values.go — do not edit.
//
// One block file per node, holding the tilt arrows it shows. The row sits in
// the path, not in the file.

export const TILT_VALUE_NAMES = [
  "received",
  "shaftM0",
  "shaftM1",
  "shaftM2",
  "shaftM3",
  "shaftM4",
  "shaftM5",
  "shaftM6",
  "shaftM7",
  "shaftM8",
  "shaftM9",
  "shaftM10",
  "shaftM11",
  "shaftM12",
  "shaftM13",
  "shaftM14",
  "shaftM15",
  "headM0",
  "headM1",
  "headM2",
  "headM3",
  "headM4",
  "headM5",
  "headM6",
  "headM7",
  "headM8",
  "headM9",
  "headM10",
  "headM11",
  "headM12",
  "headM13",
  "headM14",
  "headM15",
] as const;

export type TiltValueName = (typeof TILT_VALUE_NAMES)[number];
