package main

//go:generate go run .

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dtauraso/wirefold/scripts/genpaths"

	Speed "github.com/dtauraso/wirefold/Categories/Speed"
)

func main() {
	genpaths.SetName("Categories/Speed/updateattrs")
	_, srcRoot := genpaths.Roots()

	var b strings.Builder
	fmt.Fprintln(&b, "// GENERATED by Categories/Speed/updateattrs — do not edit.")
	fmt.Fprintln(&b, "// Source: Speed.UpdateAttrs. The message kind and the entity kinds an edit can")
	fmt.Fprintln(&b, "// address are Drag's, and are imported from Scene/Drag/input-defs.ts.")
	fmt.Fprintln(&b, "// Regenerate with: go generate ./...")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "export const IN_UPDATE_ATTRS = [")
	for i, v := range Speed.UpdateAttrs {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", v)
	}
	fmt.Fprintln(&b, "] as const;")

	outPath := filepath.Join(srcRoot, "Speed", "update-attrs.ts")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		genpaths.Fatalf("write %s: %v", outPath, err)
	}
	genpaths.Announce(outPath, len(Speed.UpdateAttrs), "update attrs")
}
