// GENERATED by src/schema/buffer-layout/gen. Do not edit.
// Source: the Scene block(s) in this directory.

import {
  COL_STREAM_BASE_SCENE,
} from "../schema/buffer-layout/column-streams-gen";

export const COL_STREAM_SCENE_CX = COL_STREAM_BASE_SCENE + 0;
export const COL_STREAM_SCENE_CY = COL_STREAM_BASE_SCENE + 1;
export const COL_STREAM_SCENE_CZ = COL_STREAM_BASE_SCENE + 2;
export const COL_STREAM_SCENE_RADIUS = COL_STREAM_BASE_SCENE + 3;
export const COL_STREAM_SCENE_CONSTANT_R = COL_STREAM_BASE_SCENE + 4;
export const COL_STREAM_SCENE_MAX_INDEX_PHI = COL_STREAM_BASE_SCENE + 5;
export const COL_STREAM_SCENE_MAX_INDEX_THETA = COL_STREAM_BASE_SCENE + 6;
export const COL_STREAM_SCENE_NODE_COUNT = COL_STREAM_BASE_SCENE + 7;
export const COL_STREAM_SCENE_EDGE_COUNT = COL_STREAM_BASE_SCENE + 8;
