// GENERATED by src/NodeKinds/gen from src/Scene/scene/scene.go — do not edit.
//
// Which sibling scene trees exist, and which directory each one is. The extension
// host needs this before Go runs: it sizes the stdio array from the SELECTED
// scene's counts, and Go — the one that resolves the selection — is not running
// yet. Generated rather than written twice, because the two disagreeing is a
// panic on every spawn.

export interface SceneEntry {
  name: string;
  dir: string;
}

export const SCENES: SceneEntry[] = [
  { name: "ring", dir: "topology" },
  { name: "pair", dir: "topology-pair" },
];
