// GENERATED by src/Scene/gen from SceneValues in src/Scene/scene_values.go — do not edit.
//
// The scene values the renderer reads as files, and how wide each one is on
// disk. valuefile writes every leaf as eight little-endian bytes, so the kind
// says how to read them, not how many.

export type SceneValueKind = "f64" | "i64";

export interface SceneValueDef {
  name: string;
  kind: SceneValueKind;
}

export const SCENE_VALUES: SceneValueDef[] = [
  { name: "cx", kind: "f64" },
  { name: "cy", kind: "f64" },
  { name: "cz", kind: "f64" },
  { name: "radius", kind: "f64" },
  { name: "constantR", kind: "f64" },
  { name: "maxIndexPhi", kind: "i64" },
  { name: "maxIndexTheta", kind: "i64" },
];
