package main

//go:generate go run .

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dtauraso/beadnetwork/scripts/genpaths"

	NodeShape "github.com/dtauraso/beadnetwork/Categories/Ring/NodeShape"
)

func writeBlockPath(pathsDir, rel string) error {
	if err := os.MkdirAll(pathsDir, 0o755); err != nil {
		return err
	}
	if err := genpaths.WriteIfChanged(filepath.Join(pathsDir, "block.bin"), []byte(rel), 0o644); err != nil {
		return err
	}
	entries, err := os.ReadDir(pathsDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || e.Name() == "block.bin" { // path-resolution-ok: the generator's own output directory
			continue
		}
		if err := os.Remove(filepath.Join(pathsDir, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

func writeRingPointNames(path string) error {
	var b strings.Builder
	b.WriteString("// GENERATED by Categories/Ring/NodeShape/layout from RingPointValueNames in\n")
	b.WriteString("// ring_point_values.go — do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// The canonical node ring surface, computed once from constants and never\n")
	b.WriteString("// changed. Written at startup, not per frame.\n\n")
	b.WriteString("export const RING_POINT_VALUE_NAMES = [\n")
	for _, name := range NodeShape.RingPointValueNames {
		fmt.Fprintf(&b, "  %q,\n", name)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type RingPointValueName = (typeof RING_POINT_VALUE_NAMES)[number];\n")
	return genpaths.WriteIfChanged(path, []byte(b.String()), 0o644)
}

func main() {
	genpaths.SetName("Categories/Ring/NodeShape/layout")
	_, srcRoot := genpaths.Roots()

	dir := filepath.Join(srcRoot, "Ring", "NodeShape")

	pathsDir := filepath.Join(dir, "paths")
	if err := writeBlockPath(pathsDir, NodeShape.RingPointValueRelPath()); err != nil {
		genpaths.Fatalf("write node ring point paths: %v", err)
	}
	genpaths.Announce(pathsDir, 1, "node ring point block path")

	namesPath := filepath.Join(dir, "ring-point-values-gen.ts")
	if err := writeRingPointNames(namesPath); err != nil {
		genpaths.Fatalf("write %s: %v", namesPath, err)
	}
	genpaths.Announce(namesPath, len(NodeShape.RingPointValueNames), "node ring point values")
}
