// GENERATED by Categories/Node/TopVector/layout from TopVectorValueNames in
// top_vector_values.go — do not edit.
//
// One block file per node, written by that node's own top-vector goroutine. The
// row sits in the path, not in the file.

export const TOP_VECTOR_VALUE_NAMES = [
  "drawn",
  "topShaftM0",
  "topShaftM1",
  "topShaftM2",
  "topShaftM3",
  "topShaftM4",
  "topShaftM5",
  "topShaftM6",
  "topShaftM7",
  "topShaftM8",
  "topShaftM9",
  "topShaftM10",
  "topShaftM11",
  "topShaftM12",
  "topShaftM13",
  "topShaftM14",
  "topShaftM15",
  "topHeadM0",
  "topHeadM1",
  "topHeadM2",
  "topHeadM3",
  "topHeadM4",
  "topHeadM5",
  "topHeadM6",
  "topHeadM7",
  "topHeadM8",
  "topHeadM9",
  "topHeadM10",
  "topHeadM11",
  "topHeadM12",
  "topHeadM13",
  "topHeadM14",
  "topHeadM15",
] as const;

export type TopVectorValueName = (typeof TOP_VECTOR_VALUE_NAMES)[number];
