// GENERATED by Chrome/Panels/gen from PointerTargetValueNames in
// pointer_target_values.go — do not edit.
//
// The pointer target follows the cursor, so this one block file is read per
// frame rather than on the interval the rest of chrome uses.

export const POINTER_TARGET_VALUE_NAMES = [
  "x",
  "y",
  "w",
  "h",
  "kind",
  "tipX",
  "tipY",
  "tipText",
] as const;

export type PointerTargetValueName = (typeof POINTER_TARGET_VALUE_NAMES)[number];
