// GENERATED by Chrome/Panels/SliderPanel/gen from PanelValueNames in
// panel_values.go — do not edit.
//
// The slider panel's values, in the order they sit in the block. The renderer
// learns where that block is from Chrome/Panels/SliderPanel/paths/, which Go
// writes from this same list, so neither side spells a path.

export const SLIDER_PANEL_VALUE_NAMES = [
  "boxX",
  "boxY",
  "boxW",
  "boxH",
  "rectX",
  "rectY",
  "rectW",
  "rectH",
  "selected",
  "numText",
  "numLen",
  "denText",
  "denLen",
  "trackX",
  "trackY",
  "trackW",
  "trackH",
] as const;

export type SliderPanelValueName = (typeof SLIDER_PANEL_VALUE_NAMES)[number];
