// GENERATED by Categories/Node/Poles/gen — do not edit.
// Source: Categories/Node/Poles/shading_params.go ShadingParam* constants.
// Regenerate with: go generate ./...
//
// Go owns the shading PARAMETER values (MODEL.md). TS reads these and applies
// them to GPU materials / bakes the env map from them — no shading values of its
// own. The GPU machinery (three.js materials, PMREM bake, binding) stays in TS.

export const SHADING_PARAM_POLE_RING_TUBE_RATIO = 0.08;
export const SHADING_PARAM_POLE_RING_OPACITY = 0.55;
export const SHADING_PARAM_POLE_RING_EMISSIVE_INTENSITY = 0.25;
