// stream-fixture.test.ts — CROSS-LANGUAGE byte-level verification that the REAL Go
// stream-frame packers (Buffer.BuildNodeStreamFrame / BuildEdgeStreamFrame /
// BuildInteriorStreamFrame) and the REAL TS stream-frame decoders (decodeNodeStreamFrame /
// decodeEdgeStreamFrame / decodeInteriorStreamFrame in ../src/webview/three/buffer-decode)
// agree on the wire bytes — the Go->TS direction mirror of
// nodes/Wiring/input_fixture_test.go (TS->Go).
//
// node-stream-blocks.test.ts already covers this decode path, but it builds its own frame
// bytes with `new ArrayBuffer`/`new DataView` in TS and decodes them in TS — a same-language
// round trip that cannot catch a Go/TS offset disagreement (see input_fixture_test.go's
// header for why: if Go drops N bytes at one offset and TS drops N bytes at a DIFFERENT
// offset, both same-language round trips still pass while every subsequent field silently
// misaligns). This test closes that gap on the Go->TS side by decoding Go-produced bytes
// with the REAL TS decoders and asserting every field.
//
// The fixture (fixtures/stream_fixture.json) is generated by `go run
// ./tools/gen-stream-fixture` from the repo root (see tools/gen-stream-fixture/main.go,
// which calls the REAL production Buffer.BuildNodeStreamFrame/BuildEdgeStreamFrame/
// BuildInteriorStreamFrame). It is CHECKED, not trusted: this test also regenerates it live
// into a temp file and byte-diffs it against the committed copy, so a fixture committed
// before a Go packer changed again fails HERE with a clear message instead of quietly
// testing its own past self. If `go` is unavailable, the staleness check is skipped (not
// silently passed) and the decode assertions still run against the committed fixture.
//
// Testing-shape note (docs/testing-shape.md): this does NOT assert that two goroutines
// communicate. It builds one frame (with the real Go builder, in a separate `go run`
// process, no network running) and decodes it (with the real TS decoder, no movers, no
// wiring). Same shape as the sanctioned persistence exception — bytes on the wire, checked
// against the real codec on the other side.
import { describe, it, expect } from "vitest";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { execFileSync } from "child_process";
import {
  decodeNodeStreamFrame,
  decodeEdgeStreamFrame,
  decodeInteriorStreamFrame,
  readNodeStreamLayoutLinkDstNodeRow,
} from "../src/webview/three/buffer-decode";
import {
  readNodeCX, readNodeCY, readNodeCZ, readNodeRadius, readNodeSphereR,
  readNodeVRX, readNodeVRY, readNodeVRZ, readNodeFRX, readNodeFRY, readNodeFRZ,
  readNodeSelected, readNodeKindId, readNodeHovered, readNodeLatchedSel, readNodeGotDragMsg,
  readNodeDragDeltaA, readNodeDragDeltaB, readNodeDragDeltaC, readNodeDragRequantCount,
  readNodeGotForwardMsg, readNodeForwardDeltaA, readNodeForwardDeltaB, readNodeForwardDeltaC,
  readNodeForwardFromRow,
  readPortNodeRow, readPortDX, readPortDY, readPortDZ, readPortPX, readPortPY, readPortPZ,
  readPortIsInput, readPortHovered, readPortPortNameLen, readPortPortNameOff,
  readEdgeSrcPortRow, readEdgeDstPortRow, readEdgeSelected,
  readInteriorPresent, readInteriorValue, readInteriorOX, readInteriorOY, readInteriorOZ,
} from "../src/schema/buffer-layout";

const STR_DECODER = new TextDecoder();

const repoRoot = path.resolve(__dirname, "../../..");
const committedFixturePath = path.join(__dirname, "fixtures", "stream_fixture.json");

interface PortFixture {
  nodeRow: number; dx: number; dy: number; dz: number; px: number; py: number; pz: number;
  isInput: number; hovered: number; nameLen: number; name: string;
}
interface LayoutLinkFixture { dstNodeRow: number }
interface NodeFrameFixture {
  tick: number; nodeRow: number;
  cx: number; cy: number; cz: number; radius: number; sphereR: number;
  vrx: number; vry: number; vrz: number; frx: number; fry: number; frz: number;
  selected: number; kindId: number; hovered: number; latchedSel: number; gotDragMsg: number;
  dragDeltaA: number; dragDeltaB: number; dragDeltaC: number; dragRequantCount: number;
  gotForwardMsg: number; forwardDeltaA: number; forwardDeltaB: number; forwardDeltaC: number;
  forwardFromRow: number;
  label: string;
  ports: PortFixture[];
  layoutLinks: LayoutLinkFixture[];
  hex: string;
}
interface EdgeFrameFixture {
  tick: number; srcPortRow: number; dstPortRow: number; selected: number; label: string;
  beadVal: number[]; beadX: number[]; beadY: number[]; beadZ: number[];
  hex: string;
}
interface InteriorFrameFixture {
  tick: number; present: number[]; value: number[]; ox: number[]; oy: number[]; oz: number[];
  hex: string;
}
interface StreamFixture {
  nodeFrame: NodeFrameFixture;
  edgeFrame: EdgeFrameFixture;
  interiorFrame: InteriorFrameFixture;
}

function hexToArrayBuffer(hex: string): ArrayBuffer {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return bytes.buffer;
}

function loadFixture(fixturePath: string): StreamFixture {
  return JSON.parse(fs.readFileSync(fixturePath, "utf8")) as StreamFixture;
}

function expectClose(got: number, want: number, field: string) {
  expect(got, field).toBeCloseTo(want, 3);
}

// ── TestStreamFixtureFreshness mirror ───────────────────────────────────────────
//
// Regenerates the fixture live (via `go run ./tools/gen-stream-fixture`, the REAL Go
// packers) into a temp file and byte-diffs it against the committed copy. A stale fixture
// fails HERE with a clear pointer to the regeneration command, rather than as silent
// staleness. Skipped (not silently passed) if `go` is unavailable.
describe("stream fixture freshness", () => {
  it("committed fixture matches a live regeneration from the real Go packers", () => {
    let goAvailable = true;
    try {
      execFileSync("go", ["version"], { cwd: repoRoot, stdio: "ignore" });
    } catch {
      goAvailable = false;
    }
    if (!goAvailable) {
      // eslint-disable-next-line no-console
      console.warn("stream-fixture.test.ts: `go` not found on PATH — skipping freshness check (decode assertions below still run against the committed fixture)");
      return;
    }

    const tmpOut = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "stream-fixture-")), "stream_fixture.json");
    execFileSync("go", ["run", "./tools/gen-stream-fixture", tmpOut], { cwd: repoRoot, stdio: "pipe" });

    const committed = fs.readFileSync(committedFixturePath, "utf8");
    const fresh = fs.readFileSync(tmpOut, "utf8");
    expect(
      fresh,
      "tools/topology-vscode/test/fixtures/stream_fixture.json is STALE relative to the current Go stream-frame packers " +
      "(Buffer/node_stream_frame.go, Buffer/edge_stream_frame.go). Regenerate with:\n" +
      "  go run ./tools/gen-stream-fixture\n" +
      "and commit the result."
    ).toEqual(committed);
  });
});

// ── TestStreamFixtureCrossLanguage mirror ───────────────────────────────────────
describe("stream fixture cross-language decode", () => {
  const fx = loadFixture(committedFixturePath);

  it("decodeNodeStreamFrame agrees with the Go-encoded node fixture", () => {
    const want = fx.nodeFrame;
    const buf = hexToArrayBuffer(want.hex);
    const decoded = decodeNodeStreamFrame(0, buf);
    expect(decoded, "Go-encoded node stream frame bytes were rejected by the real TS decoder").not.toBeNull();
    if (!decoded) return;

    expect(decoded.tick).toBe(want.tick);
    expect(decoded.label).toBe(want.label);
    expect(decoded.portCount).toBe(want.ports.length);
    expect(decoded.layoutLinkCount).toBe(want.layoutLinks.length);

    const nv = decoded.nodeView;
    expectClose(readNodeCX(nv, 0), want.cx, "cx");
    expectClose(readNodeCY(nv, 0), want.cy, "cy");
    expectClose(readNodeCZ(nv, 0), want.cz, "cz");
    expectClose(readNodeRadius(nv, 0), want.radius, "radius");
    expectClose(readNodeSphereR(nv, 0), want.sphereR, "sphereR");
    expectClose(readNodeVRX(nv, 0), want.vrx, "vrx");
    expectClose(readNodeVRY(nv, 0), want.vry, "vry");
    expectClose(readNodeVRZ(nv, 0), want.vrz, "vrz");
    expectClose(readNodeFRX(nv, 0), want.frx, "frx");
    expectClose(readNodeFRY(nv, 0), want.fry, "fry");
    expectClose(readNodeFRZ(nv, 0), want.frz, "frz");
    expect(readNodeSelected(nv, 0), "selected").toBe(want.selected);
    expect(readNodeKindId(nv, 0), "kindId").toBe(want.kindId);
    expect(readNodeHovered(nv, 0), "hovered").toBe(want.hovered);
    expect(readNodeLatchedSel(nv, 0), "latchedSel").toBe(want.latchedSel);
    expect(readNodeGotDragMsg(nv, 0), "gotDragMsg").toBe(want.gotDragMsg);
    expect(readNodeDragDeltaA(nv, 0), "dragDeltaA").toBe(want.dragDeltaA);
    expect(readNodeDragDeltaB(nv, 0), "dragDeltaB").toBe(want.dragDeltaB);
    expect(readNodeDragDeltaC(nv, 0), "dragDeltaC").toBe(want.dragDeltaC);
    expect(readNodeDragRequantCount(nv, 0), "dragRequantCount").toBe(want.dragRequantCount);
    expect(readNodeGotForwardMsg(nv, 0), "gotForwardMsg").toBe(want.gotForwardMsg);
    expect(readNodeForwardDeltaA(nv, 0), "forwardDeltaA").toBe(want.forwardDeltaA);
    expect(readNodeForwardDeltaB(nv, 0), "forwardDeltaB").toBe(want.forwardDeltaB);
    expect(readNodeForwardDeltaC(nv, 0), "forwardDeltaC").toBe(want.forwardDeltaC);
    expect(readNodeForwardFromRow(nv, 0), "forwardFromRow").toBe(want.forwardFromRow);

    for (let i = 0; i < want.ports.length; i++) {
      const p = want.ports[i]!;
      const pv = decoded.portView;
      expect(readPortNodeRow(pv, i), `port[${i}].nodeRow`).toBe(p.nodeRow);
      expectClose(readPortDX(pv, i), p.dx, `port[${i}].dx`);
      expectClose(readPortDY(pv, i), p.dy, `port[${i}].dy`);
      expectClose(readPortDZ(pv, i), p.dz, `port[${i}].dz`);
      expectClose(readPortPX(pv, i), p.px, `port[${i}].px`);
      expectClose(readPortPY(pv, i), p.py, `port[${i}].py`);
      expectClose(readPortPZ(pv, i), p.pz, `port[${i}].pz`);
      expect(readPortIsInput(pv, i), `port[${i}].isInput`).toBe(p.isInput);
      expect(readPortHovered(pv, i), `port[${i}].hovered`).toBe(p.hovered);
      expect(readPortPortNameLen(pv, i), `port[${i}].nameLen`).toBe(p.nameLen);
      const nameOff = readPortPortNameOff(pv, i);
      const nameBytes = decoded.portNameBytes.subarray(nameOff, nameOff + p.nameLen);
      expect(STR_DECODER.decode(nameBytes), `port[${i}].name`).toBe(p.name);
    }

    for (let i = 0; i < want.layoutLinks.length; i++) {
      expect(
        readNodeStreamLayoutLinkDstNodeRow(decoded.layoutLinkView, i),
        `layoutLinks[${i}].dstNodeRow`
      ).toBe(want.layoutLinks[i]!.dstNodeRow);
    }
  });

  it("decodeEdgeStreamFrame agrees with the Go-encoded edge fixture", () => {
    const want = fx.edgeFrame;
    const buf = hexToArrayBuffer(want.hex);
    const decoded = decodeEdgeStreamFrame(0, buf);
    expect(decoded, "Go-encoded edge stream frame bytes were rejected by the real TS decoder").not.toBeNull();
    if (!decoded) return;

    expect(decoded.tick).toBe(want.tick);
    expect(decoded.label).toBe(want.label);
    expect(decoded.beadCount).toBe(want.beadVal.length);

    const ev = decoded.edgeView;
    expect(readEdgeSrcPortRow(ev, 0), "srcPortRow").toBe(want.srcPortRow);
    expect(readEdgeDstPortRow(ev, 0), "dstPortRow").toBe(want.dstPortRow);
    expect(readEdgeSelected(ev, 0), "selected").toBe(want.selected);

    for (let i = 0; i < want.beadVal.length; i++) {
      const bv = decoded.beadView;
      expect(bv.getInt32(i * 16 + 12, true), `bead[${i}].value`).toBe(want.beadVal[i]);
      expectClose(bv.getFloat32(i * 16 + 0, true), want.beadX[i]!, `bead[${i}].x`);
      expectClose(bv.getFloat32(i * 16 + 4, true), want.beadY[i]!, `bead[${i}].y`);
      expectClose(bv.getFloat32(i * 16 + 8, true), want.beadZ[i]!, `bead[${i}].z`);
    }
  });

  it("decodeInteriorStreamFrame agrees with the Go-encoded interior fixture", () => {
    const want = fx.interiorFrame;
    const buf = hexToArrayBuffer(want.hex);
    const decoded = decodeInteriorStreamFrame(0, buf);
    expect(decoded, "Go-encoded interior stream frame bytes were rejected by the real TS decoder").not.toBeNull();
    if (!decoded) return;

    expect(decoded.tick).toBe(want.tick);
    const iv = decoded.interiorView;
    for (let i = 0; i < want.present.length; i++) {
      expect(readInteriorPresent(iv, i), `interior[${i}].present`).toBe(want.present[i]);
      expect(readInteriorValue(iv, i), `interior[${i}].value`).toBe(want.value[i]);
      expectClose(readInteriorOX(iv, i), want.ox[i]!, `interior[${i}].ox`);
      expectClose(readInteriorOY(iv, i), want.oy[i]!, `interior[${i}].oy`);
      expectClose(readInteriorOZ(iv, i), want.oz[i]!, `interior[${i}].oz`);
    }
  });
});
