// stream-fixture.test.ts — CROSS-LANGUAGE byte-level verification that the REAL Go
// stream-frame packers (Buffer.BuildNodeStreamFrame / BuildEdgeStreamFrame /
// BuildInteriorStreamFrame) and the REAL TS stream-frame decoders (decodeNodeStreamFrame /
// decodeEdgeStreamFrame / decodeInteriorStreamFrame in ../src/webview/three/buffer-decode)
// agree on the wire bytes — the Go->TS direction mirror of
// nodes/Wiring/input_fixture_test.go (TS->Go).
//
// node-stream-blocks.test.ts already covers this decode path, but it builds its own frame
// bytes with `new ArrayBuffer`/`new DataView` in TS and decodes them in TS — a same-language
// round trip that cannot catch a Go/TS offset disagreement (see input_fixture_test.go's
// header for why: if Go drops N bytes at one offset and TS drops N bytes at a DIFFERENT
// offset, both same-language round trips still pass while every subsequent field silently
// misaligns). This test closes that gap on the Go->TS side by decoding Go-produced bytes
// with the REAL TS decoders and asserting every field.
//
// The fixture (fixtures/stream_fixture.json) is generated by `go run
// ./tools/gen-stream-fixture` from the repo root (see tools/gen-stream-fixture/main.go,
// which calls the REAL production Buffer.BuildNodeStreamFrame/BuildEdgeStreamFrame/
// BuildInteriorStreamFrame). It is CHECKED, not trusted: this test also regenerates it live
// into a temp file and byte-diffs it against the committed copy, so a fixture committed
// before a Go packer changed again fails HERE with a clear message instead of quietly
// testing its own past self. If `go` is unavailable, the staleness check is skipped (not
// silently passed) and the decode assertions still run against the committed fixture.
//
// Testing-shape note (docs/testing-shape.md): this does NOT assert that two goroutines
// communicate. It builds one frame (with the real Go builder, in a separate `go run`
// process, no network running) and decodes it (with the real TS decoder, no movers, no
// wiring). Same shape as the sanctioned persistence exception — bytes on the wire, checked
// against the real codec on the other side.
import { describe, it, expect, vi } from "vitest";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { execFileSync } from "child_process";
import {
  decodeNodeStreamFrame,
  decodeEdgeStreamFrame,
  decodeInteriorStreamFrame,
  readNodeStreamLayoutLinkDstNodeRow,
} from "../src/webview/three/buffer-decode";
import {
  readNodeNodeId,
  readNodeCX, readNodeCY, readNodeCZ, readNodeRadius, readNodeSphereR,
  readNodeVRX, readNodeVRY, readNodeVRZ, readNodeFRX, readNodeFRY, readNodeFRZ,
  readNodeSelected, readNodeKindId, readNodeHovered, readNodeLatchedSel,
  readChainBeadOX,
  readChainBeadOY,
  readChainBeadOZ,
  readChainBeadLit,
  readChainBeadLitValue,
  readEdgeSX, readEdgeSY, readEdgeSZ, readEdgeEX, readEdgeEY, readEdgeEZ, readEdgeSelected,
  readInteriorPresent, readInteriorValue, readInteriorOX, readInteriorOY, readInteriorOZ,
} from "../src/schema/buffer-layout";

const repoRoot = path.resolve(__dirname, "../../..");
const committedFixturePath = path.join(__dirname, "fixtures", "stream_fixture.json");

interface LayoutLinkFixture { dstNodeRow: number }
interface NodeFrameFixture {
  tick: number; nodeRow: number; nodeId: number;
  cx: number; cy: number; cz: number; radius: number; sphereR: number;
  vrx: number; vry: number; vrz: number; frx: number; fry: number; frz: number;
  selected: number; kindId: number; hovered: number; latchedSel: number;
  chainBeads: { ox: number; oy: number; oz: number; lit: number; litValue: number }[];
  label: string;
  layoutLinks: LayoutLinkFixture[];
  hex: string;
}
interface EdgeFrameFixture {
  tick: number; sx: number; sy: number; sz: number; ex: number; ey: number; ez: number;
  selected: number; label: string;
  hex: string;
}
interface InteriorFrameFixture {
  tick: number; present: number[]; value: number[]; ox: number[]; oy: number[]; oz: number[];
  hex: string;
}
interface StreamFixture {
  nodeFrame: NodeFrameFixture;
  edgeFrame: EdgeFrameFixture;
  interiorFrame: InteriorFrameFixture;
}

function hexToArrayBuffer(hex: string): ArrayBuffer {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return bytes.buffer;
}

function loadFixture(fixturePath: string): StreamFixture {
  return JSON.parse(fs.readFileSync(fixturePath, "utf8")) as StreamFixture;
}

function expectClose(got: number, want: number, field: string) {
  expect(got, field).toBeCloseTo(want, 3);
}

// ── TestStreamFixtureFreshness mirror ───────────────────────────────────────────
//
// Regenerates the fixture live (via `go run ./tools/gen-stream-fixture`, the REAL Go
// packers) into a temp file and byte-diffs it against the committed copy. A stale fixture
// fails HERE with a clear pointer to the regeneration command, rather than as silent
// staleness. Skipped (not silently passed) if `go` is unavailable.
describe("stream fixture freshness", () => {
  it("committed fixture matches a live regeneration from the real Go packers", () => {
    let goAvailable = true;
    try {
      execFileSync("go", ["version"], { cwd: repoRoot, stdio: "ignore" });
    } catch {
      goAvailable = false;
    }
    if (!goAvailable) {
      // eslint-disable-next-line no-console
      console.warn("stream-fixture.test.ts: `go` not found on PATH — skipping freshness check (decode assertions below still run against the committed fixture)");
      return;
    }

    const tmpOut = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "stream-fixture-")), "stream_fixture.json");
    execFileSync("go", ["run", "./tools/gen-stream-fixture", tmpOut], { cwd: repoRoot, stdio: "pipe" });

    const committed = fs.readFileSync(committedFixturePath, "utf8");
    const fresh = fs.readFileSync(tmpOut, "utf8");
    expect(
      fresh,
      "tools/topology-vscode/test/fixtures/stream_fixture.json is STALE relative to the current Go stream-frame packers " +
      "(Buffer/node_stream_frame.go, Buffer/edge_stream_frame.go). Regenerate with:\n" +
      "  go run ./tools/gen-stream-fixture\n" +
      "and commit the result."
    ).toEqual(committed);
  });
});

// ── TestStreamFixtureCrossLanguage mirror ───────────────────────────────────────
describe("stream fixture cross-language decode", () => {
  const fx = loadFixture(committedFixturePath);

  it("decodeNodeStreamFrame agrees with the Go-encoded node fixture", () => {
    const want = fx.nodeFrame;
    const buf = hexToArrayBuffer(want.hex);
    // Decode on the fixture's OWN nodeRow (the fd-arrival row the fixture's NodeId=8 was
    // built to agree with — nodeId = row+1 by construction), not a hardcoded 0: passing the
    // wrong row here would itself trip the id/row mismatch report this column exists to add.
    const decoded = decodeNodeStreamFrame(want.nodeRow, buf);
    expect(decoded, "Go-encoded node stream frame bytes were rejected by the real TS decoder").not.toBeNull();
    if (!decoded) return;

    expect(decoded.tick).toBe(want.tick);
    expect(decoded.label).toBe(want.label);
    expect(decoded.layoutLinkCount).toBe(want.layoutLinks.length);

    const nv = decoded.nodeView;
    expect(readNodeNodeId(nv, 0), "nodeId").toBe(want.nodeId);
    expectClose(readNodeCX(nv, 0), want.cx, "cx");
    expectClose(readNodeCY(nv, 0), want.cy, "cy");
    expectClose(readNodeCZ(nv, 0), want.cz, "cz");
    expectClose(readNodeRadius(nv, 0), want.radius, "radius");
    expectClose(readNodeSphereR(nv, 0), want.sphereR, "sphereR");
    expectClose(readNodeVRX(nv, 0), want.vrx, "vrx");
    expectClose(readNodeVRY(nv, 0), want.vry, "vry");
    expectClose(readNodeVRZ(nv, 0), want.vrz, "vrz");
    expectClose(readNodeFRX(nv, 0), want.frx, "frx");
    expectClose(readNodeFRY(nv, 0), want.fry, "fry");
    expectClose(readNodeFRZ(nv, 0), want.frz, "frz");
    expect(readNodeSelected(nv, 0), "selected").toBe(want.selected);
    expect(readNodeKindId(nv, 0), "kindId").toBe(want.kindId);
    expect(readNodeHovered(nv, 0), "hovered").toBe(want.hovered);
    expect(readNodeLatchedSel(nv, 0), "latchedSel").toBe(want.latchedSel);

    // ChainBead section: node-local offsets, read with the GENERATED ChainBead column
    // readers (the node-stream row stride equals the block's own stride, so there is no
    // separate decoder for these bytes).
    expect(decoded.chainBeadCount, "chainBeadCount").toBe(want.chainBeads.length);
    for (let i = 0; i < want.chainBeads.length; i++) {
      const cb = want.chainBeads[i]!;
      expectClose(readChainBeadOX(decoded.chainBeadView, i), cb.ox, `chainBead[${i}].ox`);
      expectClose(readChainBeadOY(decoded.chainBeadView, i), cb.oy, `chainBead[${i}].oy`);
      expectClose(readChainBeadOZ(decoded.chainBeadView, i), cb.oz, `chainBead[${i}].oz`);
      expect(readChainBeadLit(decoded.chainBeadView, i), `chainBead[${i}].lit`).toBe(cb.lit);
      expect(readChainBeadLitValue(decoded.chainBeadView, i), `chainBead[${i}].litValue`).toBe(cb.litValue);
    }

    // No port section any more (docs/channels-not-ports.md — a port carries no geometry,
    // so the fixture and the decoder both have nothing to carry for it).

    for (let i = 0; i < want.layoutLinks.length; i++) {
      expect(
        readNodeStreamLayoutLinkDstNodeRow(decoded.layoutLinkView, i),
        `layoutLinks[${i}].dstNodeRow`
      ).toBe(want.layoutLinks[i]!.dstNodeRow);
    }
  });

  it("decodeEdgeStreamFrame agrees with the Go-encoded edge fixture", () => {
    const want = fx.edgeFrame;
    const buf = hexToArrayBuffer(want.hex);
    const decoded = decodeEdgeStreamFrame(0, buf);
    expect(decoded, "Go-encoded edge stream frame bytes were rejected by the real TS decoder").not.toBeNull();
    if (!decoded) return;

    expect(decoded.tick).toBe(want.tick);
    expect(decoded.label).toBe(want.label);

    const ev = decoded.edgeView;
    expectClose(readEdgeSX(ev, 0), want.sx, "sx");
    expectClose(readEdgeSY(ev, 0), want.sy, "sy");
    expectClose(readEdgeSZ(ev, 0), want.sz, "sz");
    expectClose(readEdgeEX(ev, 0), want.ex, "ex");
    expectClose(readEdgeEY(ev, 0), want.ey, "ey");
    expectClose(readEdgeEZ(ev, 0), want.ez, "ez");
    expect(readEdgeSelected(ev, 0), "selected").toBe(want.selected);
  });

  it("decodeNodeStreamFrame reports a loud mismatch when NodeId disagrees with the arrival row", () => {
    // The whole point of the NodeId column: a frame's stated identity can now CONTRADICT the
    // row it arrived on, and that must be reported loudly, not silently trusted (see
    // buffer-decode.ts's reportNodeIdMismatch). Decode the same fixture bytes (NodeId=8) on a
    // row that does NOT satisfy id==row+1.
    const want = fx.nodeFrame;
    const wrongRow = want.nodeRow + 1; // id 8 would need row 7, not row 8
    const buf = hexToArrayBuffer(want.hex);
    const errors: string[] = [];
    const spy = vi.spyOn(console, "error").mockImplementation((msg: unknown) => {
      errors.push(String(msg));
    });
    try {
      const decoded = decodeNodeStreamFrame(wrongRow, buf);
      // The mismatch is reported, not swallowed — the frame still decodes (the bytes are
      // otherwise valid), so callers still get a usable view; only the identity check fires.
      expect(decoded, "a mismatched frame must still decode, only the identity check reports").not.toBeNull();
    } finally {
      spy.mockRestore();
    }
    expect(errors.some((e) => e.includes("node-id-row-mismatch"))).toBe(true);
    expect(errors.some((e) => e.includes(`row ${wrongRow}`))).toBe(true);
    expect(errors.some((e) => e.includes(`NodeId ${want.nodeId}`))).toBe(true);
  });

  it("decodeInteriorStreamFrame agrees with the Go-encoded interior fixture", () => {
    const want = fx.interiorFrame;
    const buf = hexToArrayBuffer(want.hex);
    const decoded = decodeInteriorStreamFrame(0, buf);
    expect(decoded, "Go-encoded interior stream frame bytes were rejected by the real TS decoder").not.toBeNull();
    if (!decoded) return;

    expect(decoded.tick).toBe(want.tick);
    const iv = decoded.interiorView;
    for (let i = 0; i < want.present.length; i++) {
      expect(readInteriorPresent(iv, i), `interior[${i}].present`).toBe(want.present[i]);
      expect(readInteriorValue(iv, i), `interior[${i}].value`).toBe(want.value[i]);
      expectClose(readInteriorOX(iv, i), want.ox[i]!, `interior[${i}].ox`);
      expectClose(readInteriorOY(iv, i), want.oy[i]!, `interior[${i}].oy`);
      expectClose(readInteriorOZ(iv, i), want.oz[i]!, `interior[${i}].oz`);
    }
  });
});
