package main

//go:generate go run .

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/dtauraso/wirefold/scripts/genpaths"
)

const (
	kindDirName = "PairNode"
	kindPkgName = "PairNode"
)

func main() {
	genpaths.SetName("Categories/NodeKinds/" + kindDirName + "/portsdef")
	_, srcRoot := genpaths.Roots()
	kindDir := filepath.Join(srcRoot, "NodeKinds", kindDirName)

	ports := parsePortsFromSpec(kindDir)
	if len(ports) == 0 {
		genpaths.Fatalf("%s: SPEC.md has no ## Ports rows — the table is the only declaration of this kind's inputs and outputs, so a kind without one binds nothing", kindDirName)
	}

	outPath := filepath.Join(kindDir, "kind_ports_gen.go")
	if err := writePortsTable(outPath, ports); err != nil {
		genpaths.Fatalf("write %s: %v", outPath, err)
	}
	genpaths.Announce(outPath, len(ports), "ports")

	view, err := parseView(kindDir)
	if err != nil {
		genpaths.Fatalf("%s: SPEC.md ## View: %v", kindDirName, err)
	}
	if view.Kind == "" {
		genpaths.Fatalf("%s: SPEC.md ## View has an empty view.kind", kindDirName)
	}
	if view.KindID == "" {
		genpaths.Fatalf("%s: SPEC.md ## View has no kindId — an id is assigned once per kind and never renumbered, so it is authored, not derived", kindDirName)
	}

	goKind, err := parseGoKindName(kindDir)
	if err != nil {
		genpaths.Fatalf("%s: %v", kindDirName, err)
	}

	defPath := filepath.Join(kindDir, "node-def-gen.ts")
	if err := writeNodeDef(defPath, goKind, view, ports); err != nil {
		genpaths.Fatalf("write %s: %v", defPath, err)
	}
	genpaths.Announce(defPath, 1, "node def")
}

func writeNodeDef(outPath, goKind string, v ViewDef, ports []Port) error {
	var b strings.Builder
	fmt.Fprintf(&b, "// GENERATED by Categories/NodeKinds/%s/portsdef — do not edit.\n", kindDirName)
	b.WriteString("// Source: this kind's own SPEC.md ## View, ## Ports and ## Description.\n")
	b.WriteString("// Regenerate with: go generate ./...\n\n")
	b.WriteString("import type { NodeDef } from \"../node-def\";\n\n")
	b.WriteString("// What this kind looks like in the editor, and the id it carries on the wire.\n")
	b.WriteString("// node-defs.ts collects this fragment together with the other kinds'; the id\n")
	b.WriteString("// is authored in SPEC.md and never renumbered, so a removed kind leaves a gap.\n")
	fmt.Fprintf(&b, "export const KIND_NAME = %q;\n", goKind)
	fmt.Fprintf(&b, "export const KIND_ID = %s;\n", v.KindID)
	fmt.Fprintf(&b, "export const DEF: NodeDef = %s;\n", buildDef(v, ports))
	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}

func buildDef(v ViewDef, ports []Port) string {
	var fields []string
	fields = append(fields, fmt.Sprintf(`bg: "%s"`, v.Bg))
	fields = append(fields, fmt.Sprintf(`border: "%s"`, v.Border))
	fields = append(fields, fmt.Sprintf(`text: "%s"`, v.Text))
	for _, f := range []struct{ name, val string }{
		{"minWidth", v.MinWidth}, {"shape", v.Shape}, {"fill", v.Fill},
		{"stroke", v.Stroke}, {"width", v.Width}, {"height", v.Height},
	} {
		if f.val == "" {
			continue
		}
		if f.name == "minWidth" || f.name == "width" || f.name == "height" {
			fields = append(fields, fmt.Sprintf(`%s: %s`, f.name, f.val))
		} else {
			fields = append(fields, fmt.Sprintf(`%s: "%s"`, f.name, f.val))
		}
	}
	if v.Desc != "" {
		fields = append(fields, fmt.Sprintf(`desc: %q`, v.Desc))
	}
	if in := joinPortsTyped(ports, "in"); in != "" {
		fields = append(fields, fmt.Sprintf(`inputs: [%s]`, in))
	}
	if out := joinPortsTyped(ports, "out"); out != "" {
		fields = append(fields, fmt.Sprintf(`outputs: [%s]`, out))
	}
	return "{ " + strings.Join(fields, ", ") + " }"
}

func joinPortsTyped(ports []Port, dir string) string {
	var parts []string
	for _, p := range ports {
		if p.Direction != dir {
			continue
		}
		ek := p.EdgeKind
		if ek == "" {
			ek = "chain"
		}
		if p.IsMulti {
			parts = append(parts, fmt.Sprintf(`{ name: "%s", kind: "%s", isMulti: true }`, p.ID, ek))
		} else {
			parts = append(parts, fmt.Sprintf(`{ name: "%s", kind: "%s" }`, p.ID, ek))
		}
	}
	return strings.Join(parts, ", ")
}

func portDirExpr(p Port) (string, bool) {
	switch {
	case p.Direction == "in":
		return "PortIn", true
	case p.Direction == "out" && p.IsMulti:
		return "PortBroadcast", true
	case p.Direction == "out":
		return "PortOut", true
	}
	return "", false
}

func writePortsTable(outPath string, ports []Port) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintf(w, "// GENERATED by Categories/NodeKinds/%s/portsdef — do not edit.\n", kindDirName)
	fmt.Fprintln(w, `// Source: this kind's own SPEC.md ## Ports table.`)
	fmt.Fprintln(w, `// Regenerate with: go generate ./...`)
	fmt.Fprintln(w)
	fmt.Fprintf(w, "package %s\n", kindPkgName)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// kindPorts is what this kind's SPEC.md declares, in the order the table`)
	fmt.Fprintln(w, `// lists it. BuilderFor reads this rather than a shared map, so the ports a`)
	fmt.Fprintln(w, `// kind may bind are declared in the kind and nowhere else.`)
	fmt.Fprintln(w, `var kindPorts = []PortSpec{`)
	for _, p := range ports {
		dir, ok := portDirExpr(p)
		if !ok {
			return fmt.Errorf("port %q: unknown direction %q", p.ID, p.Direction)
		}
		fmt.Fprintf(w, "\t{Name: %q, Dir: %s},\n", p.ID, dir)
	}
	fmt.Fprintln(w, `}`)

	w.Flush()
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format: %v", err)
	}
	return os.WriteFile(outPath, formatted, 0o644)
}
