// GENERATED by tools/gen-node-defs — do not edit.
// Source: Trace/Trace.go Kind* constants + BreadcrumbLabels. Regenerate with: npm run gen:node-defs

export const TRACE_EVENT_KINDS = ["recv", "fire", "send", "arrive", "breadcrumb"] as const;

export type TraceEventKind = (typeof TRACE_EVENT_KINDS)[number];

// BREADCRUMB_LABELS is indexed by the buffer EVENT block's Label column
// (Kind==KindBreadcrumb rows only) — see Trace.go's BreadcrumbLabel* consts.
export const BREADCRUMB_LABELS = ["topology-loaded", "row-seed-count-mismatch", "pole-toggle-go", "window_clear", "window_open", "dwell_start", "abc-drag", "bead-place-buffer-full", "drag.commit", "wire-breadcrumbs-dropped", "chain-aim", "neighbor-center-recv", "neighbor-setc-recv", "bead-crud", "pair-seed-unknown", "pair-lattice-adopt", "out-angle-fix", "edge-geom", "edge-beads", "drag-active-persist"] as const;
