// GENERATED by Categories/Chrome/Panels/CardPanel/layout from PanelValueNames in
// panel_values.go — do not edit.
//
// The card panels' values, in the order they sit in the block. The renderer
// learns where that block is from Categories/Chrome/Panels/CardPanel/paths/, which Go
// writes from this same list, so neither side spells a path.

export const CARD_PANEL_VALUE_NAMES = [
  "pillX",
  "pillY",
  "pillW",
  "pillH",
  "pillText",
  "open",
  "boxX",
  "boxY",
  "boxW",
  "boxH",
  "headX",
  "headY",
  "headW",
  "headH",
  "titleText",
  "titleLen",
  "fieldX",
  "fieldY",
  "fieldW",
  "fieldH",
  "keyText",
  "keyLen",
  "valueText",
  "valueLen",
  "fieldEditing",
  "draftText",
  "upX",
  "upY",
  "upW",
  "upH",
  "downX",
  "downY",
  "downW",
  "downH",
] as const;

export type CardPanelValueName = (typeof CARD_PANEL_VALUE_NAMES)[number];
