// GENERATED by Categories/Chrome/Panels/SliderPanel/updateattrs — do not edit.
// Source: SliderPanel.UpdateAttrs. The message kind and the entity kinds an edit can
// address are Drag's, and are imported from Scene/Drag/input-defs.ts.
// Regenerate with: go generate ./...

export const IN_UPDATE_ATTRS = ["speed"] as const;
