package buflayout

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
)

func writeBufferLayoutTSSingletons(outPath string, schema BufLayoutSchema) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: Buffer/bufschema/layout.go  Regenerate: npm run gen:node-defs`)
	fmt.Fprintln(w)

	for _, blk := range schema.Blocks {
		if !isSingletonBlock(blk.name) {
			continue
		}
		writeTSBlockConstsAndReaders(w, blk, true)
	}

	w.Flush()
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}
