package buflayout

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
)

func isSingletonBlock(name string) bool {
	return name == "Overlay" || name == "Camera" || name == "RuleBuilder" || name == "Scene" || name == "Panel"
}

var movedToColumns = map[string]bool{
	"Scene":         true,
	"Panel":         true,
	"Overlay":       true,
	"Camera":        true,
	"NodeRingPoint": true,
	"BeadRingPoint": true,
	"Edge":          true,
	"Node":          true,
	"Interior":      true,
	"EdgeBead":      true,
	"TiltArrow":     true,
}

func hasRow(name string) bool { return !movedToColumns[name] }

func WriteBufferLayoutGo(headerPath, rowsPathA, rowsPathB, singletonsPath string, schema BufLayoutSchema) error {
	fp := buildBufFingerprint(schema)

	if err := writeBufferLayoutGoHeader(headerPath, schema, fp); err != nil {
		return err
	}
	if err := writeBufferLayoutGoRows(rowsPathA, rowsPathB, schema, fp); err != nil {
		return err
	}
	if err := writeBufferLayoutGoSingletons(singletonsPath, schema, fp); err != nil {
		return err
	}
	return nil
}

func writeBufferLayoutGoPreamble(w *bufio.Writer, fp string) {
	writeBufferLayoutGoPreambleFor(w, fp, true)
}

func writeBufferLayoutGoPreambleFor(w *bufio.Writer, fp string, needsImports bool) {
	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: Buffer/bufschema/layout.go  Regenerate: cd tools/topology-vscode && npm run gen:node-defs`)
	fmt.Fprintf(w, "// BUF_LAYOUT_FINGERPRINT: %s\n", fp)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `package Buffer`)
	fmt.Fprintln(w)
	if !needsImports {
		return
	}
	fmt.Fprintln(w, `import (`)
	fmt.Fprintln(w, `	"encoding/binary"`)
	fmt.Fprintln(w, `	"math"`)
	fmt.Fprintln(w, `)`)
	fmt.Fprintln(w)
}

func writeBufferLayoutGoHeaderPreamble(w *bufio.Writer, fp string) {
	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: Buffer/bufschema/layout.go  Regenerate: cd tools/topology-vscode && npm run gen:node-defs`)
	fmt.Fprintf(w, "// BUF_LAYOUT_FINGERPRINT: %s\n", fp)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `package Buffer`)
	fmt.Fprintln(w)
}

func writeBufferLayoutGoHeader(outPath string, schema BufLayoutSchema, fp string) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)
	writeBufferLayoutGoHeaderPreamble(w, fp)

	fmt.Fprintf(w, "// BufLayoutVersionGenerated must equal BufLayoutVersion in layout.go.\n")
	fmt.Fprintf(w, "const BufLayoutVersionGenerated = %d\n", schema.version)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// BufLayoutFingerprintHash is FNV-1a over BUF_LAYOUT_FINGERPRINT above. It rides in`)
	fmt.Fprintln(w, `// every VIEW frame header so the decoder can REFUSE a frame whose layout it was not`)
	fmt.Fprintln(w, `// built for, instead of reading the bytes into the wrong columns and drawing garbage.`)
	fmt.Fprintln(w, `//`)
	fmt.Fprintln(w, `// It is DERIVED, never hand-written: any column added, removed, resized or reordered`)
	fmt.Fprintln(w, `// changes the fingerprint and therefore this value. BufLayoutVersion is a human intent`)
	fmt.Fprintln(w, `// marker and is NOT what the wire check uses — a forgotten bump must not be able to`)
	fmt.Fprintln(w, `// make a skewed layout look compatible.`)
	fmt.Fprintf(w, "const BufLayoutFingerprintHash uint32 = %d\n", fnv1aHash(fp))
	fmt.Fprintln(w)
	fmt.Fprintf(w, "// BufInteriorSlotsPerNodeGenerated must equal BufInteriorSlotsPerNode in layout.go.\n")
	fmt.Fprintf(w, "const BufInteriorSlotsPerNodeGenerated = %d\n", schema.interiorSlotsPerNode)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// BufHeaderSize is the byte width of the retired combined-snapshot frame's header.`)
	fmt.Fprintln(w, `// The combined SCENE/BEAD/NODE/EDGE frame is gone entirely — each goroutine now streams`)
	fmt.Fprintln(w, `// its own per-owner frame (VIEW/EDGE_STREAM/NODE_STREAM/INTERIOR_STREAM — see`)
	fmt.Fprintln(w, `// Buffer/frame_tags.go and memory/feedback_no_single_writer_bridge.md); this constant`)
	fmt.Fprintln(w, `// is a historical layout marker, not consumed by any live decoder:`)
	fmt.Fprintln(w, `// [tick:u32][layoutLinkCount:u32]`)
	fmt.Fprintln(w, `const BufHeaderSize = 8`)

	w.Flush()
	return formatAndWrite(buf, outPath)
}

func formatAndWrite(buf bytes.Buffer, outPath string) error {
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format %s: %w\n--- unformatted ---\n%s", outPath, err, buf.String())
	}
	return os.WriteFile(outPath, formatted, 0644)
}
