// GENERATED by src/Input/gen — do not edit.
// Source: the input layout declared in src/Input/gen.
// Regenerate with: go generate ./...

package File

var InEventKinds = []string{"pointerdown", "pointermove", "pointerup", "wheel", "home", "delete", "key"}

