package kindscan

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
)

func WriteKindImports(outPath, networkPkg string, kinds []KindEntry) error {
	dirs := make([]string, 0, len(kinds))
	for _, k := range kinds {
		dirs = append(dirs, k.Dir)
	}
	sort.Strings(dirs)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by src/schema/gen. DO NOT EDIT.\n\n")
	buf.WriteString("package main\n\nimport (\n")
	for _, d := range dirs {
		fmt.Fprintf(&buf, "\t_ %q\n", networkPkg+"/"+d)
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format: %w", err)
	}
	return os.WriteFile(outPath, formatted, 0644)
}
