// GENERATED by tools/gen-node-defs — do not edit.
// Source: nodes/<Kind>/SPEC.md + bead.Register calls.
// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs

package Buffer

// KindIDUnknown is the sentinel KindId value when a node's kind is not in kindIDMap.
const KindIDUnknown uint8 = 0xFF

// kindIDMap maps a node's Go kind name (PascalCase) to its stable buffer KindId,
// assigned once per kind in nodes/<Kind>/SPEC.md and never renumbered by sort
// order. Id i here ↔ NODE_DEFS_ARRAY[i] on the TS side (gaps left by a removed
// kind get an undefined placeholder there, not a shift).
var kindIDMap = map[string]uint8{
	"TimeEnd":     0,
	"HoldFlip":    1,
	"Time":        2,
	"Input":       3,
	"Pacer":       4,
	"Pulse":       5,
	"SelectRight": 6,
	"SelectLeft":  7,
	"PulseLeft":   8,
	"PulseRight":  9,
	"TimeStart":   10,
	"PairNode":    11,
	"NormalSum":   12,
}

// NodeKindID returns the buffer KindId for a node's Go kind string.
// Returns KindIDUnknown (0xFF) when the kind is not in the registry.
func NodeKindID(kind string) uint8 {
	if id, ok := kindIDMap[kind]; ok {
		return id
	}
	return KindIDUnknown
}

// KnownKinds returns every Go kind name present in kindIDMap. IDs are stable
// and assigned once (see nodes/<Kind>/SPEC.md kindId), so — unlike the id
// space itself — this set is NOT guaranteed contiguous or dense; a removed
// kind just leaves its id unused.
// KindAppearance is what a kind looks like in the node palette: the swatch colours
// and the description, both authored in nodes/<Kind>/SPEC.md alongside the id.
type KindAppearance struct {
	Fill   string
	Stroke string
	Desc   string
}

var kindAppearance = map[string]KindAppearance{
	"TimeEnd":     {Fill: "#fff3e0", Stroke: "#7f0000", Desc: "The end of a time chain: holds what arrives and sends nothing on."},
	"HoldFlip":    {Fill: "#eceff1", Stroke: "#263238", Desc: "Inverts what it receives: a 0 goes out as 1, a 1 as 0."},
	"Time":        {Fill: "#fff3e0", Stroke: "#e65100", Desc: "Holds what arrives and sends on what it was holding, so a value comes out one arrival late."},
	"Input":       {Fill: "#e0e0e0", Stroke: "#666", Desc: "The source: emits its own authored list of values, last one first, optionally repeating."},
	"Pacer":       {Fill: "#e8f5e9", Stroke: "#2e7d32", Desc: "Sends 1 back when the value it receives differs from the last one, and 0 when it repeats."},
	"Pulse":       {Fill: "#e1f5fe", Stroke: "#2196f3", Desc: "Holds the last value it received and drives it out continuously, from the moment it starts."},
	"SelectRight": {Fill: "#fce4ec", Stroke: "#f06292", Desc: "Passes a value on only when both inputs arrive within one window, favouring the RIGHT one."},
	"SelectLeft":  {Fill: "#fce4ec", Stroke: "#880e4f", Desc: "Passes a value on only when both inputs arrive within one window, favouring the LEFT one."},
	"PulseLeft":   {Fill: "#e1f5fe", Stroke: "#90caf9", Desc: "Holds and drives a value like Pulse, feeding the LEFT input of a select gate."},
	"PulseRight":  {Fill: "#e1f5fe", Stroke: "#01579b", Desc: "Holds and drives a value like Pulse, feeding the RIGHT input of a select gate."},
	"TimeStart":   {Fill: "#fff3e0", Stroke: "#ffc400", Desc: "The head of a time chain: holds what arrives and fans the value it was holding to every downstream node at once."},
	"PairNode":    {Fill: "#fff8e1", Stroke: "#f9a825", Desc: "One half of a pair: turns its own tilt vector toward rest by exchanging directions with its partner, one step per arrival."},
	"NormalSum":   {Fill: "#ede7f6", Stroke: "#4527a0", Desc: "Takes a normal from each of two nodes and holds their total, drawn as its own vector."},
}

// AppearanceOf returns a kind's palette appearance, and false when the kind is unknown.
func AppearanceOf(kind string) (KindAppearance, bool) {
	a, ok := kindAppearance[kind]
	return a, ok
}

// KindNameByID is the kind at each id, with an empty string where an id is unused.
func KindNameByID() []string {
	var maxID int
	for _, id := range kindIDMap {
		if int(id) > maxID {
			maxID = int(id)
		}
	}
	out := make([]string, maxID+1)
	for k, id := range kindIDMap {
		out[id] = k
	}
	return out
}

func KnownKinds() []string {
	out := make([]string, 0, len(kindIDMap))
	for k := range kindIDMap {
		out = append(out, k)
	}
	return out
}
