// GENERATED by src/schema/buffer-layout/gen — do not edit.
// Source: the exported constants in Buffer/frame_tags.go, named as they are there.
// Regenerate with: go generate ./...
//
//

export const BUF_BLOCK_TAG_VIEW = 4;

export const BUF_VIEW_FRAME_HEADER_SIZE = 8;

export const BUF_BLOCK_TAG_EDGE_STREAM = 5;

export const BUF_EDGE_STREAM_FRAME_HEADER_SIZE = 4;

export const BUF_BLOCK_TAG_NODE_STREAM = 6;

export const BUF_BLOCK_TAG_INTERIOR_STREAM = 7;

export const BUF_NODE_STREAM_FRAME_HEADER_SIZE = 4;

export const BUF_INTERIOR_STREAM_FRAME_HEADER_SIZE = 4;

export const BUF_BLOCK_TAG_BEAD_STREAM = 8;

export const BUF_BLOCK_TAG_COLUMN = 9;

export const BUF_BEAD_STREAM_FRAME_HEADER_SIZE = 8;
