// GENERATED by Categories/NodeKinds/selectleft/gen — do not edit.
// Source: this kind's own SPEC.md ## Ports table.
// Regenerate with: go generate ./...

package selectleft

// kindPorts is what this kind's SPEC.md declares, in the order the table
// lists it. BuilderFor reads this rather than a shared map, so the ports a
// kind may bind are declared in the kind and nowhere else.
var kindPorts = []PortSpec{
	{Name: "FromLeft", Dir: PortIn},
	{Name: "FromRight", Dir: PortIn},
	{Name: "ToPassed", Dir: PortOut},
}
