// GENERATED by src/Buffer/gen. Do not edit.
// Source: the Overlay block(s) in this directory.

import {
  COL_STREAM_BASE_OVERLAY,
} from "../Buffer/column-streams-gen";

export const COL_STREAM_OVERLAY_DRAG_NODE_ROW = COL_STREAM_BASE_OVERLAY + 0;
export const COL_STREAM_OVERLAY_EDIT_REFUSED = COL_STREAM_BASE_OVERLAY + 1;
export const COL_STREAM_OVERLAY_SCENE_EDITABLE = COL_STREAM_BASE_OVERLAY + 2;
export const COL_STREAM_OVERLAY_SCENE_KINDS = COL_STREAM_BASE_OVERLAY + 3;
export const COL_STREAM_OVERLAY_SPEED = COL_STREAM_BASE_OVERLAY + 4;
