// GENERATED by src/Overlay/gen — do not edit.
// Source: the OVERLAY_FLAGS block in src/Input/messages.ts.
// Regenerate with: go generate ./...
//
// The flags ride ONE file, in this order. The order IS the layout: each value is
// a u32 length then that many bytes. src/Overlay/paths/block.bin hands the
// renderer the same path, so neither side builds this string itself.

package Overlay

const BlockRelPath = "view/overlays.bin"

var FlagNames = []string{
	"tori",
	"scenePoles",
	"nodePoles",
	"handholds",
	"labelsGlobal",
	"overlays",
	"nodeBody",
	"nodeRing",
	"ringPick",
	"selectionRing",
	"hoverRing",
	"sceneVectors",
	"ruleChannels",
	"nodePoleSphere",
	"allPoleSpheres",
}
