package main

//go:generate go run .

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/dtauraso/beadnetwork/scripts/genpaths"

	"github.com/dtauraso/beadnetwork/Categories/Scene/Drag"
)

func main() {
	genpaths.SetName("Categories/Scene/Drag/inputdefs")
	_, srcRoot := genpaths.Roots()

	var b strings.Builder
	fmt.Fprintln(&b, "// GENERATED by Categories/Scene/Drag/inputdefs — do not edit.")
	fmt.Fprintln(&b, "// Source: Drag's kinds.go and stdin_reader.go, the only declarations of the")
	fmt.Fprintln(&b, "// TS -> Go record vocabulary. Every sender reads its message kind from here.")
	fmt.Fprintln(&b, "// Regenerate with: go generate ./...")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "export const IN_KIND_RAW_INPUT = %d;\n", Drag.KindRawInput)
	fmt.Fprintf(&b, "export const IN_KIND_EDIT_UPDATE = %d;\n\n", Drag.KindEditUpdate)
	writeList(&b, "IN_EVENT_KINDS", Drag.EventKinds)
	fmt.Fprintln(&b)
	writeList(&b, "IN_HIT_KINDS", Drag.HitKinds)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// EDIT_UPDATE_KINDS_START")
	writeList(&b, "IN_UPDATE_KINDS", Drag.UpdateKinds)
	fmt.Fprintln(&b, "// EDIT_UPDATE_KINDS_END")
	fmt.Fprintln(&b)

	outPath := filepath.Join(srcRoot, "Scene", "Drag", "input-defs.ts")
	if err := genpaths.WriteIfChanged(outPath, []byte(b.String()), 0o644); err != nil {
		genpaths.Fatalf("write %s: %v", outPath, err)
	}
	genpaths.Announce(outPath, len(Drag.EventKinds)+len(Drag.HitKinds)+len(Drag.UpdateKinds), "input, hit and update kinds")
}

func writeList(b *strings.Builder, name string, items []string) {
	fmt.Fprintf(b, "export const %s = [", name)
	for i, v := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%q", v)
	}
	fmt.Fprintln(b, "] as const;")
}
