#!/usr/bin/env bash
# Writes docs/pair-node/root.js, which tells the docs pages this clone's absolute
# path so their source links can be vscode://file/<abs path> URIs.
#
# The path is machine-specific, so root.js is GITIGNORED and generated rather than
# committed. Run this once per clone:
#
#     bash tools/docs-root.sh
#
# Without it the pages still render; the source names just do not link.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/docs/pair-node/root.js"

# Quoted by hand rather than with ${root@Q}: macOS ships bash 3.2, which does not
# have that expansion. A path may legitimately contain a backslash or a quote.
esc=$(printf '%s' "$root" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')

cat > "$out" <<EOF
// Generated by tools/docs-root.sh — gitignored, machine-specific.
// This clone's absolute path, so the source links can address VS Code.
window.WIREFOLD_ROOT = "$esc";
EOF

echo "wrote $out"
echo "  root = $root"
