// GENERATED by Categories/Chrome/Pills/values from PillValueNames in pill_values.go —
// do not edit.
//
// The overlays popover's values, in the order they sit in the block. The
// renderer learns where that block is from Categories/Chrome/Pills/paths/, which Go
// writes from this same list, so neither side spells a path.

export const OVERLAYS_PILL_VALUE_NAMES = [
  "scrollY",
  "pillX",
  "pillY",
  "pillW",
  "pillH",
  "open",
  "active",
  "popoverX",
  "popoverY",
  "popoverW",
  "popoverH",
  "labelText",
  "rowKind",
  "rowDepth",
  "rowX",
  "rowY",
  "rowW",
  "rowH",
  "rowTextData",
  "rowTextLen",
  "rowIconData",
  "rowIconLen",
  "rowOn",
  "rowDisabled",
  "rowCountOn",
  "rowCountAll",
  "countX",
  "countY",
  "countW",
  "countH",
] as const;

export type OverlaysPillValueName = (typeof OVERLAYS_PILL_VALUE_NAMES)[number];
