// GENERATED by src/Buffer/gen — do not edit.
// Source: src/Buffer/layout_version.go  Regenerate: go generate ./...
// BUF_LAYOUT_FINGERPRINT: version:58

package bufferlayout

// BufLayoutVersionGenerated must equal BufLayoutVersion in layout.go.
const BufLayoutVersionGenerated = 58

// BufLayoutFingerprintHash is FNV-1a over BUF_LAYOUT_FINGERPRINT above. It rides in
// every VIEW frame header so the decoder can REFUSE a frame whose layout it was not
// built for, instead of reading the bytes into the wrong columns and drawing garbage.
//
// It is DERIVED, never hand-written: any column added, removed, resized or reordered
// changes the fingerprint and therefore this value. BufLayoutVersion is a human intent
// marker and is NOT what the wire check uses — a forgotten bump must not be able to
// make a skewed layout look compatible.
const BufLayoutFingerprintHash uint32 = 3489316442
