// GENERATED by src/Buffer/gen — do not edit.
// Source: Buffer/bufschema/layout.go  Regenerate: go generate ./...

// This half holds the Send, Arrive, Breadcrumb block(s). Row blocks are split across two files
// purely to stay under check-file-size.sh's limit — the division is by position in
// Buffer/bufschema/layout.go, not by meaning, so neither file is a category.

// ── Send block ───────────────────────────────────────────────
export const SEND_COL_NODE_ROW                   = 0; // i32
export const SEND_COL_TARGET_ROW                 = 4; // i32
export const SEND_COL_VALUE                      = 8; // i32
export const SEND_COL_BEAD_STEPS                 = 12; // f32
export const SEND_STRIDE                         = 16;

export function readSendNodeRow(view: DataView, row: number): number { return view.getInt32(row * SEND_STRIDE + SEND_COL_NODE_ROW, true); }
export function readSendTargetRow(view: DataView, row: number): number { return view.getInt32(row * SEND_STRIDE + SEND_COL_TARGET_ROW, true); }
export function readSendValue(view: DataView, row: number): number { return view.getInt32(row * SEND_STRIDE + SEND_COL_VALUE, true); }
export function readSendBeadSteps(view: DataView, row: number): number { return view.getFloat32(row * SEND_STRIDE + SEND_COL_BEAD_STEPS, true); }

// ── Arrive block ─────────────────────────────────────────────
export const ARRIVE_COL_NODE_ROW                 = 0; // i32
export const ARRIVE_COL_VALUE                    = 4; // i32
export const ARRIVE_COL_BEAD                     = 8; // u32
export const ARRIVE_STRIDE                       = 12;

export function readArriveNodeRow(view: DataView, row: number): number { return view.getInt32(row * ARRIVE_STRIDE + ARRIVE_COL_NODE_ROW, true); }
export function readArriveValue(view: DataView, row: number): number { return view.getInt32(row * ARRIVE_STRIDE + ARRIVE_COL_VALUE, true); }
export function readArriveBead(view: DataView, row: number): number { return view.getUint32(row * ARRIVE_STRIDE + ARRIVE_COL_BEAD, true); }

// ── Breadcrumb block ─────────────────────────────────────────
export const BREADCRUMB_COL_NODE_ROW             = 0; // i32
export const BREADCRUMB_COL_PORT_ROW             = 4; // i32
export const BREADCRUMB_COL_TARGET_ROW           = 8; // i32
export const BREADCRUMB_COL_TARGET_PORT_ROW      = 12; // i32
export const BREADCRUMB_COL_EDGE_ROW             = 16; // i32
export const BREADCRUMB_COL_SLOT                 = 20; // i32
export const BREADCRUMB_COL_VALUE                = 24; // i32
export const BREADCRUMB_COL_X                    = 28; // f32
export const BREADCRUMB_COL_Y                    = 32; // f32
export const BREADCRUMB_COL_Z                    = 36; // f32
export const BREADCRUMB_COL_LABEL                = 40; // u8
export const BREADCRUMB_COL_DEBUG                = 41; // u8
export const BREADCRUMB_COL_TEXT_OFF             = 42; // u32
export const BREADCRUMB_COL_TEXT_LEN             = 46; // u32
export const BREADCRUMB_STRIDE                   = 50;

export function readBreadcrumbNodeRow(view: DataView, row: number): number { return view.getInt32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_NODE_ROW, true); }
export function readBreadcrumbPortRow(view: DataView, row: number): number { return view.getInt32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_PORT_ROW, true); }
export function readBreadcrumbTargetRow(view: DataView, row: number): number { return view.getInt32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_TARGET_ROW, true); }
export function readBreadcrumbTargetPortRow(view: DataView, row: number): number { return view.getInt32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_TARGET_PORT_ROW, true); }
export function readBreadcrumbEdgeRow(view: DataView, row: number): number { return view.getInt32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_EDGE_ROW, true); }
export function readBreadcrumbSlot(view: DataView, row: number): number { return view.getInt32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_SLOT, true); }
export function readBreadcrumbValue(view: DataView, row: number): number { return view.getInt32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_VALUE, true); }
export function readBreadcrumbX(view: DataView, row: number): number { return view.getFloat32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_X, true); }
export function readBreadcrumbY(view: DataView, row: number): number { return view.getFloat32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_Y, true); }
export function readBreadcrumbZ(view: DataView, row: number): number { return view.getFloat32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_Z, true); }
export function readBreadcrumbLabel(view: DataView, row: number): number { return view.getUint8(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_LABEL); }
export function readBreadcrumbDebug(view: DataView, row: number): number { return view.getUint8(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_DEBUG); }
export function readBreadcrumbTextOff(view: DataView, row: number): number { return view.getUint32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_TEXT_OFF, true); }
export function readBreadcrumbTextLen(view: DataView, row: number): number { return view.getUint32(row * BREADCRUMB_STRIDE + BREADCRUMB_COL_TEXT_LEN, true); }

