// GENERATED by src/Buffer/gen — do not edit.
// Source: src/Buffer/layout_version.go  Regenerate: go generate ./...
// BUF_LAYOUT_FINGERPRINT: version:55|interiorSlotsPerNode:4|block:Scene[NodeCount:i32:0,EdgeCount:i32:4]:stride:8|block:Recv[NodeRow:i32:0,Value:i32:4]:stride:8|block:Fire[NodeRow:i32:0]:stride:4|block:Send[NodeRow:i32:0,TargetRow:i32:4,Value:i32:8,BeadSteps:f32:12]:stride:16|block:Arrive[NodeRow:i32:0,Value:i32:4,Bead:u32:8]:stride:12|block:Breadcrumb[NodeRow:i32:0,PortRow:i32:4,TargetRow:i32:8,TargetPortRow:i32:12,EdgeRow:i32:16,Slot:i32:20,Value:i32:24,X:f32:28,Y:f32:32,Z:f32:36,Label:u8:40,Debug:u8:41,TextOff:u32:42,TextLen:u32:46]:stride:50

package bufferlayout

import (
	"encoding/binary"
	"math"
)

// This half holds the Send, Arrive, Breadcrumb block(s). Row blocks are split across two files
// purely to stay under check-file-size.sh's limit — the division is by position in
// Buffer/bufschema/layout.go, not by meaning, so neither file is a category.

// ── Send block ───────────────────────────────────────────────
const (
	BufSendColNodeRow   = 0  // i32
	BufSendColTargetRow = 4  // i32
	BufSendColValue     = 8  // i32
	BufSendColBeadSteps = 12 // f32
	BufSendStride       = 16
)

// SetSendRow writes one Send row into buf[row*BufSendStride:].
func SetSendRow(buf []byte, row int, nodeRow int32, targetRow int32, value int32, beadSteps float32) {
	off := row * BufSendStride
	binary.LittleEndian.PutUint32(buf[off+0:], uint32(nodeRow))
	binary.LittleEndian.PutUint32(buf[off+4:], uint32(targetRow))
	binary.LittleEndian.PutUint32(buf[off+8:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+12:], math.Float32bits(beadSteps))
}

// ── Arrive block ─────────────────────────────────────────────
const (
	BufArriveColNodeRow = 0 // i32
	BufArriveColValue   = 4 // i32
	BufArriveColBead    = 8 // u32
	BufArriveStride     = 12
)

// SetArriveRow writes one Arrive row into buf[row*BufArriveStride:].
func SetArriveRow(buf []byte, row int, nodeRow int32, value int32, bead uint32) {
	off := row * BufArriveStride
	binary.LittleEndian.PutUint32(buf[off+0:], uint32(nodeRow))
	binary.LittleEndian.PutUint32(buf[off+4:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+8:], bead)
}

// ── Breadcrumb block ─────────────────────────────────────────
const (
	BufBreadcrumbColNodeRow       = 0  // i32
	BufBreadcrumbColPortRow       = 4  // i32
	BufBreadcrumbColTargetRow     = 8  // i32
	BufBreadcrumbColTargetPortRow = 12 // i32
	BufBreadcrumbColEdgeRow       = 16 // i32
	BufBreadcrumbColSlot          = 20 // i32
	BufBreadcrumbColValue         = 24 // i32
	BufBreadcrumbColX             = 28 // f32
	BufBreadcrumbColY             = 32 // f32
	BufBreadcrumbColZ             = 36 // f32
	BufBreadcrumbColLabel         = 40 // u8
	BufBreadcrumbColDebug         = 41 // u8
	BufBreadcrumbColTextOff       = 42 // u32
	BufBreadcrumbColTextLen       = 46 // u32
	BufBreadcrumbStride           = 50
)

// SetBreadcrumbRow writes one Breadcrumb row into buf[row*BufBreadcrumbStride:].
func SetBreadcrumbRow(buf []byte, row int, nodeRow int32, portRow int32, targetRow int32, targetPortRow int32, edgeRow int32, slot int32, value int32, x float32, y float32, z float32, label uint8, debug uint8, textOff uint32, textLen uint32) {
	off := row * BufBreadcrumbStride
	binary.LittleEndian.PutUint32(buf[off+0:], uint32(nodeRow))
	binary.LittleEndian.PutUint32(buf[off+4:], uint32(portRow))
	binary.LittleEndian.PutUint32(buf[off+8:], uint32(targetRow))
	binary.LittleEndian.PutUint32(buf[off+12:], uint32(targetPortRow))
	binary.LittleEndian.PutUint32(buf[off+16:], uint32(edgeRow))
	binary.LittleEndian.PutUint32(buf[off+20:], uint32(slot))
	binary.LittleEndian.PutUint32(buf[off+24:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+28:], math.Float32bits(x))
	binary.LittleEndian.PutUint32(buf[off+32:], math.Float32bits(y))
	binary.LittleEndian.PutUint32(buf[off+36:], math.Float32bits(z))
	buf[off+40] = label
	buf[off+41] = debug
	binary.LittleEndian.PutUint32(buf[off+42:], textOff)
	binary.LittleEndian.PutUint32(buf[off+46:], textLen)
}
