// GENERATED by src/Buffer/gen — do not edit.
// Source: src/Buffer/layout_version.go  Regenerate: go generate ./...
// BUF_LAYOUT_FINGERPRINT: version:58|block:Recv[NodeRow:i32:0,Value:i32:4]:stride:8|block:Fire[NodeRow:i32:0]:stride:4|block:Send[NodeRow:i32:0,TargetRow:i32:4,Value:i32:8,BeadSteps:f32:12]:stride:16|block:Arrive[NodeRow:i32:0,Value:i32:4,Bead:u32:8]:stride:12|block:Breadcrumb[NodeRow:i32:0,PortRow:i32:4,TargetRow:i32:8,TargetPortRow:i32:12,EdgeRow:i32:16,Slot:i32:20,Value:i32:24,X:f32:28,Y:f32:32,Z:f32:36,Label:u8:40,Debug:u8:41,TextOff:u32:42,TextLen:u32:46]:stride:50

/** Schema version — must match BufLayoutVersion in Buffer/bufschema/layout.go. */
export const BUF_LAYOUT_VERSION = 58;

/** FNV-1a over BUF_LAYOUT_FINGERPRINT above — the layout this BUNDLE was built for.
 * Every VIEW frame carries Go's copy; the decoder compares them and refuses a frame
 * from a different layout rather than decoding its bytes into the wrong columns.
 * Derived from the fingerprint, so it cannot be forgotten the way a hand-bumped
 * version number can. */
export const BUF_LAYOUT_FINGERPRINT_HASH = 48636798;

export * from './buffer-layout-rows-gen';
export * from './buffer-layout-rows2-gen';
export * from './buffer-layout-singletons-gen';
