// GENERATED by src/Buffer/gen — do not edit.
// Source: src/Buffer/layout_version.go  Regenerate: go generate ./...
// BUF_LAYOUT_FINGERPRINT: version:58|block:Recv[NodeRow:i32:0,Value:i32:4]:stride:8|block:Fire[NodeRow:i32:0]:stride:4|block:Send[NodeRow:i32:0,TargetRow:i32:4,Value:i32:8,BeadSteps:f32:12]:stride:16|block:Arrive[NodeRow:i32:0,Value:i32:4,Bead:u32:8]:stride:12|block:Breadcrumb[NodeRow:i32:0,PortRow:i32:4,TargetRow:i32:8,TargetPortRow:i32:12,EdgeRow:i32:16,Slot:i32:20,Value:i32:24,X:f32:28,Y:f32:32,Z:f32:36,Label:u8:40,Debug:u8:41,TextOff:u32:42,TextLen:u32:46]:stride:50

package bufferlayout

// BufLayoutVersionGenerated must equal BufLayoutVersion in layout.go.
const BufLayoutVersionGenerated = 58

// BufLayoutFingerprintHash is FNV-1a over BUF_LAYOUT_FINGERPRINT above. It rides in
// every VIEW frame header so the decoder can REFUSE a frame whose layout it was not
// built for, instead of reading the bytes into the wrong columns and drawing garbage.
//
// It is DERIVED, never hand-written: any column added, removed, resized or reordered
// changes the fingerprint and therefore this value. BufLayoutVersion is a human intent
// marker and is NOT what the wire check uses — a forgotten bump must not be able to
// make a skewed layout look compatible.
const BufLayoutFingerprintHash uint32 = 48636798
