// GENERATED by cmd/gen-node-defs. Do not edit.

export const COLUMNS_PER_NODE_STREAM = 145;
export const COLUMNS_PER_EDGE_STREAM = 11;
export const COLUMNS_IN_SINGLETON_STREAMS = 292;

export function columnStreamCount(nodes: number, edges: number): number {
  return nodes * COLUMNS_PER_NODE_STREAM + edges * COLUMNS_PER_EDGE_STREAM + COLUMNS_IN_SINGLETON_STREAMS;
}

export const COL_STREAM_BASE_NODE = 0;
export const COL_STREAM_BASE_INTERIOR = 54;
export const COL_STREAM_BASE_EDGE_BEAD = 59;
export const COL_STREAM_BASE_TILT_ARROW = 80;
export const COL_STREAM_BASE_CHANNEL_VECTOR = 113;
export const COL_STREAM_BASE_EDGE = 0;
export const COL_STREAM_BASE_CAMERA = 0;
export const COL_STREAM_BASE_OVERLAY = 9;
export const COL_STREAM_BASE_PANEL = 29;
export const COL_STREAM_BASE_SCENE = 40;
export const COL_STREAM_BASE_NODE_RING_POINT = 49;
export const COL_STREAM_BASE_BEAD_RING_POINT = 52;
export const COL_STREAM_BASE_SPEED_PANEL = 55;
export const COL_STREAM_BASE_TILT_PANEL = 72;
export const COL_STREAM_BASE_ANGLE_PILL = 101;
export const COL_STREAM_BASE_NODES_PILL = 138;
export const COL_STREAM_BASE_OVERLAYS_PILL = 175;
export const COL_STREAM_BASE_FIT_CHIP = 205;
export const COL_STREAM_BASE_TAB_STRIP = 210;
export const COL_STREAM_BASE_RULES_PANEL = 221;
export const COL_STREAM_BASE_POINTER_TARGET = 284;

