// GENERATED by src/Buffer/gen — do not edit.
// Source: src/Node/Wiring/nodegeom/curve_params.go CurveParam* constants.
// Regenerate with: go generate ./...

export const CURVE_PARAM_NODE_RADIUS_DIVISOR = 4;
export const CURVE_PARAM_TILT_VECTOR_ANGLE_STEP = 0.2617993877991494;
