// GENERATED by Categories/Scene/Handholds/shading — do not edit.
// Source: Categories/Scene/Handholds/shading_params.go ShadingParam* constants.
// Regenerate with: go generate ./...
//
// Go owns the shading PARAMETER values (MODEL.md). TS reads these and applies
// them to GPU materials / bakes the env map from them — no shading values of its
// own. The GPU machinery (three.js materials, PMREM bake, binding) stays in TS.

export const SHADING_PARAM_HANDHOLD_COLOR = "#cc8844";
export const SHADING_PARAM_HANDHOLD_EMISSIVE = "#cc8844";
export const SHADING_PARAM_HANDHOLD_EMISSIVE_INTENSITY = 0.6;
export const SHADING_PARAM_HANDHOLD_OPACITY = 0.9;
export const SHADING_PARAM_HANDHOLD_RADIUS_RATIO = 0.04;
export const SHADING_PARAM_HANDHOLD_MIN_RADIUS = 3.0;
