// GENERATED by src/schema/buffer-layout/gen. Do not edit.
// Source: the FitChip block(s) in this directory.

import {
  COL_STREAM_BASE_FIT_CHIP,
} from "../../../schema/buffer-layout/column-streams-gen";

export const COL_STREAM_FIT_CHIP_X = COL_STREAM_BASE_FIT_CHIP + 0;
export const COL_STREAM_FIT_CHIP_Y = COL_STREAM_BASE_FIT_CHIP + 1;
export const COL_STREAM_FIT_CHIP_W = COL_STREAM_BASE_FIT_CHIP + 2;
export const COL_STREAM_FIT_CHIP_H = COL_STREAM_BASE_FIT_CHIP + 3;
export const COL_STREAM_FIT_CHIP_LABEL_TEXT = COL_STREAM_BASE_FIT_CHIP + 4;
