// GENERATED by Categories/NodeKinds/PulseRight/gen — do not edit.
// Source: this kind's own SPEC.md ## View, ## Ports and ## Description.
// Regenerate with: go generate ./...

import type { NodeDef } from "../node-def";

// What this kind looks like in the editor, and the id it carries on the wire.
// node-defs.ts collects this fragment together with the other kinds'; the id
// is authored in SPEC.md and never renumbered, so a removed kind leaves a gap.
export const KIND_NAME = "PulseRight";
export const KIND_ID = 9;
export const DEF: NodeDef = { bg: "#e1f5fe", border: "#01579b", text: "#01579b", minWidth: 90, shape: "rect", fill: "#e1f5fe", stroke: "#01579b", width: 90, height: 60, desc: "Holds and drives a value like Pulse, feeding the RIGHT input of a select gate.", inputs: [{ name: "In", kind: "chain" }], outputs: [{ name: "Out", kind: "chain" }] };
