// GENERATED by Categories/Scene/structuraledit/kindports — do not edit.
// Source: Categories/NodeKinds/<Kind>/SPEC.md ## Ports table.
// Regenerate with: go generate ./...

package structuraledit

// KindPorts maps each runtime kind to the inputs and outputs its SPEC.md
// declares, in the same order the table lists them. Binding reads this
// instead of a hand-written list, so a kind declares its ports in one place
// and the runtime and the editor cannot disagree about them.
type PortDir int

const (
	PortIn PortDir = iota
	PortOut
	PortBroadcast
)

type PortSpec struct {
	Name string
	Dir  PortDir
}

func FirstPortOfDir(ports []PortSpec, dir PortDir) (string, bool) {
	for _, p := range ports {
		if p.Dir == dir {
			return p.Name, true
		}
	}
	return "", false
}

var KindPorts = map[string][]PortSpec{
	"Input": {
		{Name: "OutCadence", Dir: PortOut},
		{Name: "ToExcitatory", Dir: PortOut},
		{Name: "FeedbackIn", Dir: PortIn},
	},
	"PairNode": {
		{Name: "In", Dir: PortIn},
		{Name: "Out", Dir: PortOut},
	},
	"Pulse": {
		{Name: "In", Dir: PortIn},
		{Name: "Out", Dir: PortOut},
		{Name: "OutFanout", Dir: PortOut},
	},
	"PulseLeft": {
		{Name: "In", Dir: PortIn},
		{Name: "Out", Dir: PortOut},
	},
	"PulseRight": {
		{Name: "In", Dir: PortIn},
		{Name: "Out", Dir: PortOut},
	},
	"SelectLeft": {
		{Name: "FromLeft", Dir: PortIn},
		{Name: "FromRight", Dir: PortIn},
		{Name: "ToPassed", Dir: PortOut},
	},
	"SelectRight": {
		{Name: "FromLeft", Dir: PortIn},
		{Name: "FromRight", Dir: PortIn},
		{Name: "ToPassed", Dir: PortOut},
	},
	"Time": {
		{Name: "In", Dir: PortIn},
		{Name: "ToNext", Dir: PortBroadcast},
	},
	"TimeEnd": {
		{Name: "In", Dir: PortIn},
	},
	"TimeStart": {
		{Name: "In", Dir: PortIn},
		{Name: "ToNext", Dir: PortBroadcast},
	},
}
