// GENERATED by: go generate ./... (regenerate after editing wire:"..." tags in nodes/Wiring/loadspec/topo_spec.go)
// Source: nodes/Wiring/loadspec/topo_spec.go wire:"prop,..." tags. Do not edit by hand.

export interface WirePropDef {
  tsType: string;
  required: boolean;
}

export const WIRE_PROPS: Record<string, WirePropDef> = {
  label:       { tsType: "string",    required: true },
};

// Derived from WIRE_PROPS — do not hand-edit. Consumed by Edge and EdgeData.
export type WireProps = {
  label: string;
};
